; ===========================================================================
; NASM v2.14.02 - NETWIDE ASSEMBLER FOR TRDOS 386 - Erdogan Tan - 18/09/2026 
; Disassembled from "nasm.c" (Dissassembler: IDA)
; NASM Syntax: Erdogan Tan
; Last Update: 25/09/2026
; ===========================================================================
; bss.asm
; -------
; This file will be included in the "nasm386.asm" file
; Inclusion order: the last included file

; target: NASM.PRG (flat binary)
; main assembly file: nasm386.asm
; library section: libnasm.asm
; TRDOS 386 functions: system.asm 
; data section: data.asm
; bss section: bss.asm
; launcher: crt0.asm

;
; +-------------------------------------------------------------------------+
; |   This file has been generated by The Interactive Disassembler (IDA)    |
; |           Copyright (c) 2018 Hex-Rays, <support@hex-rays.com>           |
; |                            Freeware version                             |
; +-------------------------------------------------------------------------+
;

; File Name   : C:\Users\90542\OneDrive\Masaüstü\nasm_214_c_o\nasm.o
; Format      : ELF for Intel 386 (Relocatable)
;
; Source File : 'nasm.c'

; ===========================================================================
; BSS (uninitialized data)
; ===========================================================================

section .bss

bss_start:

ABSOLUTE bss_start

alignb 4

; ---------------------------------------------------------------------------
; nasm.asm (nasm.c) 
; ---------------------------------------------------------------------------

using_debug_info:
                resd 1                    ; ...
opt_verbose_info:
                resd 1                    ; ...
debug_format:   resd 1                    ; ...
keep_all:       resd 1                    ; ...
pass0:          resd 1                    ; ...

alignb 16

passn:          resd 1                    ; ...
                resd 1
pass1:          resd 1                    ; ...
pass2:          resd 1                    ; ...

official_compile_time:
                resb 96                   ; ...

inname:         resd 1                    ; ...

outname:        resd 1                    ; ...
listname:       resd 1                    ; ...
errname:        resd 1                    ; ...
globallineno:   resd 1                    ; ...

alignb 8

dfmt:           resd 1                    ; ...
error_file:     resd 1                    ; ...
cpu:            resb 16                   ; ...
cmd_cpu:        resb 16                   ; ...
location:       resd 1                    ; ...

alignb 16

in_absolute:    resd 1                    ; ...

alignb 8

absolute:       resd 1                    ; ...
                resb 12
offsets:        resd 1                    ; ...
forwrefs:       resd 1                    ; ...
forwref:        resd 1                    ; ...
preproc:        resd 1                    ; ...
include_path:   resd 1                    ; ...
pp_noline:      resd 1                    ; ...
operating_mode: resd 1                    ; ...
depend_list:    resd 1                    ; ...
want_usage:     resd 1                    ; ...
terminate_after_phase:
                resd 1                    ; ...

; ---------------------------------------------------------------------------
; errfile.asm (errfile.c)
; ---------------------------------------------------------------------------

error_file:     resd 1

; ---------------------------------------------------------------------------
; string.asm (string.c)
; ---------------------------------------------------------------------------

nasm_tolower_tab:
                resb 256

; ---------------------------------------------------------------------------
; srcfile.asm (srcfile.c)
; ---------------------------------------------------------------------------

filename_hash: resb 16

; ---------------------------------------------------------------------------
; zerobuf.asm (zerobuf.c)
; ---------------------------------------------------------------------------

; const uint8_t zero_buffer[ZERO_BUF_SIZE];

zero_buffer:   resb 65536


; ---------------------------------------------------------------------------

bss_end:
