; ===========================================================================
; NASM v2.14.02 - NETWIDE ASSEMBLER FOR TRDOS 386 - Erdogan Tan - 18/09/2026 
; Disassembled from "file.c" (Dissassembler: IDA)
; NASM Syntax: Erdogan Tan
; Last Update: 23/09/2026
; ===========================================================================
; file.asm
; --------
; This file will be included in the "nasm386.asm" file
; Inclusion order: 7

; target: NASM.PRG (flat binary)
; main assembly file: nasm386.asm
; library section: libnasm.asm
; TRDOS 386 functions: system.asm 
; data section: data.asm
; bss section: bss.asm
; launcher: crt0.asm

;
; +-------------------------------------------------------------------------+
; |   This file has been generated by The Interactive Disassembler (IDA)    |
; |           Copyright (c) 2018 Hex-Rays, <support@hex-rays.com>           |
; |                            Freeware version                             |
; +-------------------------------------------------------------------------+
;

; File Name   : C:\Users\90542\OneDrive\Masaüstü\file_tcc.o
; File Name   : C:\Users\90542\OneDrive\Masaüstü\file.o
; Format      : ELF for Intel 386 (Relocatable)
;
; Source File : 'file.c'

; ===========================================================================
; CODE
; ===========================================================================

; section .text

; =============== S U B R O U T I N E =======================================

; ---------------------------------------------------------------------------
; Function: nasm_read
;
; Description: read input file
;
; C Declaration: void nasm_read(void *ptr, size_t size, FILE *f)
;
; Input (Stack): [EBP+8]  = *ptr (buffer)
;                [EBP+12] = size (read count)
;                [EBP+16] = *f (file descriptor, c type)
;
; Output: none
;
; Modified Registers: EAX, ECX, (EDX)
; ---------------------------------------------------------------------------

%assign n      -4
%assign ptr     8
%assign size    0Ch
%assign f       10h

nasm_read:
                push    ebp
                mov     ebp, esp
                sub     esp, 4
                nop
                mov     eax, [ebp+f]
                push    eax
                mov     eax, [ebp+size]
                push    eax
                mov     eax, 1
                push    eax
                mov     eax, [ebp+ptr]
                push    eax
                call    fread
                add     esp, 16
                mov     [ebp+n], eax    ; size_t n = fread(ptr, 1, size, f);
                mov     eax, [ebp+f]
                push    eax
                call    ferror          ; if (ferror(f)) {
                add     esp, 4
                test    eax, eax
                jz      nr_1
                call    _errno
                mov     ecx, [eax]
                push    ecx
                call    strerror
                add     esp, 4
                push    eax
                mov     eax, L_0	; "unable to read input: %s"
                push    eax
                mov     eax, 0
                push    eax
                call    nasm_fatal      ; nasm_fatal(0, "unable to read input: %s", strerror(errno));
                add     esp, 12
                jmp     nr_3
; ---------------------------------------------------------------------------

nr_1:                                   ; ...
                mov     eax, [ebp+n]    ;  } else if (n != size || feof(f)) {
                mov     ecx, [ebp+size]
                cmp     eax, ecx
                jnz     nr_2
                mov     eax, [ebp+f]
                push    eax
                call    feof
                add     esp, 4
                test    eax, eax
                jnz     nr_2
                jmp     nr_3
; ---------------------------------------------------------------------------

nr_2:                                   ; ...
                mov     eax, L_1	; "fatal short read on input"
                push    eax
                mov     eax, 0
                push    eax
                call    nasm_fatal      ; nasm_fatal(0, "fatal short read on input");
                add     esp, 8

nr_3:                                   ; ...
                leave
                retn


; =============== S U B R O U T I N E =======================================

; ---------------------------------------------------------------------------
; Function: nasm_write
;
; Description: write output file
;
; C Declaration: void nasm_write(const void *ptr, size_t size, FILE *f)
;
; Input (Stack): [EBP+8]  = *ptr (buffer)
;                [EBP+12] = size (write count)
;                [EBP+16] = *f (file descriptor, c type)
;
; Output: none
;
; Modified Registers: EAX, ECX, (EDX)
; ---------------------------------------------------------------------------

%assign n      -4
%assign ptr     8
%assign size    0Ch
%assign f       10h

nasm_write:
                push    ebp
                mov     ebp, esp
                sub     esp, 4
                nop
                mov     eax, [ebp+f]
                push    eax
                mov     eax, [ebp+size]
                push    eax
                mov     eax, 1
                push    eax
                mov     eax, [ebp+ptr]
                push    eax
                call    fwrite
                add     esp, 16
                mov     [ebp+n], eax    ; size_t n = fwrite(ptr, 1, size, f);
                mov     eax, [ebp+n]    ; if (n != size || ferror(f) || feof(f))
                mov     ecx, [ebp+size]
                cmp     eax, ecx
                jnz     nw_1
                mov     eax, [ebp+f]
                push    eax
                call    ferror
                add     esp, 4
                test    eax, eax
                jnz     nw_1
                mov     eax, [ebp+f]
                push    eax
                call    feof
                add     esp, 4
                test    eax, eax
                jnz     nw_1
                jmp     nw_2
; ---------------------------------------------------------------------------

nw_1:                                   ; ...
                call    _errno
                mov     ecx, [eax]
                push    ecx
                call    strerror
                add     esp, 4
                push    eax
                mov     eax, L_2	; "unable to write output: %s"
                push    eax
                mov     eax, 0
                push    eax
                call    nasm_fatal      ; nasm_fatal(0, "unable to write output: %s", strerror(errno));
                add     esp, 12

nw_2:                                   ; ...
                leave
                retn


; =============== S U B R O U T I N E =======================================

; ---------------------------------------------------------------------------
; Function: fwriteint16_t
;
; Description:
;
; C Declaration: void fwriteint16_t(uint16_t data, FILE * fp)
;
; Input (Stack): [EBP+8]  = data
;                [EBP+12] = *fp
;
; Output: none
;
; Modified Registers: EAX, (ECX), (EDX)
; ---------------------------------------------------------------------------

%assign data    8
%assign fp      0Ch

fwriteint16_t:
                push    ebp
                mov     ebp, esp
                sub     esp, 0
                nop
                ;movzx  eax, word [ebp+data]
                ;mov    [ebp+data], ax  ; data = cpu_to_le16(data);
                mov     eax, [ebp+fp]
                push    eax
                mov     eax, 2
                push    eax
                lea     eax, [ebp+data]
                push    eax
                call    nasm_write      ; nasm_write(&data, 2, fp);
                add     esp, 12
                leave
                retn


; =============== S U B R O U T I N E =======================================

; ---------------------------------------------------------------------------
; Function: fwriteint32_t
;
; Description:
;
; C Declaration: void fwriteint32_t(uint32_t data, FILE * fp)
;
; Input (Stack): [EBP+8]  = data
;                [EBP+12] = *fp
;
; Output: none
;
; Modified Registers: EAX, (ECX), (EDX)
; ---------------------------------------------------------------------------

%assign data    8
%assign fp      0Ch

fwriteint32_t:
                push    ebp
                mov     ebp, esp
                sub     esp, 0
                nop
                ;mov    eax, [ebp+data]
                ;mov    [ebp+data], eax ; data = cpu_to_le32(data);
                mov     eax, [ebp+fp]
                push    eax
                mov     eax, 4
                push    eax
                lea     eax, [ebp+data]
                push    eax
                call    nasm_write      ; nasm_write(&data, 4, fp);
                add     esp, 12
                leave
                retn


; =============== S U B R O U T I N E =======================================

; ---------------------------------------------------------------------------
; Function: fwriteint64_t
;
; Description:
;
; C Declaration: void fwriteint64_t(uint64_t data, FILE * fp)
;
; Input (Stack): [EBP+8]  = data
;                [EBP+12] = data_h
;                [EBP+16] = *fp
;
; Output: none
;
; Modified Registers: EAX, (ECX), (EDX)
; ---------------------------------------------------------------------------

%assign data    8
%assign data_h  0Ch
%assign fp      10h

fwriteint64_t:
                push    ebp
                mov     ebp, esp
                sub     esp, 0
                nop
                ;mov    eax, [ebp+data]
                ;mov    ecx, [ebp+data_h]
                ;mov    [ebp+data], eax ; data = cpu_to_le64(data);
                ;mov    [ebp+data_h], ecx
                mov     eax, [ebp+fp]
                push    eax
                mov     eax, 8
                push    eax
                lea     eax, [ebp+data]
                push    eax
                call    nasm_write      ; nasm_write(&data, 8, fp);
                add     esp, 12
                leave
                retn


; =============== S U B R O U T I N E =======================================

; ---------------------------------------------------------------------------
; Function: fwriteaddr
;
; Description:
;
; C Declaration: void fwriteaddr(uint64_t data, int size, FILE * fp)
;
; Input (Stack): [EBP+8]  = data
;                [EBP+12] = data_h
;                [EBP+16] = size
;                [EBP+20] = *fp
;
; Output: none
;
; Modified Registers: EAX, (ECX), (EDX)
; ---------------------------------------------------------------------------

%assign data    8
%assign data_h  0Ch
%assign size    10h
%assign fp      14h

fwriteaddr:
                push    ebp
                mov     ebp, esp
                sub     esp, 0
                nop
                ;mov    eax, [ebp+data]
                ;mov    ecx, [ebp+data_h]
                ;mov    [ebp+data], eax ; data = cpu_to_le64(data);
                ;mov    [ebp+data_h], ecx
                mov     eax, [ebp+fp]
                push    eax
                mov     eax [ebp+size]
                push    eax
                lea     eax, [ebp+data]
                push    eax
                call    nasm_write      ; nasm_write(&data, size, fp);
                add     esp, 12
                leave
                retn


; =============== S U B R O U T I N E =======================================

; ---------------------------------------------------------------------------
; Function: fwritezero
;
; Description:
;
; C Declaration: void fwritezero(off_t bytes, FILE *fp)
;
; Input (Stack): [EBP+8]  = bytes
;                [EBP+12] = *fp
;
; Output: none
;
; Modified Registers: EAX, ECX, (EDX)
; ---------------------------------------------------------------------------

%assign blksize -4
%assign bytes    8
%assign fp       0Ch

fwritezero:
                push    ebp
                mov     ebp, esp
                sub     esp, 4
                nop

fwz_1:                                  ; ...
                mov     eax, [ebp+bytes] ; while (bytes > 0) {
                cmp     eax, 0
                jle     fwz_5
                mov     eax, [ebp+bytes]
                cmp     eax, 65536      ; blksize = (bytes < ZERO_BUF_SIZE) ? bytes : ZERO_BUF_SIZE;
                mov     eax, 0
                setl    al
                test    eax, eax
                jz      fwz_2
                jmp     fwz_3
; ---------------------------------------------------------------------------

fwz_2:                                  ; ...
                mov     eax, 65536
                jmp     fwz_4
; ---------------------------------------------------------------------------

fwz_3:                                  ; ...
                mov     eax, [ebp+bytes]

fwz_4:                                  ; ...
                mov     [ebp+blksize], eax
                mov     eax, [ebp+fp]
                push    eax
                mov     eax, [ebp+blksize]
                push    eax
                mov     eax, zero_buffer
                push    eax
                call    nasm_write      ; nasm_write(zero_buffer, blksize, fp);
                add     esp, 12
                mov     eax, [ebp+bytes]
                mov     ecx, [ebp+blksize]
                sub     eax, ecx
                mov     [ebp+bytes], eax ; bytes -= blksize;
                jmp     short fwz_1
; ---------------------------------------------------------------------------

fwz_5:                                  ; ...
                leave
                retn


; =============== S U B R O U T I N E =======================================

; ---------------------------------------------------------------------------
; Function: nasm_open_read
;
; Description: Open (input) file for reading
;
; C Declaration:
;          FILE *nasm_open_read(const char *filename, enum file_flags flags)
;
; Input (Stack): [EBP+8]  = filename
;                [EBP+12] = flags
;
; Output (EAX): file descriptor (iob, c type)
;
; Modified Registers: EAX, ECX, (EDX)
; ---------------------------------------------------------------------------

%assign again   -8
%assign f       -4
%assign filename 8
%assign flags    0Ch

nasm_open_read:
                push    ebp
                mov     ebp, esp
                sub     esp, 8
                nop
                mov     eax, 0
                mov     [ebp+f], eax    ; FILE *f = NULL;
                mov     eax, 1
                mov     [ebp+again], eax
                mov     eax, [ebp+again] ; if (again)
                test    eax, eax
                jz      nor_4
                mov     eax, [ebp+flags]
                and     eax, 1
                test    eax, eax
                jz      nor_1
                jmp     nor_2
; ---------------------------------------------------------------------------

nor_1:                                  ; ...
                mov     eax, L_4	; "rb"
                jmp     nor_3
; ---------------------------------------------------------------------------

nor_2:                                  ; ...
                mov     eax, L_3	; "rt"

nor_3:                                  ; ...
                push    eax
                mov     eax, [ebp+filename]
                push    eax
                call    fopen           ; f = fopen(filename, (flags & NF_TEXT) ? "rt" : "rb");
                add     esp, 8
                mov     [ebp+f], eax

nor_4:                                  ; ...
                mov     eax, [ebp+f]    ; if (!f && (flags & NF_FATAL))
                test    eax, eax
                jz      nor_5
                jmp     nor_6
; ---------------------------------------------------------------------------

nor_5:                                  ; ...
                mov     eax, [ebp+flags] ; nasm_fatal(ERR_NOFILE, "unable to open input file: `%s': %s",
                                        ; filename, strerror(errno));
                and     eax, 2
                test    eax, eax
                jz      nor_6
                call    _errno
                mov     ecx, [eax]
                push    ecx
                call    strerror
                add     esp, 4
                push    eax
                mov     eax, [ebp+filename]
                push    eax
                mov     eax, L_5	; "unable to open input file: `%s': %s"
                push    eax
                mov     eax, 10h        ; ERR_NOFILE
                push    eax
                call    nasm_fatal
                add     esp, 16

nor_6:                                  ; ...
                mov     eax, [ebp+f]
                ;jmp    $+5
; ---------------------------------------------------------------------------

nor_7:                                  ; ...
                leave
                retn


; =============== S U B R O U T I N E =======================================

; ---------------------------------------------------------------------------
; Function: nasm_open_write
;
; Description: Open (output) file for writing
;
; C Declaration:
;          FILE *nasm_open_write(const char *filename, enum file_flags flags)
;
; Input (Stack): [EBP+8]  = filename
;                [EBP+12] = flags
;
; Output (EAX): file descriptor (iob, c type)
;
; Modified Registers: EAX, ECX, (EDX)
; ---------------------------------------------------------------------------

%assign f       -4
%assign filename 8
%assign flags    0Ch

nasm_open_write:
                push    ebp
                mov     ebp, esp
                sub     esp, 4
                nop
                mov     eax, [ebp+flags] ; f = fopen(filename, (flags & NF_TEXT) ? "wt" : "wb");
                and     eax, 1
                test    eax, eax
                jz      now_1
                jmp     now_2
; ---------------------------------------------------------------------------

now_1:                                  ; ...
                mov     eax, L_7	; "wb"
                jmp     now_3
; ---------------------------------------------------------------------------

now_2:                                  ; ...
                mov     eax, L_6	; "wt"

now_3:                                  ; ...
                push    eax
                mov     eax, [ebp+filename]
                push    eax
                call    fopen
                add     esp, 8
                mov     [ebp+f], eax
                mov     eax, [ebp+f]    ; if (!f && (flags & NF_FATAL))
                test    eax, eax
                jz      now_4
                jmp     now_5
; ---------------------------------------------------------------------------

now_4:                                  ; ...
                mov     eax, [ebp+flags]
                and     eax, 2
                test    eax, eax
                jz      now_5
                call    _errno
                mov     ecx, [eax]
                push    ecx
                call    strerror
                add     esp, 4
                push    eax
                mov     eax, [ebp+filename]
                push    eax
                mov     eax, L_8	; "unable to open output file: `%s': %s"
                push    eax
                mov     eax, 10h        ; ERR_NOFILE
                push    eax
                call    nasm_fatal      ; nasm_fatal(ERR_NOFILE, "unable to open output file: `%s': %s",
                                        ; filename, strerror(errno));
                add     esp, 16

now_5:                                  ; ...
                mov     eax, [ebp+f]
                ;jmp    $+5
; ---------------------------------------------------------------------------

now_6:                                  ; ...
                leave
                retn


; =============== S U B R O U T I N E =======================================

; ---------------------------------------------------------------------------
; Function: nasm_file_exists
;
; Description: Report the existence of a file
;
; C Declaration: bool nasm_file_exists(const char *filename)
;
; Input (Stack): [EBP+8] = filename
;
; Output (EAX): status (true/false)
;
; Modified Registers: EAX, (ECX), (EDX)
; ---------------------------------------------------------------------------

%assign f       -4
%assign filename 8

nasm_file_exists:
                push    ebp
                mov     ebp, esp
                sub     esp, 4
                nop                     ; FILE *f;
                mov     eax, L_9	; "rb"
                push    eax
                mov     eax, [ebp+filename]
                push    eax
                call    fopen
                add     esp, 8
                mov     [ebp+f], eax    ; f = fopen(filename, "rb");
                ;mov    eax, [ebp+f]    ; if (f) {
                test    eax, eax
                jz      nfe_1
                mov     eax, [ebp+f]
                push    eax
                call    fclose          ; fclose(f);
                add     esp, 4
                mov     eax, 1          ; return true;
                jmp     nfe_2
; ---------------------------------------------------------------------------
                ;jmp    nfe_2
; ---------------------------------------------------------------------------

nfe_1:                                  ; ...
                mov     eax, 0          ; return false;
                ;jmp    $+5
; ---------------------------------------------------------------------------

nfe_2:                                  ; ...
                leave
                retn


; =============== S U B R O U T I N E =======================================

; ---------------------------------------------------------------------------
; Function: nasm_file_size
;
; Description: Report file size
;
; C Declaration: off_t nasm_file_size(FILE *f)
;
; Input (Stack): [EBP+8] = *f (file descriptor, iob, c type)
;
; Output (EAX): file size
;
; Modified Registers: EAX, (ECX), (EDX)
; ---------------------------------------------------------------------------

	; TRDOS 386 Kernel v2.1 (& 2.0.11) SysFSTAT system call parameters
	; Input:
	;	EBX = File Descriptor (Handle)
	;	ECX = Pointer to stat structure (User Buffer)
	; Output:
	;	If cf = 0 -> EAX = 0
	;	If cf = 1 -> EAX = error code (= -1)
	;
	; 22/05/2026
        ;
	; ref: tcc (include/sys) stat.h ((modified))
	; stat structure:
	; 	st_dev:   resd 1 ; 0
	;	st_ino:	  resd 1 ; 4
	;	st_mode:  resw 1 ; 8
	;	st_nlink: resw 1 ; 10
	;	st_uid:   resw 1 ; 12
	;	st_gid:   resw 1 ; 14
	;	st_rdev:  resd 1 ; 16
	;	st_size:  resd 1 ; 20
	;		  resd 1 ; 24
	;	st_atime: resd 1 ; 28
	;	st_mtime: resd 1 ; 32
	;	st_ctime: resd 1 ; 36

%assign st     -40
%assign st.st_size -20
%assign f       8

nasm_file_size:
                push    ebp
                mov     ebp, esp
                sub     esp, 40
                                        ; off_t nasm_file_size(FILE *f)
                lea     eax, [ebp+st]   ; nasm_struct_stat st;
                push	eax             ; &st
                mov     eax, [ebp+f]    ; fileno(f)
                mov     eax, [eax+16]   ; (iob fileno field)
                push	eax
                call    nasm_fstat      ; if (nasm_fstat(fileno(f), &st))
                ;add	esp, 8
                test    eax, eax
                jnz     short nfs_2
                ;mov    eax, [ebp+st+20]
                                        ; return st.st_size;
                mov     eax, [ebp+st.st_size]
nfs_1:                                  ; ...
                ;mov    esp, ebp
		;pop    ebp
                leave
                retn
; ---------------------------------------------------------------------------
nfs_2:                                  ; ...
                mov     eax, -1         ; return (off_t)-1;
                jmp     short nfs_1


; =============== S U B R O U T I N E =======================================

%if 0

; ---------------------------------------------------------------------------
; Function: nasm_file_size
;
; Description: Report file size. This MAY move the file pointer.
;
; C Declaration: off_t nasm_file_size(FILE *f)
;
; Input (Stack): [EBP+8] = *f (file descriptor, iob, c type)
;
; Output (EAX): file size
;
; Modified Registers: EAX, (ECX), (EDX)
; ---------------------------------------------------------------------------

%assign f       8

nasm_file_size:
                push    ebp 
                mov     ebp, esp
                sub     esp, 0          ; #elif defined(nasm_fstat)
                nop
                mov     eax, 2          ; #else
                push    eax
                mov     eax, 0
                push    eax
                mov     eax, [ebp+f]
                push    eax
                call    fseek           ; if (fseeko(f, 0, SEEK_END))
                add     esp, 12
                test    eax, eax
                jz      nfs_1
                mov     eax, -1         ; return (off_t)-1;
                jmp     nfs_2
; ---------------------------------------------------------------------------

nfs_1:                                  ; ...
                mov     eax, [ebp+f]
                push    eax
                call    ftell           ; return ftello(f);
                add     esp, 4
                ;jmp    $+5
; ---------------------------------------------------------------------------

nfs_2:                                  ; ...
                leave
                retn
%endif


; =============== S U B R O U T I N E =======================================

; ---------------------------------------------------------------------------
; Function: nasm_file_size_by_path
;
; Description: Report file size given pathname
;
; C Declaration: off_t nasm_file_size_by_path(const char *pathname)
;
; Input (Stack): [EBP+8] = *pathname
;
; Output (EAX): file size
;
; Modified Registers: EAX, (ECX), (EDX)
; ---------------------------------------------------------------------------

%assign len     -8
%assign fp      -4
%assign pathname 8

nasm_file_size_by_path:
                push    ebp
                mov     ebp, esp        ; #ifdef nasm_stat
                sub     esp, 8          ; #else
                nop                     ; FILE *fp;
                mov     eax, 0          ; off_t len;
                push    eax             ; (NF_BINARY = 0)
                mov     eax, [ebp+pathname]
                push    eax
                call    nasm_open_read  ; fp = nasm_open_read(pathname, NF_BINARY);
                add     esp, 8
                mov     [ebp+fp], eax
                mov     eax, [ebp+fp]   ; if (!fp)
                test    eax, eax
                ;jz     nfsp_1
                ;jmp    nfsp_2
                jnz	nfsp_2
; ---------------------------------------------------------------------------

nfsp_1:                                 ; ...
                mov     eax, -1         ; return (off_t)-1;
                jmp     nfsp_3
; ---------------------------------------------------------------------------

nfsp_2:                                 ; ...
                mov     eax, [ebp+fp]
                push    eax
                call    nasm_file_size
                add     esp, 4
                mov     [ebp+len], eax  ; len = nasm_file_size(fp);
                mov     eax, [ebp+fp]
                push    eax
                call    fclose          ; fclose(fp);
                add     esp, 4
                mov     eax, [ebp+len]  ; return len;
                ;jmp    $+5
; ---------------------------------------------------------------------------

nfsp_3:                                 ; ...
                leave
                retn

; =============== S U B R O U T I N E =======================================

; ---------------------------------------------------------------------------
; Function: nasm_file_time
;
; Description: Report the timestamp on a file, returns true if successful
;
; C Declaration: bool nasm_file_time(time_t *t, const char *pathname)
;
; Input (Stack): [EBP+8]  = *t (time field)
;                [EBP+12] = patname
;
; Output (EAX): true/false
;
; Modified Registers: EAX, (ECX), (EDX)
; ---------------------------------------------------------------------------

%assign st      -44
%assign st.st_mtime -12
%assign fp      -4
%assign t        8
%assign pathname 0Ch

nasm_file_time:
                push    ebp
                mov     ebp, esp
                sub     esp, 44
                mov     eax, 0          ; (NF_BINARY = 0)
                push    eax 
                mov     eax, [ebp+pathname]
                push    eax
                call    nasm_open_read  ; fp = nasm_open_read(pathname, NF_BINARY);
                add     esp, 8
                mov     [ebp+fp], eax   ; FILE *fp;
                mov     eax, [ebp+fp]   ; if (!fp)
                test    eax, eax
                jz      nft_4           ; return false (eax = 0)
; ---------------------------------------------------------------------------
nft_1:
                lea     eax, [ebp+st]   ; nasm_struct_stat st;
                push	eax             ; &st
                mov     eax, [ebp+fp]   ; fileno(fp)
                mov     eax, [eax+16]   ; (iob fileno field)
                push	eax
                call    nasm_fstat      ; if (nasm_fstat(fileno(f), &st))
                add     esp, 8
                test    eax, eax
                jz      short nft_2
                mov     eax, 0          ; return false		
                jmp     nft_3
nft_2:
                ;mov    eax, [ebp+st+32]
                mov     eax, [ebp+st.st_mtime]
                mov	[ebp+t], eax	; *t = st.st_mtime;
                mov     eax, 1          ; return true;
nft_3:
                push	eax
                mov     eax, [ebp+fp]
                push    eax
                call    fclose          ; fclose(fp);
                ;add    esp, 4
                pop     eax
                pop     eax             ; true or false 
; ---------------------------------------------------------------------------

nft_4:
                leave
                retn
