; ===========================================================================
; NASM v2.14.02 - NETWIDE ASSEMBLER FOR TRDOS 386 - Erdogan Tan - 18/09/2026 
; Disassembled from "filename.c" (Dissassembler: IDA)
; NASM Syntax: Erdogan Tan
; Last Update: 25/09/2026
; ===========================================================================
; filename.asm
; ------------
; This file will be included in the "nasm386.asm" file
; Inclusion order: 11

; target: NASM.PRG (flat binary)
; main assembly file: nasm386.asm
; library section: libnasm.asm
; TRDOS 386 functions: system.asm 
; data section: data.asm
; bss section: bss.asm
; launcher: crt0.asm

;
; +-------------------------------------------------------------------------+
; |   This file has been generated by The Interactive Disassembler (IDA)    |
; |           Copyright (c) 2018 Hex-Rays, <support@hex-rays.com>           |
; |                            Freeware version                             |
; +-------------------------------------------------------------------------+
;

; File Name   : C:\Users\90542\OneDrive\Masaüstü\nasm_214_c_o\filename.o
; Format      : ELF for Intel 386 (Relocatable)
;
; Source File : 'filename.c'

; ===========================================================================
; CODE
; ===========================================================================

; section .text

; =============== S U B R O U T I N E =======================================

; ---------------------------------------------------------------------------
; Function: filename_set_extension
;
; Description:
; Add/modify a filename extension, assumed to be a period-delimited field
; at the very end of the filename. Returns a newly allocated string buffer.
;
; C Declaration:
; const char *filename_set_extension(const char *inname, const char *extension)
;
; Input (Stack): [EBP+8]  = *inname
;                [EBP+12] = *extension
;
; Output (EAX): string buffer (asciiz filename.ext) address
;
; Modified Registers: EAX, ECX, (EDX)
; ---------------------------------------------------------------------------

%assign baselen  -10h
%assign elen     -0Ch
%assign p        -8
%assign q        -4
%assign inname    8
%assign extension 0Ch

filename_set_extension:
                push    ebp
                mov     ebp, esp
                sub     esp, 16
                nop
                mov     eax, [ebp+inname]
                mov     [ebp+q], eax    ; const char *q = inname;
                mov     eax, [ebp+extension] ; char *p;
                push    eax
                call    strlen
                add     esp, 4
                mov     [ebp+elen], eax ; size_t elen = strlen(extension);
                mov     eax, '.'
                push    eax
                mov     eax, [ebp+inname]
                push    eax
                call    strrchrnul      ; q = strrchrnul(inname, '.');
                add     esp, 8
                mov     [ebp+q], eax
                mov     eax, [ebp+q]    ; size_t baselen;
                mov     ecx, [ebp+inname]
                sub     eax, ecx
                mov     [ebp+baselen], eax ; baselen = q - inname;
                mov     eax, [ebp+baselen]
                mov     ecx, [ebp+elen]
                add     eax, ecx
                inc     eax
                push    eax
                call    nasm_malloc
                add     esp, 4
                mov     [ebp+p], eax    ; p = nasm_malloc(baselen + elen + 1);
                mov     eax, [ebp+baselen]
                push    eax
                mov     eax, [ebp+inname]
                push    eax
                mov     eax, [ebp+p]
                push    eax
                call    memcpy          ; memcpy(p, inname, baselen);
                add     esp, 12
                mov     eax, [ebp+baselen]
                mov     ecx, [ebp+p]
                add     ecx, eax
                mov     eax, [ebp+elen]
                inc     eax
                push    eax
                mov     eax, [ebp+extension]
                push    eax
                push    ecx
                call    memcpy          ; memcpy(p+baselen, extension, elen+1);
                add     esp, 12
                mov     eax, [ebp+p]    ; return p;
                leave
                retn
