; ===========================================================================
; NASM v2.14.02 - NETWIDE ASSEMBLER FOR TRDOS 386 - Erdogan Tan - 18/09/2026 
; Disassembled from "hashtbl.c" (Dissassembler: IDA)
; NASM Syntax: Erdogan Tan
; Last Update: 26/09/2026
; ===========================================================================
; hashtbl.asm
; -----------
; This file will be included in the "nasm386.asm" file
; Inclusion order: 16

; target: NASM.PRG (flat binary)
; main assembly file: nasm386.asm
; library section: libnasm.asm
; TRDOS 386 functions: system.asm 
; data section: data.asm
; bss section: bss.asm
; launcher: crt0.asm

;
; +-------------------------------------------------------------------------+
; |   This file has been generated by The Interactive Disassembler (IDA)    |
; |           Copyright (c) 2018 Hex-Rays, <support@hex-rays.com>           |
; |                            Freeware version                             |
; +-------------------------------------------------------------------------+
;

; File Name   : C:\Users\90542\OneDrive\Masaüstü\nasm_214_c_o\hashtbl.o
; Format      : ELF for Intel 386 (Relocatable)
;
; Source File : 'hashtbl.c'

; ===========================================================================
; CODE
; ===========================================================================

; section .text

; struct hash_tbl_node {
;    uint64_t hash;
;    const char *key;
;    void *data;
; };

; struct hash_table {
;    struct hash_tbl_node *table;
;    size_t load;
;    size_t size;
;    size_t max_load;
; };

; struct hash_insert {
;   uint64_t hash;
;   struct hash_table *head;
;   struct hash_tbl_node *where;
; };

; #define CRC64_INIT UINT64_C(0xffffffffffffffff)
; #define HASH_MEDIUM 16

; #define HASH_MAX_LOAD 2 /* Higher = more memory-efficient, slower */

; #define hash_calc(key)       crc64(CRC64_INIT, (key))
; #define hash_calci(key)      crc64i(CRC64_INIT, (key))
; #define hash_max_load(size)  ((size) * (HASH_MAX_LOAD - 1) / HASH_MAX_LOAD)
; #define hash_expand(size)    ((size) << 1)
; #define hash_mask(size)      ((size) - 1)
; #define hash_pos(hash, mask) ((hash) & (mask))
; #define hash_inc(hash, mask) ((((hash) >> 32) & (mask)) | 1) /* always odd */
; #define hash_pos_next(pos, inc, mask) (((pos) + (inc)) & (mask))


; =============== S U B R O U T I N E =======================================

; ---------------------------------------------------------------------------
; Function: alloc_table
;
; Description:
;
; C Declaration: static struct hash_tbl_node *alloc_table(size_t newsize)

; Input (Stack): [EBP+8] = newsize
;
; Output (EAX): hash_tbl_node address
;
; Modified Registers: EAX, (ECX), (EDX)
; ---------------------------------------------------------------------------

%assign bytes  -4
%assign newsize 8

alloc_table:
                push    ebp
                mov     ebp, esp
                sub     esp, 4
                nop
                mov     eax, [ebp+newsize]
                shl     eax, 4
                mov     [ebp+bytes], eax ; size_t bytes = newsize * sizeof(struct hash_tbl_node);
                mov     eax, [ebp+bytes]
                push    eax
                call    nasm_zalloc     ; return nasm_zalloc(bytes);
                add     esp, 4
                leave


; =============== S U B R O U T I N E =======================================

; ---------------------------------------------------------------------------
; Function: hash_init
;
; Description:
;
; C Declaration: void hash_init(struct hash_table *head, size_t size)
;
; Input (Stack): [EBP+8]  = size
;                [EBP+12] = *head
;
; Output: none
;
; Modified Registers: EAX, ECX, (EDX)
; ---------------------------------------------------------------------------

; #define is_power2(v) ((v) && ((v) & ((v) - 1)) == 0)

%assign tmp    -4
%assign head    8
%assign size    0Ch

hash_init:
                push    ebp
                mov     ebp, esp
                sub     esp, 4
                nop
                mov     eax, [ebp+size]
                cmp     eax, 0
                jz      hi_1
                ;mov    eax, [ebp+size]
                dec     eax
                mov     ecx, [ebp+size]
                and     ecx, eax
                cmp     ecx, 0
                jnz     hi_1
                jmp     hi_2
; ---------------------------------------------------------------------------

hi_1:                                   ; ...
                jmp     hi_3
; ---------------------------------------------------------------------------

hi_2:                                   ; ...
                jmp     hi_4
; ---------------------------------------------------------------------------

hi_3:                                   ; ...
                mov     eax, L_196	; "is_power2(size)"
                push    eax
                mov     eax, 65         ; (hashtbl.c line 65)
                push    eax
                mov     eax, L_195	; "hashtbl.c"
                push    eax
                call    nasm_assert_failed ; nasm_assert(is_power2(size));
                add     esp, 12

hi_4:                                   ; ...
                mov     eax, [ebp+head]
                mov     ecx, [ebp+size]
                push    ecx
                mov     [ebp+tmp], eax
                call    alloc_table
                add     esp, 4
                mov     ecx, [ebp+tmp]
                mov     [ecx], eax      ; head->table = alloc_table(size);
                mov     eax, [ebp+head]
                add     eax, 4
                mov     ecx, 0
                mov     [eax], ecx      ; head->load = 0;
                mov     eax, [ebp+head]
                add     eax, 8
                mov     ecx, [ebp+size]
                mov     [eax], ecx      ; head->size = size;
                mov     eax, [ebp+head]
                add     eax, 12
                mov     ecx, [ebp+size]
                shr     ecx, 1          ; #define HASH_MAX_LOAD 2
                                        ;    /* Higher = more memory-efficient, slower */
                                        ; #define hash_max_load(size)
                                        ;    ((size) * (HASH_MAX_LOAD - 1) / HASH_MAX_LOAD)
                mov     [eax], ecx      ; head->max_load = hash_max_load(size);
                leave
                retn


; =============== S U B R O U T I N E =======================================

; ---------------------------------------------------------------------------
; Function: hash_find
;
; Description: Find an entry in a hash table.
;
;   On failure, if "insert" is non-NULL, store data in that structure
;   which can be used to insert that node using hash_add().
;    
;   WARNING: this data is only valid until the very next call of
;            hash_add(); it cannot be "saved" to a later date.
;
;   On success, return a pointer to the "data" element of the hash structure.
;
; C Declaration: void **hash_find(struct hash_table *head, const char *key,
;                                 struct hash_insert *insert)
;
; Input (Stack): [EBP+8]  = *head
;                [EBP+12] = *key
;                [EBP+16] = *insert
;
; Output: none
;
; Modified Registers: EAX, ECX, EDX
; ---------------------------------------------------------------------------

%assign tmp_h  -28h
%assign tmp    -24h
%assign incr   -1Ch
%assign pos    -18h
%assign mask   -14h
%assign hash   -10h
%assign hash_h -0Ch
%assign tbl    -8
%assign np     -4
%assign head    8
%assign key     0Ch
%assign insert  10h

hash_find:
                push    ebp
                mov     ebp, esp
                sub     esp, 40         ; struct hash_tbl_node *np;
                nop
                mov     eax, [ebp+head]
                mov     ecx, [eax]
                mov     [ebp+tbl], ecx  ; struct hash_tbl_node *tbl = head->table;
                mov     eax, [ebp+key]  ; #define hash_calc(key) crc64(CRC64_INIT, (key))
                push    eax
                mov     eax, 0FFFFFFFFh ; CRC64_INIT
                mov     ecx, 0FFFFFFFFh
                push    ecx
                push    eax
                call    crc64
                add     esp, 12
                mov     [ebp+hash], eax ; uint64_t hash = hash_calc(key);
                mov     [ebp+hash_h], edx
                mov     eax, [ebp+head]
                add     eax, 8          ; head->size
                mov     ecx, [eax]      ; #define hash_mask(size) ((size) - 1)
                dec     ecx
                mov     [ebp+mask], ecx ; size_t mask = hash_mask(head->size);
                mov     eax, [ebp+mask]
                ;mov    ecx, 0
                mov     edx, [ebp+hash] ; #define hash_pos(hash, mask) ((hash) & (mask))
                and     edx, eax
                ;mov    eax, [ebp+hash_h]
                ;and    eax, ecx
                mov     [ebp+pos], edx  ; size_t pos = hash_pos(hash, mask);
                mov     eax, [ebp+hash_h]
                ;mov    ecx, 0
                mov     edx, [ebp+mask]
                mov     [ebp+tmp_h], eax
                ;mov    [ebp+tmp], ecx
                ;mov    ecx, 0
                mov     eax, [ebp+tmp_h] ; #define hash_inc(hash, mask)
                                        ;    ((((hash) >> 32) & (mask)) | 1) /* always odd */
                and     eax, edx        ; ((hash) >> 32) & mask
                ;mov    edx, [ebp+tmp]
                ;and    edx, ecx
                or      eax, 1          ; | 1
                mov     [ebp+incr], eax ; size_t inc = hash_inc(hash, mask);

hf_1:                                   ; ...
                mov     eax, [ebp+pos]  ; while ((np = &tbl[pos])->key) {
                shl     eax, 4
                mov     ecx, [ebp+tbl]
                add     ecx, eax
                mov     [ebp+np], ecx
                add     ecx, 8
                mov     eax, [ecx]
                cmp     eax, 0
                jz      hf_4
                mov     eax, [ebp+np]   ; if (hash == np->hash && !strcmp(key, np->key))
                mov     ecx, [eax]
                add     eax, 4
                mov     edx, [eax]
                mov     eax, [ebp+hash_h]
                cmp     eax, edx
                jnz     hf_3
                mov     eax, [ebp+hash]
                cmp     eax, ecx
                jnz     hf_3
                mov     eax, [ebp+np]
                add     eax, 8
                mov     ecx, [eax]
                push    ecx
                mov     eax, [ebp+key]
                push    eax
                call    strcmp
                add     esp, 8
                cmp     eax, 0
                jz      hf_2            ; !strcmp(key, np->key)
                jmp     hf_3
; ---------------------------------------------------------------------------

hf_2:                                   ; ...
                mov     eax, [ebp+np]   ; return &np->data;
                add     eax, 12
                jmp     hf_6
; ---------------------------------------------------------------------------

hf_3:                                   ; ...
                mov     eax, [ebp+pos]  ; #define hash_pos_next(pos, inc, mask) (((pos) + (inc)) & (mask))
                mov     ecx, [ebp+incr]
                add     eax, ecx
                mov     ecx, [ebp+mask]
                and     eax, ecx
                mov     [ebp+pos], eax  ; pos = hash_pos_next(pos, inc, mask);
                jmp     short hf_1
; ---------------------------------------------------------------------------

hf_4:                                   ; ...
                mov     eax, [ebp+insert]
                                        ; /* Not found. Store info for insert if requested. */
                cmp     eax, 0          ; if (insert) {
                jz      hf_5
                mov     eax, [ebp+insert] ; struct hash_insert {
                                        ;     uint64_t hash;
                                        ;     struct hash_table *head;
                                        ;     struct hash_tbl_node *where;
                                        ; };
                add     eax, 8
                mov     ecx, [ebp+head]
                mov     [eax], ecx      ; insert->head = head;
                mov     eax, [ebp+insert]
                mov     ecx, [ebp+hash]
                mov     edx, [ebp+hash_h]
                mov     [eax], ecx      ; insert->hash = hash;
                add     eax, 4
                mov     [eax], edx      ; insert->where = np;
                mov     eax, [ebp+insert]
                add     eax, 12
                mov     ecx, [ebp+np]
                mov     [eax], ecx

hf_5:                                   ; ...
                mov     eax, 0          ; return NULL;

hf_6:                                   ; ...
                leave
                retn


; =============== S U B R O U T I N E =======================================

; ---------------------------------------------------------------------------
; Function: hash_findi
;
; Description: Find an entry in a hash table.
;              Same as hash_find, but for case-insensitive hashing.
;
; C Declaration: void **hash_findi(struct hash_table *head, const char *key,
;                                  struct hash_insert *insert)
;
; Input (Stack): [EBP+8]  = *head
;                [EBP+12] = *key
;                [EBP+16] = *insert
;
; Output: none
;
; Modified Registers: EAX, ECX, EDX
; ---------------------------------------------------------------------------

%assign tmp_h  -28h
%assign tmp    -24h
%assign incr   -1Ch
%assign pos    -18h
%assign mask   -14h
%assign hash   -10h
%assign hash_h -0Ch
%assign tbl    -8
%assign np     -4
%assign head    8
%assign key     0Ch
%assign insert  10h

hash_findi:
                push    ebp
                mov     ebp, esp
                sub     esp, 40
                nop
                mov     eax, [ebp+head] ; struct hash_tbl_node *np;
                mov     ecx, [eax]
                mov     [ebp+tbl], ecx  ; struct hash_tbl_node *tbl = head->table;
                mov     eax, [ebp+key]
                push    eax
                mov     eax, 0FFFFFFFFh ; CRC64_INIT
                mov     ecx, 0FFFFFFFFh
                push    ecx
                push    eax
                call    crc64i          ; #define hash_calci(key) crc64i(CRC64_INIT, (key))
                add     esp, 12
                mov     [ebp+hash], eax ; uint64_t hash = hash_calci(key);
                mov     [ebp+hash_h], edx
                mov     eax, [ebp+head]
                add     eax, 8
                mov     ecx, [eax]
                dec     ecx
                mov     [ebp+mask], ecx ; size_t mask = hash_mask(head->size);
                mov     eax, [ebp+mask]
                ;mov    ecx, 0
                mov     edx, [ebp+hash]
                and     edx, eax
                ;mov    eax, [ebp+hash_h]
                ;and    eax, ecx
                mov     [ebp+pos], edx  ; size_t pos = hash_pos(hash, mask);
                mov     eax, [ebp+hash_h]
                ;mov    ecx, 0
                mov     edx, [ebp+mask]
                mov     [ebp+tmp_h], eax
                mov     [ebp+tmp], ecx
                ;mov    ecx, 0
                mov     eax, [ebp+tmp_h]
                and     eax, edx
                ;mov    edx, [ebp+tmp]
                ;and    edx, ecx
                or      eax, 1
                mov     [ebp+incr], eax ; size_t inc = hash_inc(hash, mask);

hfi_1:                                  ; ...
                mov     eax, [ebp+pos]  ; while ((np = &tbl[pos])->key) {
                shl     eax, 4
                mov     ecx, [ebp+tbl]
                add     ecx, eax
                mov     [ebp+np], ecx
                add     ecx, 8
                mov     eax, [ecx]
                cmp     eax, 0
                jz      hfi_4
                mov     eax, [ebp+np]   ; if (hash == np->hash && !nasm_stricmp(key, np->key))
                mov     ecx, [eax]
                add     eax, 4
                mov     edx, [eax]
                mov     eax, [ebp+hash_h]
                cmp     eax, edx
                jnz     hfi_3
                mov     eax, [ebp+hash]
                cmp     eax, ecx
                jnz     hfi_3
                mov     eax, [ebp+np]
                add     eax, 8
                mov     ecx, [eax]
                push    ecx
                mov     eax, [ebp+key]
                push    eax
                call    nasm_stricmp
                add     esp, 8
                cmp     eax, 0
                jz      hfi_2           ; !nasm_stricmp(key, np->key)
                jmp     hfi_3
; ---------------------------------------------------------------------------

hfi_2:                                  ; ...
                mov     eax, [ebp+np]   ; return &np->data;
                add     eax, 12
                jmp     hfi_6
; ---------------------------------------------------------------------------

hfi_3:                                  ; ...
                mov     eax, [ebp+pos]
                mov     ecx, [ebp+incr]
                add     eax, ecx
                mov     ecx, [ebp+mask]
                and     eax, ecx
                mov     [ebp+pos], eax  ; pos = hash_pos_next(pos, inc, mask);
                jmp     short hfi_1
; ---------------------------------------------------------------------------

hfi_4:                                  ; ...
                mov     eax, [ebp+insert] 
                                        ; /* Not found. Store info for insert if requested. */
                cmp     eax, 0          ; if (insert) {
                jz      hfi_5
                mov     eax, [ebp+insert]
                add     eax, 8
                mov     ecx, [ebp+head]
                mov     [eax], ecx      ; insert->head = head;
                mov     eax, [ebp+insert]
                mov     ecx, [ebp+hash]
                mov     edx, [ebp+hash_h]
                mov     [eax], ecx
                add     eax, 4
                mov     [eax], edx      ; insert->hash = hash;
                mov     eax, [ebp+insert]
                add     eax, 12
                mov     ecx, [ebp+np]
                mov     [eax], ecx      ; insert->where = np;

hfi_5:                                  ; ...
                mov     eax, 0          ; return NULL;

hfi_6:                                  ; ...
                leave
                retn


; =============== S U B R O U T I N E =======================================

; ---------------------------------------------------------------------------
; Function: hash_add
;
; Description: Insert node.
;    Return a pointer to the "data" element of the newly created hash node.
;
; C Declaration:
;    void **hash_add(struct hash_insert *insert, const char *key, void *data)
;
; Input (Stack): [EBP+8]  = *insert
;                [EBP+12] = *key
;                [EBP+16] = *data
;
; Output: none
;
; Modified Registers: EAX, ECX, EDX
; ---------------------------------------------------------------------------

%assign tmp4    -44h
%assign tmp3_h  -40h
%assign tmp3    -3Ch
%assign incr    -34h
%assign tmp2    -30h
%assign tmp2_h  -2Ch
%assign pos     -28h
%assign i       -24h
%assign xp      -20h
%assign op      -1Ch
%assign mask    -18h
%assign newtbl  -14h
%assign newsize -10h
%assign tmp1    -0Ch
%assign np      -8
%assign head    -4
%assign insert   8
%assign key      0Ch
%assign data     10h

hash_add:
                push    ebp
                mov     ebp, esp
                sub     esp, 68
                nop
                mov     eax, [ebp+insert]
                add     eax, 8
                mov     ecx, [eax]
                mov     [ebp+head], ecx ; struct hash_table *head = insert->head;
                mov     eax, [ebp+insert]
                add     eax, 12
                mov     ecx, [eax]
                mov     [ebp+np], ecx   ; struct hash_tbl_node *np = insert->where;
                mov     eax, [ebp+np]
                mov     ecx, [ebp+insert]
                                        ; /* Insert node. We can always do this, even if
                                        ;    we need to rebalance immediately after. */
                mov     edx, [ecx]
                add     ecx, 4
                mov     [ebp+tmp1], eax ; *np
                mov     eax, [ecx]
                mov     ecx, [ebp+tmp1]
                mov     [ecx], edx      ; hash
                add     ecx, 4          ; hash_h
                mov     [ecx], eax      ; np->hash = insert->hash;
                mov     eax, [ebp+np]
                add     eax, 8
                mov     ecx, [ebp+key]
                mov     [eax], ecx      ; np->key = key;
                mov     eax, [ebp+np]
                add     eax, 12
                mov     ecx, [ebp+data]
                mov     [eax], ecx      ; np->data = data;
                mov     eax, [ebp+head]
                add     eax, 4
                mov     ecx, [eax]      ; head->load
                inc     ecx
                mov     [eax], ecx      ; ++head->load
                mov     eax, [ebp+head]
                add     eax, 12
                mov     edx, [eax]      ; head->max_load
                cmp     ecx, edx        ; if (++head->load > head->max_load) {
                jbe     ha_9
                mov     eax, [ebp+head] ; /* Need to expand the table */
                add     eax, 8
                mov     ecx, [eax]      ; head->size
                shl     ecx, 1          ; #define hash_expand(size) ((size) << 1)
                mov     [ebp+newsize], ecx ; size_t newsize = hash_expand(head->size);
                mov     eax, [ebp+newsize]
                push    eax
                call    alloc_table
                add     esp, 4
                mov     [ebp+newtbl], eax ; struct hash_tbl_node *newtbl = alloc_table(newsize);
                mov     eax, [ebp+newsize]
                dec     eax             ; #define hash_mask(size) ((size) - 1)
                mov     [ebp+mask], eax ; size_t mask = hash_mask(newsize);
                mov     eax, [ebp+head]
                mov     ecx, [eax]      ; struct hash_tbl_node *op, *xp;
                cmp     ecx, 0          ; if (head->table) {
                jz      ha_8
                mov     eax, 0          ; size_t i;
                mov     [ebp+i], eax    ; i = 0
                mov     eax, [ebp+head]
                mov     ecx, [eax]
                mov     [ebp+op], ecx   ; op = head->table

ha_1:                                   ; ...
                mov     eax, [ebp+head] ; /* Rebalance all the entries */
                                        ; for (i = 0, op = head->table; i < head->size; i++, op++) {
                add     eax, 8
                mov     ecx, [ebp+i]
                mov     edx, [eax]
                cmp     ecx, edx        ; (if) i < head->size;
                jnb     ha_7
                jmp     ha_3
; ---------------------------------------------------------------------------

ha_2:                                   ; ...
                mov     eax, [ebp+i]    ; (next) i++
                mov     ecx, eax
                inc     eax
                mov     [ebp+i], eax
                mov     eax, [ebp+op]   ; (next) op++
                mov     ecx, eax
                add     eax, 16         ; + (hash_tbl_node structure size)
                mov     [ebp+op], eax
                jmp     short ha_1
; ---------------------------------------------------------------------------

ha_3:                                   ; ...
                mov     eax, [ebp+op]   ; if (op->key) {
                add     eax, 8
                mov     ecx, [eax]
                cmp     ecx, 0
                jz      ha_6
                mov     eax, [ebp+op]
                mov     ecx, [ebp+mask]
                mov     edx, 0          ; #define hash_pos(hash, mask) ((hash) & (mask))
                mov     [ebp+tmp2], ecx ; mask
                mov     [ebp+tmp2_h], edx ; mask_h
                mov     edx, [eax]      ; op->hash
                add     eax, 4
                mov     ecx, [eax]      ; op->hash_h
                mov     eax, [ebp+tmp2]
                and     edx, eax
                mov     eax, [ebp+tmp2_h]
                and     ecx, eax
                mov     [ebp+pos], edx  ; size_t pos = hash_pos(op->hash, mask);
                mov     eax, [ebp+op]
                mov     ecx, [eax]      ; op->hash
                add     eax, 4
                mov     edx, [eax]      ; op->hash_h
                ;mov    eax, 0
                mov     ecx, [ebp+mask] ; #define hash_inc(hash, mask) ((((hash) >> 32) & (mask)) | 1)
                ;mov    [ebp+tmp3_h], edx
                ;mov    [ebp+tmp3], eax
                ;mov    eax, 0
                ;mov    edx, [ebp+tmp3_h]
                and     edx, ecx        ; ((hash) >> 32) & mask
                ;mov    ecx, [ebp+tmp3]
                ;and    ecx, eax
                or      edx, 1          ; | 1
                mov     [ebp+incr], edx ; size_t inc = hash_inc(op->hash, mask);

ha_4:                                   ; ...
                mov     eax, [ebp+pos]  ; while ((xp = &newtbl[pos])->key)
                shl     eax, 4
                mov     ecx, [ebp+newtbl]
                add     ecx, eax
                mov     [ebp+xp], ecx
                add     ecx, 8
                mov     eax, [ecx]
                cmp     eax, 0
                jz      ha_5
                mov     eax, [ebp+pos]  ; #define hash_pos_next(pos, inc, mask) (((pos) + (inc)) & (mask))
                mov     ecx, [ebp+incr]
                add     eax, ecx
                mov     ecx, [ebp+mask]
                and     eax, ecx
                mov     [ebp+pos], eax  ; pos = hash_pos_next(pos, inc, mask);
                jmp     short ha_4
; ---------------------------------------------------------------------------

ha_5:                                   ; ...
                mov     eax, [ebp+xp]
                mov     ecx, [ebp+op]
                mov     edx, 16
                push    edx
                push    ecx
                push    eax
                mov     [ebp+tmp4], ecx
                call    memmove         ; *xp = *op;
                add     esp, 12
                mov     eax, [ebp+op]   ; if (op == np)
                mov     ecx, [ebp+np]
                cmp     eax, ecx
                jnz     ha_6
                mov     eax, [ebp+xp]
                mov     [ebp+np], eax   ; np = xp;

ha_6:                                   ; ...
                jmp     ha_2
; ---------------------------------------------------------------------------

ha_7:                                   ; ...
                mov     eax, [ebp+head]
                mov     ecx, [eax]
                push    ecx
                call    nasm_free       ; nasm_free(head->table);
                add     esp, 4

ha_8:                                   ; ...
                mov     eax, [ebp+head]
                mov     ecx, [ebp+newtbl]
                mov     [eax], ecx      ; head->table = newtbl;
                mov     eax, [ebp+head]
                add     eax, 8
                mov     ecx, [ebp+newsize]
                mov     [eax], ecx      ; head->size = newsize;
                mov     eax, [ebp+head]
                add     eax, 12
                mov     ecx, [ebp+newsize]
                shr     ecx, 1          ; #define hash_max_load(size)
                                        ;   ((size) * (HASH_MAX_LOAD - 1) / HASH_MAX_LOAD)
                mov     [eax], ecx      ; head->max_load = hash_max_load(newsize);

ha_9:                                   ; ...
                mov     eax, [ebp+np]
                add     eax, 12         ; return &np->data;
                leave
                retn


; =============== S U B R O U T I N E =======================================

; ---------------------------------------------------------------------------
; Function: hash_iterate
;
; Description: Iterate over all members of a hash set.
;              For the first call, iterator should be initialized to NULL.
;              Returns the data pointer, or NULL on failure.
;
; C Declaration:
;      void *hash_iterate(const struct hash_table *head,
;                         struct hash_tbl_node **iterator, const char **key)
;
; Input (Stack): [EBP+8]  = *head
;                [EBP+12] = **iterator
;                [EBP+16] = *key
;
; Output: none
;
; Modified Registers: EAX, ECX, EDX
; ---------------------------------------------------------------------------

%assign tmp     -0Ch
%assign ep      -8
%assign np      -4
%assign head     8
%assign iterator 0Ch
%assign key      10h

hash_iterate:
                push    ebp
                mov     ebp, esp
                sub     esp, 12
                nop
                mov     eax, [ebp+iterator]
                mov     ecx, [eax]
                mov     [ebp+np], ecx   ; struct hash_tbl_node *np = *iterator;
                mov     eax, [ebp+head]
                mov     ecx, [ebp+head]
                add     ecx, 8
                mov     edx, [ecx]
                shl     edx, 4
                mov     ecx, [eax]
                add     ecx, edx
                mov     [ebp+ep], ecx   ; struct hash_tbl_node *ep = head->table + head->size;
                mov     eax, [ebp+np]
                cmp     eax, 0          ; if (!np) {
                jz      hite_1
                jmp     hite_3
; ---------------------------------------------------------------------------

hite_1:                                 ; ...
                mov     eax, [ebp+head]
                mov     ecx, [eax]
                mov     [ebp+np], ecx   ; np = head->table;
                mov     eax, [ebp+np]   ; if (!np)
                cmp     eax, 0
                jz      hite_2
                jmp     hite_3
; ---------------------------------------------------------------------------

hite_2:                                 ; ...
                mov     eax, 0          ; return NULL; /* Uninitialized table */
                jmp     hite_8
; ---------------------------------------------------------------------------

hite_3:                                 ; ...
                mov     eax, [ebp+np]   ; while (np < ep) {
                mov     ecx, [ebp+ep]
                cmp     eax, ecx
                jnb     hite_6
                mov     eax, [ebp+np]
                add     eax, 8          ; np->key
                mov     ecx, [eax]
                cmp     ecx, 0          ; if (np->key) {
                jz      hite_5
                mov     eax, [ebp+iterator]
                mov     ecx, [ebp+np]
                add     ecx, 16
                mov     [eax], ecx      ; *iterator = np + 1;
                mov     eax, [ebp+key]
                cmp     eax, 0          ; if (key)
                jz      hite_4
                mov     eax, [ebp+key]
                mov     ecx, [ebp+np]
                add     ecx, 8
                mov     edx, [ecx]
                mov     [eax], edx      ; *key = np->key;

hite_4:                                 ; ...
                mov     eax, [ebp+np]
                add     eax, 12
                mov     [ebp+tmp], eax
                mov     eax, [ebp+tmp]
                mov     eax, [eax]      ; return np->data;
                jmp     hite_8
; ---------------------------------------------------------------------------

hite_5:                                 ; ...
                mov     eax, [ebp+np]
                mov     ecx, eax
                add     eax, 16         ; + structure size
                mov     [ebp+np], eax   ; np++;
                jmp     short hite_3
; ---------------------------------------------------------------------------

hite_6:                                 ; ...
                mov     eax, [ebp+iterator]
                mov     ecx, 0
                mov     [eax], ecx      ; *iterator = NULL;
                mov     eax, [ebp+key]
                cmp     eax, 0          ; if (key)
                jz      hite_7
                mov     eax, [ebp+key]
                mov     ecx, 0
                mov     [eax], ecx      ; *key = NULL;

hite_7:                                 ; ...
                mov     eax, 0

hite_8:                                 ; ...
                leave                   ; return NULL;
                retn

; =============== S U B R O U T I N E =======================================

; ---------------------------------------------------------------------------
; Function: hash_free
;
; Description: Free the hash itself. Doesn't free the data elements;
;              use hash_iterate() to do that first, if needed.
;              This function is normally used when the hash data entries are
;              either freed separately, or compound objects which can't be
;              freed in a single operation.
;
; C Declaration: void hash_free(struct hash_table *head)
;
; Input (Stack): [EBP+8] = *head
;
; Output: none
;
; Modified Registers: EAX, ECX, (EDX)
; ---------------------------------------------------------------------------

%assign p      -4
%assign head    8

hash_free:
                push    ebp
                mov     ebp, esp
                sub     esp, 4
                nop
                mov     eax, [ebp+head]
                mov     ecx, [eax]
                mov     [ebp+p], ecx    ; void *p = head->table;
                mov     eax, [ebp+head]
                mov     ecx, 0
                mov     [eax], ecx      ; head->table = NULL;
                mov     eax, [ebp+p]
                push    eax
                call    nasm_free       ; nasm_free(p);
                add     esp, 4
                leave
                retn

; =============== S U B R O U T I N E =======================================

; ---------------------------------------------------------------------------
; Function: hash_free_all
;
; Description: Frees the hash *and* all data elements.
;              This is applicable only in the case where the data element
;              is a single allocation. If the second argument is false,
;              the key string is part of the data allocation or belongs to
;              an allocation which will be freed separately,
;              if it is true the keys are also freed.
;
; C Declaration: void hash_free_all(struct hash_table *head, bool free_keys)
;
; Input (Stack): [EBP+8]  = *head
;                [EBP+12] = free_keys
;
; Output: none
;
; Modified Registers: EAX, ECX, (EDX)
; ---------------------------------------------------------------------------

%assign d        -0Ch
%assign keyp     -8
%assign iter     -4
%assign head      8
%assign free_keys 0Ch

hash_free_all:
                push    ebp
                mov     ebp, esp
                sub     esp, 12
                nop
                mov     eax, 0
                mov     [ebp+iter], eax ; struct hash_tbl_node *iter = NULL;

hfa_1:                                  ; ...
                lea     eax, [ebp+keyp] ; const char *keyp;
                push    eax
                lea     eax, [ebp+iter]
                push    eax
                mov     eax, [ebp+head]
                push    eax
                call    hash_iterate
                add     esp, 12         ; void *d;
                mov     [ebp+d], eax
                cmp     eax, 0          ; while ((d = hash_iterate(head, &iter, &keyp))) {
                jz      hfa_3
                mov     eax, [ebp+d]
                push    eax
                call    nasm_free       ; nasm_free(d);
                add     esp, 4
                mov     eax, [ebp+free_keys] ; if (free_keys)
                cmp     eax, 0
                jz      hfa_2
                mov     eax, [ebp+keyp]
                push    eax
                call    nasm_free       ; nasm_free((void *)keyp);
                add     esp, 4

hfa_2:                                  ; ...
                jmp     short hfa_1
; ---------------------------------------------------------------------------

hfa_3:                                  ; ...
                mov     eax, [ebp+head]
                push    eax
                call    hash_free       ; hash_free(head);
                add     esp, 4
                leave
                retn

; ===========================================================================
; DATA (hashtbl.asm, hashtbl.c)
; ===========================================================================

; section .data

; L_195:        db 'hashtbl.c',0        ; ...
; L_196:        db 'is_power2(size)',0  ; ...

