; ===========================================================================
; NASM v2.14.02 - NETWIDE ASSEMBLER FOR TRDOS 386 - Erdogan Tan - 18/09/2026 
; Disassembled from "md5.c" (Dissassembler: IDA)
; NASM Syntax: Erdogan Tan
; Last Update: 19/09/2026
; ===========================================================================
; md5.asm
; -------
; This file will be included in the "nasm386.asm" file
; Inclusion order: 5

; target: NASM.PRG (flat binary)
; main assembly file: nasm386.asm
; library section: libnasm.asm
; TRDOS 386 functions: system.asm 
; data section: data.asm
; bss section: bss.asm
; launcher: crt0.asm

;
; +-------------------------------------------------------------------------+
; |   This file has been generated by The Interactive Disassembler (IDA)    |
; |           Copyright (c) 2018 Hex-Rays, <support@hex-rays.com>           |
; |                            Freeware version                             |
; +-------------------------------------------------------------------------+
;

; File Name   : C:\Users\90542\OneDrive\Masaüstü\nasm_214_c_o\md5c.o
; Format      : ELF for Intel 386 (Relocatable)
;
; Source File : 'md5c.c'

; ===========================================================================
; CODE
; ===========================================================================

; section .text

; #define MD5_HASHBYTES 16

; typedef struct MD5Context {
;	uint32_t buf[4];
;	uint32_t bits[2];
;	unsigned char in[64];
; } MD5_CTX;

; =============== S U B R O U T I N E =======================================

; ---------------------------------------------------------------------------
; Function: MD5Init
;
; Description: Start MD5 accumulation. Set bit count to 0
;              and buffer to mysterious initialization constants.
;
; C Declaration: void MD5Init(MD5_CTX *ctx)
;
; Input (Stack): [EBP+8] = *ctx (buffer, md5 context address ptr)
;
; Output: none
;
; Modified Registers: EAX, ECX
; ---------------------------------------------------------------------------

ctx             equ  8

MD5Init:
                push    ebp
                mov     ebp, esp
                sub     esp, 0
                nop
                mov     eax, [ebp+ctx]
                mov     ecx, 67452301h
                mov     [eax], ecx      ; ctx->buf[0] = 0x67452301;
                mov     eax, [ebp+ctx]
                add     eax, 4
                mov     ecx, 0EFCDAB89h
                mov     [eax], ecx      ; ctx->buf[1] = 0xefcdab89;
                mov     eax, [ebp+ctx]
                add     eax, 8
                mov     ecx, 98BADCFEh
                mov     [eax], ecx      ; ctx->buf[2] = 0x98badcfe;
                mov     eax, [ebp+ctx]
                add     eax, 0Ch
                mov     ecx, 10325476h
                mov     [eax], ecx      ; ctx->buf[3] = 0x10325476;
                mov     eax, [ebp+ctx]
                add     eax, 16
                mov     ecx, 0
                mov     [eax], ecx      ; ctx->bits[0] = 0;
                mov     eax, [ebp+ctx]
                add     eax, 16
                add     eax, 4
                mov     ecx, 0
                mov     [eax], ecx      ; ctx->bits[1] = 0;
                leave
                retn


; =============== S U B R O U T I N E =======================================

; ---------------------------------------------------------------------------
; Function: MD5Update
;
; Description: Update context to reflect the concatenation
;              of another buffer full of bytes.
;
; C Declaration:
;       void MD5Update(MD5_CTX *ctx, unsigned char const *buf, unsigned len)
;
;
; Input (Stack): [EBP+8]  = *ctx
;                [EBP+12] = *buf
;                [EBP+16] = len
;
; Output: none
;
; Modified Registers: EAX, ECX, EDX
; ---------------------------------------------------------------------------

p               equ -8
t               equ -4
ctx             equ  8
buf             equ  0Ch
len             equ  10h

MD5Update:
                push    ebp
                mov     ebp, esp
                sub     esp, 8
                nop
                mov     eax, [ebp+ctx]
                add     eax, 16
                mov     ecx, [eax]
                mov     [ebp+t], ecx    ; t = ctx->bits[0];
                mov     eax, [ebp+ctx]
                add     eax, 16
                mov     ecx, [ebp+len]
                shl     ecx, 3
                mov     edx, [ebp+t]    ; uint32_t t;
                add     edx, ecx
                mov     [eax], edx
                mov     eax, [ebp+t]
                cmp     edx, eax        ; if ((ctx->bits[0] = t + ((uint32_t) len << 3)) < t)
                jnb     mu_1
                mov     eax, [ebp+ctx]
                add     eax, 16
                add     eax, 4
                mov     ecx, [eax]      ; ctx->bits[1]++;
                mov     edx, ecx
                inc     ecx
                mov     [eax], ecx

mu_1:                                   ; ...
                mov     eax, [ebp+ctx]  ; ctx->bits[1] += len >> 29;
                add     eax, 16
                add     eax, 4
                mov     ecx, [ebp+len]
                shr     ecx, 29
                mov     edx, [eax]
                add     edx, ecx
                mov     [eax], edx
                mov     eax, [ebp+t]    ; t = (t >> 3) & 0x3f;
                shr     eax, 3
                and     eax, 63
                mov     [ebp+t], eax
                mov     eax, [ebp+t]    ; if (t) {
                cmp     eax, 0
                jz      mu_3
                mov     eax, [ebp+ctx]
                add     eax, 24
                mov     ecx, [ebp+t]
                add     eax, ecx
                mov     [ebp+p], eax    ; unsigned char *p = (unsigned char *) ctx->in + t;
                mov     eax, 64
                mov     ecx, [ebp+t]
                sub     eax, ecx        ; t = 64 - t;
                mov     [ebp+t], eax
                mov     eax, [ebp+len]  ; if (len < t) {
                mov     ecx, [ebp+t]
                cmp     eax, ecx
                jnb     mu_2
                mov     eax, [ebp+len]
                push    eax
                mov     eax, [ebp+buf]
                push    eax
                mov     eax, [ebp+p]
                push    eax
                call    memcpy          ; memcpy(p, buf, len);
                add     esp, 12
                jmp     mu_5            ; return;
; ---------------------------------------------------------------------------

mu_2:                                   ; ...
                mov     eax, [ebp+t]
                push    eax
                mov     eax, [ebp+buf]
                push    eax
                mov     eax, [ebp+p]
                push    eax
                call    memcpy          ; memcpy(p, buf, t);
                add     esp, 12
                mov     eax, [ebp+ctx]  ; ctx->buf
                mov     ecx, [ebp+ctx]
                add     ecx, 24         ; ctx->in
                push    ecx
                push    eax
                call    MD5Transform    ; MD5Transform(ctx->buf, (uint32_t *) ctx->in);
                add     esp, 8
                mov     eax, [ebp+t]
                mov     ecx, [ebp+buf]
                add     ecx, eax
                mov     [ebp+buf], ecx  ; buf += t;
                mov     eax, [ebp+len]
                mov     ecx, [ebp+t]
                sub     eax, ecx
                mov     [ebp+len], eax  ; len -= t;

mu_3:                                   ; ...
                mov     eax, [ebp+len]  ; while (len >= 64) {
                cmp     eax, 64
                jb      mu_4
                mov     eax, [ebp+ctx]
                add     eax, 24
                mov     ecx, 64
                push    ecx
                mov     ecx, [ebp+buf]
                push    ecx
                push    eax
                call    memcpy          ; memcpy(ctx->in, buf, 64);
                add     esp, 12
                mov     eax, [ebp+ctx]
                mov     ecx, [ebp+ctx]
                add     ecx, 24
                push    ecx
                push    eax
                call    MD5Transform    ; MD5Transform(ctx->buf, (uint32_t *) ctx->in);
                add     esp, 8
                mov     eax, [ebp+buf]
                add     eax, 64
                mov     [ebp+buf], eax  ; buf += 64;
                mov     eax, [ebp+len]
                sub     eax, 64
                mov     [ebp+len], eax  ; len -= 64;
                jmp     short mu_3
; ---------------------------------------------------------------------------

mu_4:                                   ; ...
                mov     eax, [ebp+ctx]
                add     eax, 24
                mov     ecx, [ebp+len]
                push    ecx
                mov     ecx, [ebp+buf]
                push    ecx
                push    eax
                call    memcpy          ; memcpy(ctx->in, buf, len);
                add     esp, 12

mu_5:                                   ; ...
                leave
                retn


; =============== S U B R O U T I N E =======================================

; ---------------------------------------------------------------------------
; Function: MD5Final
;
; Description: Final wrapup - pad to 64-byte boundary with the bit pattern 
;              1 0* (64-bit count of bits processed, MSB-first)
;
; C Declaration: void MD5Final(unsigned char digest[16], MD5_CTX *ctx)
;
;
; Input (Stack): [EBP+8]  = digest[16]
;                [EBP+12] = *ctx
;
; Output: none
;
; Modified Registers: EAX, ECX, EDX
; ---------------------------------------------------------------------------

p               equ -8
count           equ -4
digest          equ  8
ctx             equ  0Ch

MD5Final:
                push    ebp
                mov     ebp, esp
                sub     esp, 8          ; unsigned count;
                nop                     ; unsigned char *p;
                mov     eax, [ebp+ctx]
                add     eax, 16
                mov     ecx, [eax]
                shr     ecx, 3
                and     ecx, 3Fh
                mov     [ebp+count], ecx ; count = (ctx->bits[0] >> 3) & 0x3F;
                mov     eax, [ebp+ctx]
                add     eax, 24
                mov     ecx, [ebp+count]
                add     eax, ecx
                mov     [ebp+p], eax    ; p = ctx->in + count;
                mov     eax, [ebp+p]
                mov     ecx, eax
                inc     eax
                mov     [ebp+p], eax
                mov     eax, 80h
                mov     [ecx], al       ; *p++ = 0x80;
                mov     eax, 63
                mov     ecx, [ebp+count]
                sub     eax, ecx
                mov     [ebp+count], eax ; count = 64 - 1 - count;
                mov     eax, [ebp+count]
                cmp     eax, 8          ; if (count < 8) {
                jnb     mf_1
                mov     eax, [ebp+count]
                push    eax
                mov     eax, 0
                push    eax
                mov     eax, [ebp+p]
                push    eax
                call    memset          ; memset(p, 0, count);
                add     esp, 12
                mov     eax, [ebp+ctx]
                mov     ecx, [ebp+ctx]
                add     ecx, 18h
                push    ecx
                push    eax
                call    MD5Transform    ; MD5Transform(ctx->buf, (uint32_t *) ctx->in);
                add     esp, 8
                mov     eax, [ebp+ctx]
                add     eax, 24
                mov     ecx, 56
                push    ecx
                mov     ecx, 0
                push    ecx
                push    eax
                call    memset          ; memset(ctx->in, 0, 56);
                add     esp, 12
                jmp     mf_2
; ---------------------------------------------------------------------------

mf_1:                                   ; ...
                mov     eax, [ebp+count] ; } else {
                sub     eax, 8
                push    eax
                mov     eax, 0
                push    eax
                mov     eax, [ebp+p]
                push    eax
                call    memset          ; memset(p, 0, count - 8);
                add     esp, 12

mf_2:                                   ; ...
                mov     eax, [ebp+ctx]
                add     eax, 24
                add     eax, 56         ; ctx->in)[14]
                mov     ecx, [ebp+ctx]
                add     ecx, 16         ; ctx->bits[0]
                mov     edx, [ecx]
                mov     [eax], edx      ; ((uint32_t *) ctx->in)[14] = ctx->bits[0];
                mov     eax, [ebp+ctx]
                add     eax, 24
                add     eax, 60         ; ctx->in)[15]
                mov     ecx, [ebp+ctx]
                add     ecx, 16
                add     ecx, 4          ; ctx->bits[1]
                mov     edx, [ecx]
                mov     [eax], edx      ; ((uint32_t *) ctx->in)[15] = ctx->bits[1];
                mov     eax, [ebp+ctx]
                mov     ecx, [ebp+ctx]
                add     ecx, 24
                push    ecx
                push    eax
                call    MD5Transform    ; MD5Transform(ctx->buf, (uint32_t *) ctx->in);
                add     esp, 8
                mov     eax, [ebp+ctx]
                mov     ecx, 16
                push    ecx
                push    eax
                mov     eax, [ebp+digest]
                push    eax
                call    memcpy          ; memcpy(digest, ctx->buf, 16);
                add     esp, 12
                mov     eax, 88         ; sizeof(*ctx)
                push    eax
                mov     eax, 0
                push    eax
                mov     eax, [ebp+ctx]
                push    eax
                call    memset          ; memset((char *) ctx, 0, sizeof(*ctx));
                add     esp, 12
                leave
                retn


; =============== S U B R O U T I N E =======================================

; ---------------------------------------------------------------------------
; Function: MD5Transform
;
; Description: The core of the MD5 algorithm, this alters an existing
;              MD5 hash to reflect the addition of 16 longwords of new data.
;              MD5Update blocks the data and converts bytes into longwords
;              for this routine.
;
; C Declaration: void MD5Transform(uint32_t buf[4], uint32_t const in[16])
;
; Input (Stack): [EBP+8]  = digest[16]
;                [EBP+12] = *ctx
;
; Output: none
;
; Modified Registers: EAX, ECX, EDX
; ---------------------------------------------------------------------------

d               equ -10h
c               equ -0Ch
b               equ -8
a               equ -4
buf             equ  8
in              equ  0Ch

MD5Transform:

; /* The four core functions - F1 is optimized somewhat */
;
; /* #define F1(x, y, z) (x & y | ~x & z) */
; #define F1(x, y, z) (z ^ (x & (y ^ z)))
; #define F2(x, y, z) F1(z, x, y)
; #define F3(x, y, z) (x ^ y ^ z)
; #define F4(x, y, z) (y ^ (x | ~z))
;
; /* This is the central step in the MD5 algorithm. */
; #define MD5STEP(f, w, x, y, z, data, s) \
; ( w += f(x, y, z) + data,  w = w<<s | w>>(32-s),  w += x )-

                push    ebp
                mov     ebp, esp
                sub     esp, 16
                nop                     ; register uint32_t a, b, c, d;
                mov     eax, [ebp+buf]
                mov     ecx, [eax]
                mov     [ebp+a], ecx    ; a = buf[0];
                mov     eax, [ebp+buf]
                add     eax, 4
                mov     ecx, [eax]
                mov     [ebp+b], ecx    ; b = buf[1];
                mov     eax, [ebp+buf]
                add     eax, 8
                mov     ecx, [eax]
                mov     [ebp+c], ecx    ; c = buf[2];
                mov     eax, [ebp+buf]
                add     eax, 12
                mov     ecx, [eax]
                mov     [ebp+d], ecx    ; d = buf[3];
                mov     eax, [ebp+c]    ; F1(x, y, z) = (z ^ (x & (y ^ z)))
                mov     ecx, [ebp+d]    ; z
                xor     eax, ecx        ; y ^ z
                mov     ecx, [ebp+b]    ; x
                and     ecx, eax        ; x & (y ^ z)
                mov     eax, [ebp+d]
                xor     eax, ecx        ; z ^ (x & (y ^ z))
                mov     ecx, [ebp+in]
                mov     edx, [ecx]      ; in[0]
                add     eax, edx
                add     eax, 0D76AA478h ; in[0] + 0xd76aa478
                mov     ecx, [ebp+a]
                add     ecx, eax
                mov     [ebp+a], ecx    ; w += f(x, y, z) + data
                mov     eax, [ebp+a]
                shl     eax, 7          ; w = w<<s
                mov     ecx, [ebp+a]
                shr     ecx, 25
                or      eax, ecx        ; | w>>(32-s)
                mov     [ebp+a], eax
                mov     eax, [ebp+a]
                mov     ecx, [ebp+b]
                add     eax, ecx        ; w += x
                mov     [ebp+a], eax    ; MD5STEP(F1, a, b, c, d, in[0] + 0xd76aa478, 7);
                mov     eax, [ebp+b]
                mov     ecx, [ebp+c]
                xor     eax, ecx
                mov     ecx, [ebp+a]
                and     ecx, eax
                mov     eax, [ebp+c]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 4
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 0E8C7B756h
                mov     ecx, [ebp+d]
                add     ecx, eax
                mov     [ebp+d], ecx
                mov     eax, [ebp+d]
                shl     eax, 12
                mov     ecx, [ebp+d]
                shr     ecx, 20
                or      eax, ecx
                mov     [ebp+d], eax
                mov     eax, [ebp+d]
                mov     ecx, [ebp+a]
                add     eax, ecx
                mov     [ebp+d], eax    ; MD5STEP(F1, d, a, b, c, in[1] + 0xe8c7b756, 12);
                mov     eax, [ebp+a]
                mov     ecx, [ebp+b]
                xor     eax, ecx
                mov     ecx, [ebp+d]
                and     ecx, eax
                mov     eax, [ebp+b]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 8
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 242070DBh
                mov     ecx, [ebp+c]
                add     ecx, eax
                mov     [ebp+c], ecx
                mov     eax, [ebp+c]
                shl     eax, 17
                mov     ecx, [ebp+c]
                shr     ecx, 15
                or      eax, ecx
                mov     [ebp+c], eax
                mov     eax, [ebp+c]
                mov     ecx, [ebp+d]
                add     eax, ecx
                mov     [ebp+c], eax    ; MD5STEP(F1, c, d, a, b, in[2] + 0x242070db, 17);
                mov     eax, [ebp+d]
                mov     ecx, [ebp+a]
                xor     eax, ecx
                mov     ecx, [ebp+c]
                and     ecx, eax
                mov     eax, [ebp+a]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 12
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 0C1BDCEEEh
                mov     ecx, [ebp+b]
                add     ecx, eax
                mov     [ebp+b], ecx
                mov     eax, [ebp+b]
                shl     eax, 22
                mov     ecx, [ebp+b]
                shr     ecx, 10
                or      eax, ecx
                mov     [ebp+b], eax
                mov     eax, [ebp+b]
                mov     ecx, [ebp+c]
                add     eax, ecx
                mov     [ebp+b], eax    ; MD5STEP(F1, b, c, d, a, in[3] + 0xc1bdceee, 22);
                mov     eax, [ebp+c]
                mov     ecx, [ebp+d]
                xor     eax, ecx
                mov     ecx, [ebp+b]
                and     ecx, eax
                mov     eax, [ebp+d]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 16
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 0F57C0FAFh
                mov     ecx, [ebp+a]
                add     ecx, eax
                mov     [ebp+a], ecx
                mov     eax, [ebp+a]
                shl     eax, 7
                mov     ecx, [ebp+a]
                shr     ecx, 25
                or      eax, ecx
                mov     [ebp+a], eax    ; MD5STEP(F1, a, b, c, d, in[4] + 0xf57c0faf, 7);
                mov     eax, [ebp+a]
                mov     ecx, [ebp+b]
                add     eax, ecx
                mov     [ebp+a], eax
                mov     eax, [ebp+b]
                mov     ecx, [ebp+c]
                xor     eax, ecx
                mov     ecx, [ebp+a]
                and     ecx, eax
                mov     eax, [ebp+c]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 20
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 4787C62Ah
                mov     ecx, [ebp+d]
                add     ecx, eax
                mov     [ebp+d], ecx
                mov     eax, [ebp+d]
                shl     eax, 12
                mov     ecx, [ebp+d]
                shr     ecx, 20
                or      eax, ecx
                mov     [ebp+d], eax
                mov     eax, [ebp+d]
                mov     ecx, [ebp+a]
                add     eax, ecx
                mov     [ebp+d], eax    ; MD5STEP(F1, d, a, b, c, in[5] + 0x4787c62a, 12);
                mov     eax, [ebp+a]
                mov     ecx, [ebp+b]
                xor     eax, ecx
                mov     ecx, [ebp+d]
                and     ecx, eax
                mov     eax, [ebp+b]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 24
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 0A8304613h
                mov     ecx, [ebp+c]
                add     ecx, eax
                mov     [ebp+c], ecx
                mov     eax, [ebp+c]
                shl     eax, 17
                mov     ecx, [ebp+c]
                shr     ecx, 15
                or      eax, ecx
                mov     [ebp+c], eax
                mov     eax, [ebp+c]
                mov     ecx, [ebp+d]
                add     eax, ecx
                mov     [ebp+c], eax    ; MD5STEP(F1, c, d, a, b, in[6] + 0xa8304613, 17);
                mov     eax, [ebp+d]
                mov     ecx, [ebp+a]
                xor     eax, ecx
                mov     ecx, [ebp+c]
                and     ecx, eax
                mov     eax, [ebp+a]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 28
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 0FD469501h
                mov     ecx, [ebp+b]
                add     ecx, eax
                mov     [ebp+b], ecx
                mov     eax, [ebp+b]
                shl     eax, 22
                mov     ecx, [ebp+b]
                shr     ecx, 10
                or      eax, ecx
                mov     [ebp+b], eax
                mov     eax, [ebp+b]
                mov     ecx, [ebp+c]
                add     eax, ecx
                mov     [ebp+b], eax    ; MD5STEP(F1, b, c, d, a, in[7] + 0xfd469501, 22);
                mov     eax, [ebp+c]
                mov     ecx, [ebp+d]
                xor     eax, ecx
                mov     ecx, [ebp+b]
                and     ecx, eax
                mov     eax, [ebp+d]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 32
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 698098D8h
                mov     ecx, [ebp+a]
                add     ecx, eax
                mov     [ebp+a], ecx
                mov     eax, [ebp+a]
                shl     eax, 7
                mov     ecx, [ebp+a]
                shr     ecx, 25
                or      eax, ecx
                mov     [ebp+a], eax
                mov     eax, [ebp+a]
                mov     ecx, [ebp+b]
                add     eax, ecx
                mov     [ebp+a], eax    ; MD5STEP(F1, a, b, c, d, in[8] + 0x698098d8, 7);
                mov     eax, [ebp+b]
                mov     ecx, [ebp+c]
                xor     eax, ecx
                mov     ecx, [ebp+a]
                and     ecx, eax
                mov     eax, [ebp+c]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 36
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 8B44F7AFh
                mov     ecx, [ebp+d]
                add     ecx, eax
                mov     [ebp+d], ecx
                mov     eax, [ebp+d]
                shl     eax, 12
                mov     ecx, [ebp+d]
                shr     ecx, 20
                or      eax, ecx
                mov     [ebp+d], eax
                mov     eax, [ebp+d]
                mov     ecx, [ebp+a]
                add     eax, ecx
                mov     [ebp+d], eax    ; MD5STEP(F1, d, a, b, c, in[9] + 0x8b44f7af, 12);
                mov     eax, [ebp+a]
                mov     ecx, [ebp+b]
                xor     eax, ecx
                mov     ecx, [ebp+d]
                and     ecx, eax
                mov     eax, [ebp+b]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 40
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 0FFFF5BB1h
                mov     ecx, [ebp+c]
                add     ecx, eax
                mov     [ebp+c], ecx
                mov     eax, [ebp+c]
                shl     eax, 17
                mov     ecx, [ebp+c]
                shr     ecx, 15
                or      eax, ecx
                mov     [ebp+c], eax
                mov     eax, [ebp+c]
                mov     ecx, [ebp+d]
                add     eax, ecx
                mov     [ebp+c], eax    ; MD5STEP(F1, c, d, a, b, in[10] + 0xffff5bb1, 17);
                mov     eax, [ebp+d]
                mov     ecx, [ebp+a]
                xor     eax, ecx
                mov     ecx, [ebp+c]
                and     ecx, eax
                mov     eax, [ebp+a]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 44
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 895CD7BEh
                mov     ecx, [ebp+b]
                add     ecx, eax
                mov     [ebp+b], ecx
                mov     eax, [ebp+b]
                shl     eax, 22
                mov     ecx, [ebp+b]
                shr     ecx, 10
                or      eax, ecx
                mov     [ebp+b], eax
                mov     eax, [ebp+b]
                mov     ecx, [ebp+c]
                add     eax, ecx
                mov     [ebp+b], eax    ; MD5STEP(F1, b, c, d, a, in[11] + 0x895cd7be, 22);
                mov     eax, [ebp+c]
                mov     ecx, [ebp+d]
                xor     eax, ecx
                mov     ecx, [ebp+b]
                and     ecx, eax
                mov     eax, [ebp+d]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 48
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 6B901122h
                mov     ecx, [ebp+a]
                add     ecx, eax
                mov     [ebp+a], ecx
                mov     eax, [ebp+a]
                shl     eax, 7
                mov     ecx, [ebp+a]
                shr     ecx, 25
                or      eax, ecx
                mov     [ebp+a], eax
                mov     eax, [ebp+a]
                mov     ecx, [ebp+b]
                add     eax, ecx
                mov     [ebp+a], eax    ; MD5STEP(F1, a, b, c, d, in[12] + 0x6b901122, 7);
                mov     eax, [ebp+b]
                mov     ecx, [ebp+c]
                xor     eax, ecx
                mov     ecx, [ebp+a]
                and     ecx, eax
                mov     eax, [ebp+c]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 52
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 0FD987193h
                mov     ecx, [ebp+d]
                add     ecx, eax
                mov     [ebp+d], ecx
                mov     eax, [ebp+d]
                shl     eax, 12
                mov     ecx, [ebp+d]
                shr     ecx, 20
                or      eax, ecx
                mov     [ebp+d], eax
                mov     eax, [ebp+d]
                mov     ecx, [ebp+a]
                add     eax, ecx
                mov     [ebp+d], eax    ; MD5STEP(F1, d, a, b, c, in[13] + 0xfd987193, 12);
                mov     eax, [ebp+a]
                mov     ecx, [ebp+b]
                xor     eax, ecx
                mov     ecx, [ebp+d]
                and     ecx, eax
                mov     eax, [ebp+b]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 56
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 0A679438Eh
                mov     ecx, [ebp+c]
                add     ecx, eax
                mov     [ebp+c], ecx
                mov     eax, [ebp+c]
                shl     eax, 17
                mov     ecx, [ebp+c]
                shr     ecx, 15
                or      eax, ecx
                mov     [ebp+c], eax
                mov     eax, [ebp+c]
                mov     ecx, [ebp+d]
                add     eax, ecx
                mov     [ebp+c], eax    ; MD5STEP(F1, c, d, a, b, in[14] + 0xa679438e, 17);
                mov     eax, [ebp+d]
                mov     ecx, [ebp+a]
                xor     eax, ecx
                mov     ecx, [ebp+c]
                and     ecx, eax
                mov     eax, [ebp+a]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 60
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 49B40821h
                mov     ecx, [ebp+b]
                add     ecx, eax
                mov     [ebp+b], ecx
                mov     eax, [ebp+b]
                shl     eax, 22
                mov     ecx, [ebp+b]
                shr     ecx, 10
                or      eax, ecx
                mov     [ebp+b], eax
                mov     eax, [ebp+b]
                mov     ecx, [ebp+c]
                add     eax, ecx
                mov     [ebp+b], eax    ; MD5STEP(F1, b, c, d, a, in[15] + 0x49b40821, 22);
                mov     eax, [ebp+b]    ; F2(x, y, z) = F1(z, x, y) = (y ^ (z & (x ^ y)))
                mov     ecx, [ebp+c]    ; y
                xor     eax, ecx        ; x ^ y
                mov     ecx, [ebp+d]    ; z
                and     ecx, eax        ; z & (x ^ y)
                mov     eax, [ebp+c]
                xor     eax, ecx        ; y ^ (z & (x ^ y))
                mov     ecx, [ebp+in]
                add     ecx, 4          ; in[1]
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 0F61E2562h ; data = in[1] + 0xf61e2562
                mov     ecx, [ebp+a]    ; w
                add     ecx, eax
                mov     [ebp+a], ecx    ; w += f(x, y, z) + data
                mov     eax, [ebp+a]
                shl     eax, 5          ; s = 5
                mov     ecx, [ebp+a]
                shr     ecx, 27         ; 32 - 5 ; 32 - s
                or      eax, ecx
                mov     [ebp+a], eax    ; w = w<<s | w>>(32-s)
                mov     eax, [ebp+a]
                mov     ecx, [ebp+b]    ; x
                add     eax, ecx        ; w += x
                mov     [ebp+a], eax    ; MD5STEP(F2, a, b, c, d, in[1] + 0xf61e2562, 5);
                mov     eax, [ebp+a]
                mov     ecx, [ebp+b]
                xor     eax, ecx
                mov     ecx, [ebp+c]
                and     ecx, eax
                mov     eax, [ebp+b]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 24
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 0C040B340h
                mov     ecx, [ebp+d]
                add     ecx, eax
                mov     [ebp+d], ecx
                mov     eax, [ebp+d]
                shl     eax, 9
                mov     ecx, [ebp+d]
                shr     ecx, 23
                or      eax, ecx
                mov     [ebp+d], eax
                mov     eax, [ebp+d]
                mov     ecx, [ebp+a]
                add     eax, ecx
                mov     [ebp+d], eax    ; MD5STEP(F2, d, a, b, c, in[6] + 0xc040b340, 9);
                mov     eax, [ebp+d]
                mov     ecx, [ebp+a]
                xor     eax, ecx
                mov     ecx, [ebp+b]
                and     ecx, eax
                mov     eax, [ebp+a]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 44
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 265E5A51h
                mov     ecx, [ebp+c]
                add     ecx, eax
                mov     [ebp+c], ecx
                mov     eax, [ebp+c]
                shl     eax, 14
                mov     ecx, [ebp+c]
                shr     ecx, 18
                or      eax, ecx
                mov     [ebp+c], eax
                mov     eax, [ebp+c]
                mov     ecx, [ebp+d]
                add     eax, ecx
                mov     [ebp+c], eax    ; MD5STEP(F2, c, d, a, b, in[11] + 0x265e5a51, 14);
                mov     eax, [ebp+c]
                mov     ecx, [ebp+d]
                xor     eax, ecx
                mov     ecx, [ebp+a]
                and     ecx, eax
                mov     eax, [ebp+d]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 0E9B6C7AAh
                mov     ecx, [ebp+b]
                add     ecx, eax
                mov     [ebp+b], ecx
                mov     eax, [ebp+b]
                shl     eax, 20
                mov     ecx, [ebp+b]
                shr     ecx, 12
                or      eax, ecx
                mov     [ebp+b], eax
                mov     eax, [ebp+b]
                mov     ecx, [ebp+c]
                add     eax, ecx
                mov     [ebp+b], eax    ; MD5STEP(F2, b, c, d, a, in[0] + 0xe9b6c7aa, 20);
                mov     eax, [ebp+b]
                mov     ecx, [ebp+c]
                xor     eax, ecx
                mov     ecx, [ebp+d]
                and     ecx, eax
                mov     eax, [ebp+c]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 20
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 0D62F105Dh
                mov     ecx, [ebp+a]
                add     ecx, eax
                mov     [ebp+a], ecx
                mov     eax, [ebp+a]
                shl     eax, 5
                mov     ecx, [ebp+a]
                shr     ecx, 27
                or      eax, ecx
                mov     [ebp+a], eax
                mov     eax, [ebp+a]
                mov     ecx, [ebp+b]
                add     eax, ecx
                mov     [ebp+a], eax    ; MD5STEP(F2, a, b, c, d, in[5] + 0xd62f105d, 5);
                mov     eax, [ebp+a]
                mov     ecx, [ebp+b]
                xor     eax, ecx
                mov     ecx, [ebp+c]
                and     ecx, eax
                mov     eax, [ebp+b]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 40
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 2441453h
                mov     ecx, [ebp+d]
                add     ecx, eax
                mov     [ebp+d], ecx
                mov     eax, [ebp+d]
                shl     eax, 9
                mov     ecx, [ebp+d]
                shr     ecx, 23
                or      eax, ecx
                mov     [ebp+d], eax
                mov     eax, [ebp+d]
                mov     ecx, [ebp+a]
                add     eax, ecx
                mov     [ebp+d], eax    ; MD5STEP(F2, d, a, b, c, in[10] + 0x02441453, 9);
                mov     eax, [ebp+d]
                mov     ecx, [ebp+a]
                xor     eax, ecx
                mov     ecx, [ebp+b]
                and     ecx, eax
                mov     eax, [ebp+a]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 60
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 0D8A1E681h
                mov     ecx, [ebp+c]
                add     ecx, eax
                mov     [ebp+c], ecx
                mov     eax, [ebp+c]
                shl     eax, 14
                mov     ecx, [ebp+c]
                shr     ecx, 18
                or      eax, ecx
                mov     [ebp+c], eax    ; MD5STEP(F2, c, d, a, b, in[15] + 0xd8a1e681, 14);
                mov     eax, [ebp+c]
                mov     ecx, [ebp+d]
                add     eax, ecx
                mov     [ebp+c], eax
                mov     eax, [ebp+c]
                mov     ecx, [ebp+d]
                xor     eax, ecx
                mov     ecx, [ebp+a]
                and     ecx, eax
                mov     eax, [ebp+d]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 16
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 0E7D3FBC8h
                mov     ecx, [ebp+b]
                add     ecx, eax
                mov     [ebp+b], ecx
                mov     eax, [ebp+b]
                shl     eax, 20
                mov     ecx, [ebp+b]
                shr     ecx, 12
                or      eax, ecx
                mov     [ebp+b], eax
                mov     eax, [ebp+b]
                mov     ecx, [ebp+c]
                add     eax, ecx
                mov     [ebp+b], eax    ; MD5STEP(F2, b, c, d, a, in[4] + 0xe7d3fbc8, 20);
                mov     eax, [ebp+b]
                mov     ecx, [ebp+c]
                xor     eax, ecx
                mov     ecx, [ebp+d]
                and     ecx, eax
                mov     eax, [ebp+c]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 36
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 21E1CDE6h
                mov     ecx, [ebp+a]
                add     ecx, eax
                mov     [ebp+a], ecx
                mov     eax, [ebp+a]
                shl     eax, 5
                mov     ecx, [ebp+a]
                shr     ecx, 27
                or      eax, ecx
                mov     [ebp+a], eax
                mov     eax, [ebp+a]
                mov     ecx, [ebp+b]
                add     eax, ecx
                mov     [ebp+a], eax    ; MD5STEP(F2, a, b, c, d, in[9] + 0x21e1cde6, 5);
                mov     eax, [ebp+a]
                mov     ecx, [ebp+b]
                xor     eax, ecx
                mov     ecx, [ebp+c]
                and     ecx, eax
                mov     eax, [ebp+b]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 56
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 0C33707D6h
                mov     ecx, [ebp+d]
                add     ecx, eax
                mov     [ebp+d], ecx
                mov     eax, [ebp+d]
                shl     eax, 9
                mov     ecx, [ebp+d]
                shr     ecx, 23
                or      eax, ecx
                mov     [ebp+d], eax
                mov     eax, [ebp+d]
                mov     ecx, [ebp+a]
                add     eax, ecx
                mov     [ebp+d], eax    ; MD5STEP(F2, d, a, b, c, in[14] + 0xc33707d6, 9);
                mov     eax, [ebp+d]
                mov     ecx, [ebp+a]
                xor     eax, ecx
                mov     ecx, [ebp+b]
                and     ecx, eax
                mov     eax, [ebp+a]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 12
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 0F4D50D87h
                mov     ecx, [ebp+c]
                add     ecx, eax
                mov     [ebp+c], ecx
                mov     eax, [ebp+c]
                shl     eax, 14
                mov     ecx, [ebp+c]
                shr     ecx, 18
                or      eax, ecx
                mov     [ebp+c], eax
                mov     eax, [ebp+c]
                mov     ecx, [ebp+d]
                add     eax, ecx
                mov     [ebp+c], eax    ; MD5STEP(F2, c, d, a, b, in[3] + 0xf4d50d87, 14);
                mov     eax, [ebp+c]
                mov     ecx, [ebp+d]
                xor     eax, ecx
                mov     ecx, [ebp+a]
                and     ecx, eax
                mov     eax, [ebp+d]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 32
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 455A14EDh
                mov     ecx, [ebp+b]
                add     ecx, eax
                mov     [ebp+b], ecx
                mov     eax, [ebp+b]
                shl     eax, 20
                mov     ecx, [ebp+b]
                shr     ecx, 12
                or      eax, ecx
                mov     [ebp+b], eax
                mov     eax, [ebp+b]
                mov     ecx, [ebp+c]
                add     eax, ecx
                mov     [ebp+b], eax    ; MD5STEP(F2, b, c, d, a, in[8] + 0x455a14ed, 20);
                mov     eax, [ebp+b]
                mov     ecx, [ebp+c]
                xor     eax, ecx
                mov     ecx, [ebp+d]
                and     ecx, eax
                mov     eax, [ebp+c]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 52
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 0A9E3E905h
                mov     ecx, [ebp+a]
                add     ecx, eax
                mov     [ebp+a], ecx
                mov     eax, [ebp+a]
                shl     eax, 5
                mov     ecx, [ebp+a]
                shr     ecx, 27
                or      eax, ecx
                mov     [ebp+a], eax
                mov     eax, [ebp+a]
                mov     ecx, [ebp+b]
                add     eax, ecx
                mov     [ebp+a], eax    ; MD5STEP(F2, a, b, c, d, in[13] + 0xa9e3e905, 5);
                mov     eax, [ebp+a]
                mov     ecx, [ebp+b]
                xor     eax, ecx
                mov     ecx, [ebp+c]
                and     ecx, eax
                mov     eax, [ebp+b]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 8
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 0FCEFA3F8h
                mov     ecx, [ebp+d]
                add     ecx, eax
                mov     [ebp+d], ecx
                mov     eax, [ebp+d]
                shl     eax, 9
                mov     ecx, [ebp+d]
                shr     ecx, 23
                or      eax, ecx
                mov     [ebp+d], eax
                mov     eax, [ebp+d]
                mov     ecx, [ebp+a]
                add     eax, ecx
                mov     [ebp+d], eax    ; MD5STEP(F2, d, a, b, c, in[2] + 0xfcefa3f8, 9);
                mov     eax, [ebp+d]
                mov     ecx, [ebp+a]
                xor     eax, ecx
                mov     ecx, [ebp+b]
                and     ecx, eax
                mov     eax, [ebp+a]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 28
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 676F02D9h
                mov     ecx, [ebp+c]
                add     ecx, eax
                mov     [ebp+c], ecx
                mov     eax, [ebp+c]
                shl     eax, 14
                mov     ecx, [ebp+c]
                shr     ecx, 18
                or      eax, ecx
                mov     [ebp+c], eax
                mov     eax, [ebp+c]
                mov     ecx, [ebp+d]
                add     eax, ecx
                mov     [ebp+c], eax    ; MD5STEP(F2, c, d, a, b, in[7] + 0x676f02d9, 14);
                mov     eax, [ebp+c]
                mov     ecx, [ebp+d]
                xor     eax, ecx
                mov     ecx, [ebp+a]
                and     ecx, eax
                mov     eax, [ebp+d]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 48
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 8D2A4C8Ah
                mov     ecx, [ebp+b]
                add     ecx, eax
                mov     [ebp+b], ecx
                mov     eax, [ebp+b]
                shl     eax, 20
                mov     ecx, [ebp+b]
                shr     ecx, 12
                or      eax, ecx
                mov     [ebp+b], eax
                mov     eax, [ebp+b]
                mov     ecx, [ebp+c]
                add     eax, ecx
                mov     [ebp+b], eax    ; MD5STEP(F2, b, c, d, a, in[12] + 0x8d2a4c8a, 20);
                mov     eax, [ebp+b]
                mov     ecx, [ebp+c]
                xor     eax, ecx
                mov     ecx, [ebp+d]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 20
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 0FFFA3942h
                mov     ecx, [ebp+a]
                add     ecx, eax
                mov     [ebp+a], ecx
                mov     eax, [ebp+a]
                shl     eax, 4
                mov     ecx, [ebp+a]
                shr     ecx, 28
                or      eax, ecx
                mov     [ebp+a], eax
                mov     eax, [ebp+a]
                mov     ecx, [ebp+b]
                add     eax, ecx
                mov     [ebp+a], eax    ; MD5STEP(F3, a, b, c, d, in[5] + 0xfffa3942, 4);
                mov     eax, [ebp+a]
                mov     ecx, [ebp+b]
                xor     eax, ecx
                mov     ecx, [ebp+c]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 32
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 8771F681h
                mov     ecx, [ebp+d]
                add     ecx, eax
                mov     [ebp+d], ecx
                mov     eax, [ebp+d]
                shl     eax, 11
                mov     ecx, [ebp+d]
                shr     ecx, 21
                or      eax, ecx
                mov     [ebp+d], eax
                mov     eax, [ebp+d]
                mov     ecx, [ebp+a]
                add     eax, ecx
                mov     [ebp+d], eax    ; MD5STEP(F3, d, a, b, c, in[8] + 0x8771f681, 11);
                mov     eax, [ebp+d]
                mov     ecx, [ebp+a]
                xor     eax, ecx
                mov     ecx, [ebp+b]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 44
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 6D9D6122h
                mov     ecx, [ebp+c]
                add     ecx, eax
                mov     [ebp+c], ecx
                mov     eax, [ebp+c]
                shl     eax, 16
                mov     ecx, [ebp+c]
                shr     ecx, 16
                or      eax, ecx
                mov     [ebp+c], eax
                mov     eax, [ebp+c]
                mov     ecx, [ebp+d]
                add     eax, ecx
                mov     [ebp+c], eax    ; MD5STEP(F3, c, d, a, b, in[11] + 0x6d9d6122, 16);
                mov     eax, [ebp+c]
                mov     ecx, [ebp+d]
                xor     eax, ecx
                mov     ecx, [ebp+a]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 56
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 0FDE5380Ch
                mov     ecx, [ebp+b]
                add     ecx, eax
                mov     [ebp+b], ecx
                mov     eax, [ebp+b]
                shl     eax, 23
                mov     ecx, [ebp+b]
                shr     ecx, 9
                or      eax, ecx
                mov     [ebp+b], eax
                mov     eax, [ebp+b]
                mov     ecx, [ebp+c]
                add     eax, ecx
                mov     [ebp+b], eax    ; MD5STEP(F3, b, c, d, a, in[14] + 0xfde5380c, 23);
                mov     eax, [ebp+b]
                mov     ecx, [ebp+c]
                xor     eax, ecx
                mov     ecx, [ebp+d]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 4          ; in[1]
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 0A4BEEA44h
                mov     ecx, [ebp+a]
                add     ecx, eax
                mov     [ebp+a], ecx
                mov     eax, [ebp+a]
                shl     eax, 4
                mov     ecx, [ebp+a]
                shr     ecx, 28
                or      eax, ecx
                mov     [ebp+a], eax
                mov     eax, [ebp+a]
                mov     ecx, [ebp+b]
                add     eax, ecx
                mov     [ebp+a], eax    ; MD5STEP(F3, a, b, c, d, in[1] + 0xa4beea44, 4);
                mov     eax, [ebp+a]
                mov     ecx, [ebp+b]
                xor     eax, ecx
                mov     ecx, [ebp+c]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 16
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 4BDECFA9h
                mov     ecx, [ebp+d]
                add     ecx, eax
                mov     [ebp+d], ecx
                mov     eax, [ebp+d]
                shl     eax, 11
                mov     ecx, [ebp+d]
                shr     ecx, 21
                or      eax, ecx
                mov     [ebp+d], eax
                mov     eax, [ebp+d]
                mov     ecx, [ebp+a]
                add     eax, ecx
                mov     [ebp+d], eax    ; MD5STEP(F3, d, a, b, c, in[4] + 0x4bdecfa9, 11);
                mov     eax, [ebp+d]
                mov     ecx, [ebp+a]
                xor     eax, ecx
                mov     ecx, [ebp+b]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 28
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 0F6BB4B60h
                mov     ecx, [ebp+c]
                add     ecx, eax
                mov     [ebp+c], ecx
                mov     eax, [ebp+c]
                shl     eax, 16
                mov     ecx, [ebp+c]
                shr     ecx, 16
                or      eax, ecx
                mov     [ebp+c], eax
                mov     eax, [ebp+c]
                mov     ecx, [ebp+d]
                add     eax, ecx
                mov     [ebp+c], eax    ; MD5STEP(F3, c, d, a, b, in[7] + 0xf6bb4b60, 16);
                mov     eax, [ebp+c]
                mov     ecx, [ebp+d]
                xor     eax, ecx
                mov     ecx, [ebp+a]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 40
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 0BEBFBC70h
                mov     ecx, [ebp+b]
                add     ecx, eax
                mov     [ebp+b], ecx
                mov     eax, [ebp+b]
                shl     eax, 23
                mov     ecx, [ebp+b]
                shr     ecx, 9
                or      eax, ecx
                mov     [ebp+b], eax
                mov     eax, [ebp+b]
                mov     ecx, [ebp+c]
                add     eax, ecx
                mov     [ebp+b], eax    ; MD5STEP(F3, b, c, d, a, in[10] + 0xbebfbc70, 23);
                mov     eax, [ebp+b]
                mov     ecx, [ebp+c]
                xor     eax, ecx
                mov     ecx, [ebp+d]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 52         ; in[13]
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 289B7EC6h
                mov     ecx, [ebp+a]
                add     ecx, eax
                mov     [ebp+a], ecx
                mov     eax, [ebp+a]
                shl     eax, 4
                mov     ecx, [ebp+a]
                shr     ecx, 28
                or      eax, ecx
                mov     [ebp+a], eax
                mov     eax, [ebp+a]
                mov     ecx, [ebp+b]
                add     eax, ecx
                mov     [ebp+a], eax    ; MD5STEP(F3, a, b, c, d, in[13] + 0x289b7ec6, 4);
                mov     eax, [ebp+a]
                mov     ecx, [ebp+b]
                xor     eax, ecx
                mov     ecx, [ebp+c]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                mov     edx, [ecx]      ; in[0]
                add     eax, edx
                add     eax, 0EAA127FAh
                mov     ecx, [ebp+d]
                add     ecx, eax
                mov     [ebp+d], ecx
                mov     eax, [ebp+d]
                shl     eax, 11
                mov     ecx, [ebp+d]
                shr     ecx, 21
                or      eax, ecx
                mov     [ebp+d], eax
                mov     eax, [ebp+d]
                mov     ecx, [ebp+a]
                add     eax, ecx
                mov     [ebp+d], eax    ; MD5STEP(F3, d, a, b, c, in[0] + 0xeaa127fa, 11);
                mov     eax, [ebp+d]
                mov     ecx, [ebp+a]
                xor     eax, ecx
                mov     ecx, [ebp+b]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 12
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 0D4EF3085h
                mov     ecx, [ebp+c]
                add     ecx, eax
                mov     [ebp+c], ecx
                mov     eax, [ebp+c]
                shl     eax, 16
                mov     ecx, [ebp+c]
                shr     ecx, 16
                or      eax, ecx
                mov     [ebp+c], eax
                mov     eax, [ebp+c]
                mov     ecx, [ebp+d]
                add     eax, ecx
                mov     [ebp+c], eax    ; MD5STEP(F3, c, d, a, b, in[3] + 0xd4ef3085, 16);
                mov     eax, [ebp+c]
                mov     ecx, [ebp+d]
                xor     eax, ecx
                mov     ecx, [ebp+a]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 24
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 4881D05h
                mov     ecx, [ebp+b]
                add     ecx, eax
                mov     [ebp+b], ecx
                mov     eax, [ebp+b]
                shl     eax, 23
                mov     ecx, [ebp+b]
                shr     ecx, 9
                or      eax, ecx
                mov     [ebp+b], eax
                mov     eax, [ebp+b]
                mov     ecx, [ebp+c]
                add     eax, ecx
                mov     [ebp+b], eax    ; MD5STEP(F3, b, c, d, a, in[6] + 0x04881d05, 23);
                mov     eax, [ebp+b]
                mov     ecx, [ebp+c]
                xor     eax, ecx
                mov     ecx, [ebp+d]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 36
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 0D9D4D039h
                mov     ecx, [ebp+a]
                add     ecx, eax
                mov     [ebp+a], ecx
                mov     eax, [ebp+a]
                shl     eax, 4
                mov     ecx, [ebp+a]
                shr     ecx, 28
                or      eax, ecx
                mov     [ebp+a], eax
                mov     eax, [ebp+a]
                mov     ecx, [ebp+b]
                add     eax, ecx
                mov     [ebp+a], eax    ; MD5STEP(F3, a, b, c, d, in[9] + 0xd9d4d039, 4);
                mov     eax, [ebp+a]
                mov     ecx, [ebp+b]
                xor     eax, ecx
                mov     ecx, [ebp+c]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 48
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 0E6DB99E5h
                mov     ecx, [ebp+d]
                add     ecx, eax
                mov     [ebp+d], ecx
                mov     eax, [ebp+d]
                shl     eax, 11
                mov     ecx, [ebp+d]
                shr     ecx, 21
                or      eax, ecx
                mov     [ebp+d], eax
                mov     eax, [ebp+d]
                mov     ecx, [ebp+a]
                add     eax, ecx
                mov     [ebp+d], eax    ; MD5STEP(F3, d, a, b, c, in[12] + 0xe6db99e5, 11);
                mov     eax, [ebp+d]
                mov     ecx, [ebp+a]
                xor     eax, ecx
                mov     ecx, [ebp+b]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 60
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 1FA27CF8h
                mov     ecx, [ebp+c]
                add     ecx, eax
                mov     [ebp+c], ecx
                mov     eax, [ebp+c]
                shl     eax, 16
                mov     ecx, [ebp+c]
                shr     ecx, 16
                or      eax, ecx
                mov     [ebp+c], eax
                mov     eax, [ebp+c]
                mov     ecx, [ebp+d]
                add     eax, ecx
                mov     [ebp+c], eax    ; MD5STEP(F3, c, d, a, b, in[15] + 0x1fa27cf8, 16);
                mov     eax, [ebp+c]    ; F3(x, y, z) = (x ^ y ^ z)
                mov     ecx, [ebp+d]    ; y
                xor     eax, ecx
                mov     ecx, [ebp+a]    ; z
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 8          ; in[2]
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 0C4AC5665h
                mov     ecx, [ebp+b]
                add     ecx, eax        ; w += f(x, y, z) + data
                mov     [ebp+b], ecx
                mov     eax, [ebp+b]
                shl     eax, 23
                mov     ecx, [ebp+b]
                shr     ecx, 9
                or      eax, ecx
                mov     [ebp+b], eax    ; w = w<<s | w>>(32-s)
                mov     eax, [ebp+b]
                mov     ecx, [ebp+c]    ; x
                add     eax, ecx        ; w += x
                mov     [ebp+b], eax    ; MD5STEP(F3, b, c, d, a, in[2] + 0xc4ac5665, 23);
                mov     eax, [ebp+d]
                xor     eax, 0FFFFFFFFh
                mov     ecx, [ebp+b]
                or      ecx, eax
                mov     eax, [ebp+c]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 0F4292244h
                mov     ecx, [ebp+a]
                add     ecx, eax
                mov     [ebp+a], ecx
                mov     eax, [ebp+a]
                shl     eax, 6
                mov     ecx, [ebp+a]
                shr     ecx, 26
                or      eax, ecx
                mov     [ebp+a], eax
                mov     eax, [ebp+a]
                mov     ecx, [ebp+b]
                add     eax, ecx
                mov     [ebp+a], eax    ; MD5STEP(F4, a, b, c, d, in[0] + 0xf4292244, 6);
                mov     eax, [ebp+c]
                xor     eax, 0FFFFFFFFh
                mov     ecx, [ebp+a]
                or      ecx, eax
                mov     eax, [ebp+b]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 28
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 432AFF97h
                mov     ecx, [ebp+d]
                add     ecx, eax
                mov     [ebp+d], ecx
                mov     eax, [ebp+d]
                shl     eax, 10
                mov     ecx, [ebp+d]
                shr     ecx, 22
                or      eax, ecx
                mov     [ebp+d], eax
                mov     eax, [ebp+d]
                mov     ecx, [ebp+a]
                add     eax, ecx
                mov     [ebp+d], eax    ; MD5STEP(F4, d, a, b, c, in[7] + 0x432aff97, 10);
                mov     eax, [ebp+b]
                xor     eax, 0FFFFFFFFh
                mov     ecx, [ebp+d]
                or      ecx, eax
                mov     eax, [ebp+a]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 56
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 0AB9423A7h
                mov     ecx, [ebp+c]
                add     ecx, eax
                mov     [ebp+c], ecx
                mov     eax, [ebp+c]
                shl     eax, 15
                mov     ecx, [ebp+c]
                shr     ecx, 17
                or      eax, ecx
                mov     [ebp+c], eax
                mov     eax, [ebp+c]
                mov     ecx, [ebp+d]
                add     eax, ecx
                mov     [ebp+c], eax    ; MD5STEP(F4, c, d, a, b, in[14] + 0xab9423a7, 15);
                mov     eax, [ebp+a]
                xor     eax, 0FFFFFFFFh
                mov     ecx, [ebp+c]
                or      ecx, eax
                mov     eax, [ebp+d]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 20
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 0FC93A039h
                mov     ecx, [ebp+b]
                add     ecx, eax
                mov     [ebp+b], ecx
                mov     eax, [ebp+b]
                shl     eax, 21
                mov     ecx, [ebp+b]
                shr     ecx, 11
                or      eax, ecx
                mov     [ebp+b], eax
                mov     eax, [ebp+b]
                mov     ecx, [ebp+c]
                add     eax, ecx
                mov     [ebp+b], eax    ; MD5STEP(F4, b, c, d, a, in[5] + 0xfc93a039, 21);
                mov     eax, [ebp+d]
                xor     eax, 0FFFFFFFFh
                mov     ecx, [ebp+b]
                or      ecx, eax
                mov     eax, [ebp+c]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 48
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 655B59C3h
                mov     ecx, [ebp+a]
                add     ecx, eax
                mov     [ebp+a], ecx
                mov     eax, [ebp+a]
                shl     eax, 6
                mov     ecx, [ebp+a]
                shr     ecx, 26
                or      eax, ecx
                mov     [ebp+a], eax
                mov     eax, [ebp+a]
                mov     ecx, [ebp+b]
                add     eax, ecx
                mov     [ebp+a], eax    ; MD5STEP(F4, a, b, c, d, in[12] + 0x655b59c3, 6);
                mov     eax, [ebp+c]
                xor     eax, 0FFFFFFFFh
                mov     ecx, [ebp+a]
                or      ecx, eax
                mov     eax, [ebp+b]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 12
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 8F0CCC92h
                mov     ecx, [ebp+d]
                add     ecx, eax
                mov     [ebp+d], ecx
                mov     eax, [ebp+d]
                shl     eax, 10
                mov     ecx, [ebp+d]
                shr     ecx, 22
                or      eax, ecx
                mov     [ebp+d], eax
                mov     eax, [ebp+d]
                mov     ecx, [ebp+a]
                add     eax, ecx
                mov     [ebp+d], eax    ; MD5STEP(F4, d, a, b, c, in[3] + 0x8f0ccc92, 10);
                mov     eax, [ebp+b]
                xor     eax, 0FFFFFFFFh
                mov     ecx, [ebp+d]
                or      ecx, eax
                mov     eax, [ebp+a]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 40
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 0FFEFF47Dh
                mov     ecx, [ebp+c]
                add     ecx, eax
                mov     [ebp+c], ecx
                mov     eax, [ebp+c]
                shl     eax, 15
                mov     ecx, [ebp+c]
                shr     ecx, 17
                or      eax, ecx
                mov     [ebp+c], eax
                mov     eax, [ebp+c]
                mov     ecx, [ebp+d]
                add     eax, ecx
                mov     [ebp+c], eax    ; MD5STEP(F4, c, d, a, b, in[10] + 0xffeff47d, 15);
                mov     eax, [ebp+a]
                xor     eax, 0FFFFFFFFh
                mov     ecx, [ebp+c]
                or      ecx, eax
                mov     eax, [ebp+d]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 4
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 85845DD1h
                mov     ecx, [ebp+b]
                add     ecx, eax
                mov     [ebp+b], ecx    ; MD5STEP(F4, b, c, d, a, in[1] + 0x85845dd1, 21);
                mov     eax, [ebp+b]
                shl     eax, 21
                mov     ecx, [ebp+b]
                shr     ecx, 11
                or      eax, ecx
                mov     [ebp+b], eax
                mov     eax, [ebp+b]
                mov     ecx, [ebp+c]
                add     eax, ecx
                mov     [ebp+b], eax
                mov     eax, [ebp+d]
                xor     eax, 0FFFFFFFFh
                mov     ecx, [ebp+b]
                or      ecx, eax
                mov     eax, [ebp+c]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 32
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 6FA87E4Fh
                mov     ecx, [ebp+a]
                add     ecx, eax
                mov     [ebp+a], ecx
                mov     eax, [ebp+a]
                shl     eax, 6
                mov     ecx, [ebp+a]
                shr     ecx, 26
                or      eax, ecx
                mov     [ebp+a], eax
                mov     eax, [ebp+a]
                mov     ecx, [ebp+b]
                add     eax, ecx
                mov     [ebp+a], eax    ; MD5STEP(F4, a, b, c, d, in[8] + 0x6fa87e4f, 6);
                mov     eax, [ebp+c]
                xor     eax, 0FFFFFFFFh
                mov     ecx, [ebp+a]
                or      ecx, eax
                mov     eax, [ebp+b]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 60
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 0FE2CE6E0h
                mov     ecx, [ebp+d]
                add     ecx, eax
                mov     [ebp+d], ecx
                mov     eax, [ebp+d]
                shl     eax, 10
                mov     ecx, [ebp+d]
                shr     ecx, 22
                or      eax, ecx
                mov     [ebp+d], eax
                mov     eax, [ebp+d]
                mov     ecx, [ebp+a]
                add     eax, ecx
                mov     [ebp+d], eax    ; MD5STEP(F4, d, a, b, c, in[15] + 0xfe2ce6e0, 10);
                mov     eax, [ebp+b]
                xor     eax, 0FFFFFFFFh
                mov     ecx, [ebp+d]
                or      ecx, eax
                mov     eax, [ebp+a]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 24
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 0A3014314h
                mov     ecx, [ebp+c]
                add     ecx, eax
                mov     [ebp+c], ecx
                mov     eax, [ebp+c]
                shl     eax, 15
                mov     ecx, [ebp+c]
                shr     ecx, 17
                or      eax, ecx
                mov     [ebp+c], eax
                mov     eax, [ebp+c]
                mov     ecx, [ebp+d]
                add     eax, ecx
                mov     [ebp+c], eax    ; MD5STEP(F4, c, d, a, b, in[6] + 0xa3014314, 15);
                mov     eax, [ebp+a]
                xor     eax, 0FFFFFFFFh
                mov     ecx, [ebp+c]
                or      ecx, eax
                mov     eax, [ebp+d]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 52
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 4E0811A1h
                mov     ecx, [ebp+b]
                add     ecx, eax
                mov     [ebp+b], ecx
                mov     eax, [ebp+b]
                shl     eax, 21
                mov     ecx, [ebp+b]
                shr     ecx, 11
                or      eax, ecx
                mov     [ebp+b], eax    ; MD5STEP(F4, b, c, d, a, in[13] + 0x4e0811a1, 21);
                mov     eax, [ebp+b]
                mov     ecx, [ebp+c]
                add     eax, ecx
                mov     [ebp+b], eax
                mov     eax, [ebp+d]
                xor     eax, 0FFFFFFFFh
                mov     ecx, [ebp+b]
                or      ecx, eax
                mov     eax, [ebp+c]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 16
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 0F7537E82h
                mov     ecx, [ebp+a]
                add     ecx, eax
                mov     [ebp+a], ecx
                mov     eax, [ebp+a]
                shl     eax, 6
                mov     ecx, [ebp+a]
                shr     ecx, 26
                or      eax, ecx
                mov     [ebp+a], eax
                mov     eax, [ebp+a]
                mov     ecx, [ebp+b]
                add     eax, ecx
                mov     [ebp+a], eax    ; MD5STEP(F4, a, b, c, d, in[4] + 0xf7537e82, 6);
                mov     eax, [ebp+c]
                xor     eax, 0FFFFFFFFh
                mov     ecx, [ebp+a]
                or      ecx, eax
                mov     eax, [ebp+b]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 44         ; in[11]
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 0BD3AF235h
                mov     ecx, [ebp+d]
                add     ecx, eax
                mov     [ebp+d], ecx
                mov     eax, [ebp+d]
                shl     eax, 10
                mov     ecx, [ebp+d]
                shr     ecx, 22
                or      eax, ecx
                mov     [ebp+d], eax
                mov     eax, [ebp+d]
                mov     ecx, [ebp+a]
                add     eax, ecx
                mov     [ebp+d], eax    ; MD5STEP(F4, d, a, b, c, in[11] + 0xbd3af235, 10);
                mov     eax, [ebp+b]    ; F4(x, y, z) = (y ^ (x | ~z))
                xor     eax, 0FFFFFFFFh ; ~z
                mov     ecx, [ebp+d]    ; x
                or      ecx, eax        ; |
                mov     eax, [ebp+a]    ; y
                xor     eax, ecx        ; ^
                mov     ecx, [ebp+in]
                add     ecx, 8          ; in[2]
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 2AD7D2BBh
                mov     ecx, [ebp+c]    ; w
                add     ecx, eax
                mov     [ebp+c], ecx    ; w += f(x, y, z) + data
                mov     eax, [ebp+c]
                shl     eax, 15         ; w = w<<s
                mov     ecx, [ebp+c]
                shr     ecx, 17         ; w>>(32-s) ; 32-15
                or      eax, ecx        ; w = w<<s | w>>(32-s)
                mov     [ebp+c], eax
                mov     eax, [ebp+c]
                mov     ecx, [ebp+d]
                add     eax, ecx        ; w += x
                mov     [ebp+c], eax    ; MD5STEP(F4, c, d, a, b, in[2] + 0x2ad7d2bb, 15);
                mov     eax, [ebp+a]
                xor     eax, 0FFFFFFFFh
                mov     ecx, [ebp+c]
                or      ecx, eax
                mov     eax, [ebp+d]
                xor     eax, ecx
                mov     ecx, [ebp+in]
                add     ecx, 36
                mov     edx, [ecx]
                add     eax, edx
                add     eax, 0EB86D391h
                mov     ecx, [ebp+b]
                add     ecx, eax
                mov     [ebp+b], ecx
                mov     eax, [ebp+b]
                shl     eax, 21
                mov     ecx, [ebp+b]
                shr     ecx, 11
                or      eax, ecx
                mov     [ebp+b], eax
                mov     eax, [ebp+b]
                mov     ecx, [ebp+c]
                add     eax, ecx
                mov     [ebp+b], eax    ; MD5STEP(F4, b, c, d, a, in[9] + 0xeb86d391, 21);
                mov     eax, [ebp+buf]
                mov     ecx, [eax]
                mov     edx, [ebp+a]
                add     ecx, edx
                mov     [eax], ecx      ; buf[0] += a;
                mov     eax, [ebp+buf]
                add     eax, 4
                mov     ecx, [eax]
                mov     edx, [ebp+b]
                add     ecx, edx
                mov     [eax], ecx      ; buf[1] += b;
                mov     eax, [ebp+buf]
                add     eax, 8
                mov     ecx, [eax]
                mov     edx, [ebp+c]
                add     ecx, edx
                mov     [eax], ecx      ; buf[2] += c;
                mov     eax, [ebp+buf]
                add     eax, 12
                mov     ecx, [eax]
                mov     edx, [ebp+d]
                add     ecx, edx
                mov     [eax], ecx      ; buf[3] += d;
                leave
                retn

