; ===========================================================================
; NASM v2.14.02 - NETWIDE ASSEMBLER FOR TRDOS 386 - Erdogan Tan - 18/09/2026 
; Disassembled from "raa.c" (Dissassembler: IDA)
; NASM Syntax: Erdogan Tan
; Last Update: 27/09/2026
; ===========================================================================
; raa.asm
; -------
; This file will be included in the "nasm386.asm" file
; Inclusion order: 17

; target: NASM.PRG (flat binary)
; main assembly file: nasm386.asm
; library section: libnasm.asm
; TRDOS 386 functions: system.asm
; data section: data.asm
; bss section: bss.asm
; launcher: crt0.asm

;
; +-------------------------------------------------------------------------+
; |   This file has been generated by The Interactive Disassembler (IDA)    |
; |           Copyright (c) 2018 Hex-Rays, <support@hex-rays.com>           |
; |                            Freeware version                             |
; +-------------------------------------------------------------------------+
;

; File Name   : C:\Users\90542\OneDrive\Masaüstü\nasm_214_c_o\raa.o
; Format      : ELF for Intel 386 (Relocatable)
;
; Source File : 'raa.c'

; ===========================================================================
; CODE
; ===========================================================================

; section .text

; union intorptr {
;    int64_t i;
;    void *p;
; };

; #define RAA_BLKSHIFT 15  /* 2**this many longs allocated at once */
; #define RAA_BLKSIZE	(1 << RAA_BLKSHIFT)
; #define RAA_LAYERSHIFT 15 /* 2**this many _pointers_ allocated */
; #define RAA_LAYERSIZE	(1 << RAA_LAYERSHIFT)

; struct real_raa {
;    /*
;     * Number of layers below this one to get to the real data. 0
;     * means this structure is a leaf, holding RAA_BLKSIZE real
;     * data items; 1 and above mean it's a branch, holding
;     * RAA_LAYERSIZE pointers to the next level branch or leaf
;     * structures.
;     */
;    int layers;
;
;    /*
;     * Number of real data items spanned by one position in the
;     * `data' array at this level. This number is 0 trivially, for
;     * a leaf (level 0): for a level 1 branch it should be
;     * RAA_BLKSHIFT, and for a level 2 branch it's
;     * RAA_LAYERSHIFT+RAA_BLKSHIFT.
;     */
;    int shift;
;
;    union RAA_UNION {
;        struct RAA_LEAF {
;            union intorptr data[RAA_BLKSIZE];
;        } l;
;        struct RAA_BRANCH {
;            struct real_raa *data[RAA_LAYERSIZE];
;        } b;
;    } u;
; };

; struct RAA {
;    struct real_raa raa;
; };

; struct RAAPTR {
;    struct real_raa raa;
; };

; #define LEAFSIZ (sizeof(struct real_raa)-sizeof(RAA_UNION)+sizeof(RAA_LEAF))
; #define BRANCHSIZ (sizeof(struct real_raa)-sizeof(RAA_UNION)+sizeof(RAA_BRANCH))

; #define LAYERSHIFT(r) ( (r)->layers==0 ? RAA_BLKSHIFT : RAA_LAYERSHIFT )

; =============== S U B R O U T I N E =======================================

; ---------------------------------------------------------------------------
; Function: raa_init
;
; Description:
;
; C Declaration: static inline struct RAA *never_null raa_init(void)
;
; Input (Stack): none
;
; Output [EAX]: RAA
;
; Modified Registers: EAX, (ECX), (EDX)
; ---------------------------------------------------------------------------

raa_init        proc near
                push    ebp
                mov     ebp, esp
                sub     esp, 0
                nop
                call    real_raa_init ; return (struct RAA *)real_raa_init();
                leave
                retn


; =============== S U B R O U T I N E =======================================

; ---------------------------------------------------------------------------
; Function: raa_init_ptr
;
; Description:
;
; C Declaration: static inline struct RAAPTR *never_null raa_init_ptr(void)
;
; Input (Stack): none
;
; Output [EAX]: RAAPTR
;
; Modified Registers: EAX, (ECX), (EDX)
; ---------------------------------------------------------------------------

raa_init_ptr:
                push    ebp
                mov     ebp, esp
                sub     esp, 0
                nop
                call    real_raa_init ; return (struct RAAPTR *)real_raa_init();
                leave
                retn


; =============== S U B R O U T I N E =======================================

; ---------------------------------------------------------------------------
; Function: raa_free
;
; Description:
;
; C Declaration: static inline void raa_free(struct RAA *raa)
;
; Input (Stack): [EBP+8] = *raa
;
; Output: none
;
; Modified Registers: EAX, (ECX), (EDX)
; ---------------------------------------------------------------------------

%assign raa     8

raa_free:
                push    ebp
                mov     ebp, esp
                sub     esp, 0
                nop
                mov     eax, [ebp+raa]
                push    eax
                call    real_raa_free  ; real_raa_free((struct real_raa *)raa);
                add     esp, 4
                leave
                retn


; =============== S U B R O U T I N E =======================================

; ---------------------------------------------------------------------------
; Function: raa_free_ptr
;
; Description:
;
; C Declaration: static inline void raa_free_ptr(struct RAAPTR *raa)
;
; Input (Stack): [EBP+8] = *raa
;
; Output: none
;
; Modified Registers: EAX, (ECX), (EDX)
; ---------------------------------------------------------------------------

%assign raa     8
raa_free_ptr:
                push    ebp
                mov     ebp, esp
                sub     esp, 0
                nop
                mov     eax, [ebp+raa]
                push    eax
                call    real_raa_free  ; real_raa_free((struct real_raa *)raa);
                add     esp, 4
                leave
                retn


; =============== S U B R O U T I N E =======================================

; ---------------------------------------------------------------------------
; Function: raa_write
;
; Description:
;
; C Declaration: static inline struct RAA * never_null
;                raa_write(struct RAA *r, int32_t posn, int64_t value)
;
; Input (Stack): [EBP+8]  = *r
;                [EBP+12] = posn
;                [EBP+16] = *value
;
; Output [EAX]: RAA
;
; Modified Registers: EAX, ECX, (EDX)
; ---------------------------------------------------------------------------

%assign tmp    -8
%assign tmp_h  -4
%assign r       8
%assign posn    0Ch
%assign value   10h
%assign value_h 14h

raa_write:
                push    ebp
                mov     ebp, esp
                sub     esp, 8
                nop                     ; union intorptr {
                                        ;     int64_t i;
                                        ;     void *p;
                                        ; };
                                        ;
                                        ; union intorptr ip;
                mov     eax, [ebp+value]
                mov     ecx, [ebp+value_h]
                mov     [ebp+tmp], eax
                mov     [ebp+tmp_h], ecx
                sub     esp, 8
                mov     eax, esp        ; ip (ip.i) address
                mov     ecx, 8
                push    ecx
                lea     ecx, [ebp+tmp]  ; value address
                push    ecx
                push    eax
                call    memmove         ; ip.i = value;
                add     esp, 12
                mov     eax, [ebp+posn]
                push    eax
                mov     eax, [ebp+r]
                push    eax
                call    real_raa_write 
                        ; return (struct RAA *)real_raa_write((struct real_raa *)r, posn, ip);
                add     esp, 16
                leave
                retn


; =============== S U B R O U T I N E =======================================

; ---------------------------------------------------------------------------
; Function: raa_write_ptr
;
; Description:
;
; C Declaration: static inline struct RAAPTR * never_null
;                raa_write_ptr(struct RAAPTR *r, int32_t posn, void *value)
;
; Input (Stack): [EBP+8]  = *r
;                [EBP+12] = posn
;                [EBP+16] = *value
;
; Output [EAX]: RAAPTR
;
; Modified Registers: EAX, ECX, (EDX)
; ---------------------------------------------------------------------------

%assign tmp    -8
%assign r       8
%assign posn    0Ch
%assign value   10h

raa_write_ptr:
                push    ebp
                mov     ebp, esp
                sub     esp, 8
                nop                     ; union intorptr ip;
                mov     eax, [ebp+value]
                mov     [ebp+tmp], eax
                sub     esp, 8
                mov     eax, esp        ; ip (ip.p) address
                mov     ecx, 8
                push    ecx
                lea     ecx, [ebp+tmp]  ; value address
                push    ecx
                push    eax
                call    memmove         ; ip.p = value;
                add     esp, 12
                mov     eax, [ebp+posn]
                push    eax
                mov     eax, [ebp+r]
                push    eax
                call    real_raa_write 
                        ; return (struct RAAPTR *)real_raa_write((struct real_raa *)r, posn, ip);
                add     esp, 16
                leave
                retn


; =============== S U B R O U T I N E =======================================

; ---------------------------------------------------------------------------
; Function: raa_init_layer
;
; Description:
;
; C Declaration: static struct real_raa *raa_init_layer(int layers)
;
; Input (Stack): [EBP+8] = layers
;
; Output [EAX]: real_raa structure address
;
; Modified Registers: EAX, ECX, EDX
; ---------------------------------------------------------------------------

%assign r      -4
%assign layers  8

raa_init_layer:
                push    ebp             ; static struct real_raa *raa_init_layer(int layers)
                mov     ebp, esp        ;
                                        ; #define RAA_BLKSHIFT 15
                                        ; #define RAA_BLKSIZE (1 << RAA_BLKSHIFT)
                                        ; #define RAA_LAYERSHIFT 15
                                        ; #define RAA_LAYERSIZE (1 << RAA_LAYERSHIFT)
                sub     esp, 4
                nop                     ; struct real_raa *r;
                mov     eax, [ebp+layers]
                cmp     eax, 0          ; if (layers == 0) {
                jnz     ril_1
                mov     eax, 40008h     ; #define LEAFSIZ
                                        ; (sizeof(struct real_raa)-sizeof(RAA_UNION)+sizeof(RAA_LEAF))
                push    eax
                call    nasm_zalloc
                add     esp, 4
                mov     [ebp+r], eax    ; r = nasm_zalloc(LEAFSIZ);
                mov     eax, [ebp+r]
                add     eax, 4          ; r->shift
                mov     ecx, 0
                mov     [eax], ecx      ; r->shift = 0;
                jmp     ril_2
; ---------------------------------------------------------------------------

ril_1:                                  ; ...
                mov     eax, 20008h     ; #define BRANCHSIZ
                                        ; (sizeof(struct real_raa)-sizeof(RAA_UNION)+sizeof(RAA_BRANCH))
                                        ;
                                        ; } else {
                push    eax
                call    nasm_zalloc
                add     esp, 4
                mov     [ebp+r], eax    ; r = nasm_zalloc(BRANCHSIZ);
                mov     eax, [ebp+r]
                mov     ecx, [ebp+layers]
                mov     [eax], ecx      ; r->layers = layers;
                mov     eax, [ebp+r]
                add     eax, 4
                mov     ecx, [ebp+layers] ; #define LAYERSHIFT(r)
                                        ; ( (r)->layers==0 ? RAA_BLKSHIFT : RAA_LAYERSHIFT )
                mov     edx, 15
                imul    ecx, edx
                mov     [eax], ecx      ; r->shift = (RAA_BLKSHIFT - RAA_LAYERSHIFT) + layers * RAA_LAYERSHIFT;

ril_2:                                  ; ...
                mov     eax, [ebp+r]    ; return r;
                leave
                retn


; =============== S U B R O U T I N E =======================================

; ---------------------------------------------------------------------------
; Function: real_raa_init
;
; Description:
;
; C Declaration: struct real_raa *real_raa_init(void)
;
; Input (Stack): none
;
; Output [EAX]: real_raa structure address
;
; Modified Registers: EAX, (ECX), (EDX)
; ---------------------------------------------------------------------------

real_raa_init:
                push    ebp
                mov     ebp, esp
                sub     esp, 0
                nop
                mov     eax, 0
                push    eax
                call    raa_init_layer  ; return raa_init_layer(0);
                add     esp, 4
                leave
                retn


; =============== S U B R O U T I N E =======================================

; ---------------------------------------------------------------------------
; Function: real_raa_free
;
; Description:
;
; C Declaration: void real_raa_free(struct real_raa *r)
;
; Input (Stack): [EBP+8] = *r
;
; Output: none
;
; Modified Registers: EAX, ECX, (EDX)
; ---------------------------------------------------------------------------

%assign p      -4
%assign r       8

real_raa_free:
                push    ebp
                mov     ebp, esp
                sub     esp, 4
                nop
                mov     eax, [ebp+r]    ; if (r->layers) {
                mov     ecx, [eax]
                cmp     ecx, 0
                jz      rrf_5
                mov     eax, [ebp+r]    ; struct real_raa **p;
                add     eax, 8          ; for (p = r->u.b.data; p - r->u.b.data < RAA_LAYERSIZE; p++)
                mov     [ebp+p], eax

rrf_1:                                  ; ...
                mov     eax, [ebp+r]
                add     eax, 8
                mov     ecx, [ebp+p]
                sub     ecx, eax        ; p - r->u.b.data
                sar     ecx, 2
                cmp     ecx, 8000h      ; < RAA_LAYERSIZE
                jge     rrf_5
                jmp     rrf_3
; ---------------------------------------------------------------------------

rrf_2:                                  ; ...
                mov     eax, [ebp+p]    ; p++
                mov     ecx, eax
                add     eax, 4
                mov     [ebp+p], eax
                jmp     short rrf_1
; ---------------------------------------------------------------------------

rrf_3:                                  ; ...
                mov     eax, [ebp+p]
                mov     ecx, [eax]
                cmp     ecx, 0          ; if (*p)
                jz      rrf_4
                mov     eax, [ebp+p]
                mov     ecx, [eax]
                push    ecx
                call    real_raa_free   ; real_raa_free(*p);
                add     esp, 4

rrf_4:                                  ; ...
                jmp     short rrf_2
; ---------------------------------------------------------------------------

rrf_5:                                  ; ...
                mov     eax, [ebp+r]
                push    eax
                call    nasm_free       ; nasm_free(r);
                add     esp, 4
                leave
                retn


; =============== S U B R O U T I N E =======================================

; ---------------------------------------------------------------------------
; Function: real_raa_read
;
; Description:
;
; C Declaration: static const union intorptr
;                *real_raa_read(struct real_raa *r, int32_t posn)
;
; Input (Stack): [EBP+8]  = *r
;                [EBP+12] = posn
;
; Output (EAX): real_raa ptr address (&r->u.l.data[posn])
;
; Modified Registers: EAX, ECX, EDX
; ---------------------------------------------------------------------------

%assign tmp3   -10h
%assign tmp2   -0Ch
%assign l      -8
%assign tmp1   -4
%assign r       8
%assign posn    0Ch

real_raa_read:
                push    ebp
                mov     ebp, esp
                sub     esp, 16
                nop
                mov     eax, [ebp+r]
                add     eax, 4
                mov     ecx, [ebp+r]    ; r->shift
                mov     edx, [ecx]      ; r->layers
                cmp     edx, 0          ; #define LAYERSHIFT(r)
                                        ; ( (r)->layers==0 ? RAA_BLKSHIFT : RAA_LAYERSHIFT )
                mov     ecx, 0
                setz    cl
                mov     [ebp+tmp1], eax
                cmp     ecx, 0
                jz      rrr_1
                jmp     rrr_2
; ---------------------------------------------------------------------------

rrr_1:                                  ; ...
                mov     eax, 15         ; RAA_BLKSHIFT
                jmp     rrr_3
; ---------------------------------------------------------------------------

rrr_2:                                  ; ...
                mov     eax, 15         ; RAA_LAYERSHIFT

rrr_3:                                  ; ...
                mov     ecx, [ebp+tmp1] ; (UINT32_C(1) << (r->shift + LAYERSHIFT(r))
                mov     ecx, [ecx]
                add     ecx, eax
                mov     eax, 1
                shl     eax, cl
                mov     ecx, [ebp+posn]
                cmp     ecx, eax        ; if ((uint32_t) posn >= (UINT32_C(1) << (r->shift + LAYERSHIFT(r))))
                jb      rrr_4
                mov     eax, 0          ; return NULL; /* Beyond the end */
                jmp     rrr_8
; ---------------------------------------------------------------------------

rrr_4:                                  ; ...
                mov     eax, [ebp+r]    ; while (r->layers > 0) {
                mov     ecx, [eax]
                cmp     ecx, 0
                jle     rrr_7
                mov     eax, [ebp+r]
                add     eax, 4
                mov     ecx, [ebp+posn] ; int32_t l = posn >> r->shift;
                mov     [ebp+tmp2], ecx
                mov     ecx, [eax]
                mov     eax, [ebp+tmp2]
                sar     eax, cl
                mov     [ebp+l], eax
                mov     eax, [ebp+r]
                add     eax, 4          ; r->shift address
                mov     ecx, 1
                mov     [ebp+tmp3], ecx ; 1 ; UINT32_C(1)
                mov     ecx, [eax]      ; r->shift value
                mov     eax, [ebp+tmp3]
                shl     eax, cl         ; UINT32_C(1) << r->shift
                dec     eax
                mov     ecx, [ebp+posn] ; posn &= (UINT32_C(1) << r->shift) - 1;
                and     ecx, eax
                mov     [ebp+posn], ecx
                mov     eax, [ebp+r]    ; r = r->u.b.data[l];
                add     eax, 8
                mov     ecx, [ebp+l]
                shl     ecx, 2
                add     eax, ecx
                mov     ecx, [eax]
                mov     [ebp+r], ecx
                mov     eax, [ebp+r]
                cmp     eax, 0          ; if (!r)
                jz      rrr_5
                jmp     rrr_6
; ---------------------------------------------------------------------------

rrr_5:                                  ; ...
                mov     eax, 0          ; return NULL; /* Not present */
                jmp     rrr_8
; ---------------------------------------------------------------------------

rrr_6:                                  ; ...
                jmp     short rrr_4     ; (while)
; ---------------------------------------------------------------------------

rrr_7:                                  ; ...
                mov     eax, [ebp+r]    ; return &r->u.l.data[posn];
                add     eax, 8
                mov     ecx, [ebp+posn]
                shl     ecx, 3
                add     eax, ecx

rrr_8:                                  ; ...
                leave
                retn


; =============== S U B R O U T I N E =======================================

; ---------------------------------------------------------------------------
; Function: raa_read
;
; Description:
;
; C Declaration: int64_t raa_read(struct RAA *r, int32_t pos)
;
; Input (Stack): [EBP+8]  = *r
;                [EBP+12] = pos
;
; Output (EDX:EAX): real_raa address
;
; Modified Registers: EAX, ECX, EDX
; ---------------------------------------------------------------------------

%assign tmp    -8
%assign iop    -4
%assign r       8
%assign pos     0Ch

raa_read:
                push    ebp
                mov     ebp, esp
                sub     esp, 8          ; const union intorptr *ip;
                nop
                mov     eax, [ebp+pos]
                push    eax
                mov     eax, [ebp+r]
                push    eax
                call    real_raa_read
                add     esp, 8
                mov     [ebp+iop], eax  ; ip = real_raa_read((struct real_raa *)r, pos);
                mov     eax, [ebp+iop]
                cmp     eax, 0          ; return ip ? ip->i : 0;
                jz      rr_1
                mov     eax, [ebp+iop]
                jmp     rr_2
; ---------------------------------------------------------------------------

rr_1:                                   ; ...
                mov     eax, 0
                mov     edx, 0
                jmp     rr_3
; ---------------------------------------------------------------------------

rr_2:                                   ; ...
                mov     [ebp+tmp], eax
                mov     eax, [ebp+tmp]
                mov     eax, [eax]      ; ip->i
                mov     ecx, [ebp+tmp]
                add     ecx, 4
                mov     edx, [ecx]      ; ip->i_h

rr_3:                                   ; ...
                leave
                retn


; =============== S U B R O U T I N E =======================================

; ---------------------------------------------------------------------------
; Function: raa_read_ptr
;
; Description:
;
; C Declaration: void *raa_read_ptr(struct RAAPTR *r, int32_t pos)
;
; Input (Stack): [EBP+8]  = *r
;                [EBP+12] = pos
;
; Output: none
;
; Modified Registers: EAX, ECX, (EDX)
; ---------------------------------------------------------------------------

%assign iop    -4
%assign r       8
%assign pos     0Ch

raa_read_ptr:
                push    ebp
                mov     ebp, esp
                sub     esp, 4
                nop                     ; const union intorptr *ip;
                mov     eax, [ebp+pos]
                push    eax
                mov     eax, [ebp+r]
                push    eax
                call    real_raa_read
                add     esp, 8
                mov     [ebp+iop], eax  ; ip = real_raa_read((struct real_raa *)r, pos);
                mov     eax, [ebp+iop]
                cmp     eax, 0          ; return ip ? ip->p : NULL;
                jz      rrp_1
                mov     eax, [ebp+iop]
                jmp     rrp_2
; ---------------------------------------------------------------------------

rrp_1:                                  ; ...
                mov     eax, 0
                jmp     rrp_3
; ---------------------------------------------------------------------------

rrp_2:                                  ; ...
                mov     ecx, [eax]
                mov     eax, ecx

rrp_3:                                  ; ...
                leave
                retn


; =============== S U B R O U T I N E =======================================

; ---------------------------------------------------------------------------
; Function: real_raa_write
;
; Description:
;
; C Declaration: struct real_raa *
;      real_raa_write(struct real_raa *r, int32_t posn, union intorptr value)
;
; Input (Stack): [EBP+8]  = *r
;                [EBP+12] = posn
;                [EBP+16] = value
;
; Output (EAX): real_raa address
;
; Modified Registers: EAX, ECX, EDX
; ---------------------------------------------------------------------------

%assign tmp5   -24h
%assign tmp4   -20h
%assign tmp3   -1Ch
%assign l      -18h
%assign sr     -14h
%assign tmp2   -10h
%assign s      -0Ch
%assign tmp1   -8
%assign result -4
%assign r       8
%assign posn    0Ch
%assign value   10h

real_raa_write:
                push    ebp
                mov     ebp, esp
                sub     esp, 36
                nop                     ; struct real_raa *result;
                mov     eax, [ebp+posn]
                cmp     eax, 0          ; nasm_assert(posn >= 0);
                jge     rrw_1
                mov     eax, L_198      ; "posn >= 0"
                push    eax
                mov     eax, 160        ; (raa.c line 160)
                push    eax
                mov     eax, L_197      ; "raa.c"
                push    eax
                call    nasm_assert_failed
                add     esp, 12

rrw_1:                                  ; ...
                mov     eax, [ebp+r]    ; while ((UINT32_C(1) << (r->shift + LAYERSHIFT(r))) <= (uint32_t) posn) {
                add     eax, 4          ; r->shift
                mov     ecx, [ebp+r]    ; #define LAYERSHIFT(r)
                                        ; ( (r)->layers==0 ? RAA_BLKSHIFT : RAA_LAYERSHIFT )
                mov     edx, [ecx]      ; #define RAA_BLKSHIFT 15
                                        ; #define RAA_LAYERSHIFT 15
                cmp     edx, 0
                mov     ecx, 0          ; /* Must add a layer. */
                setz    cl
                mov     [ebp+tmp1], eax
                cmp     ecx, 0
                jz      rrw_2
                jmp     rrw_3
; ---------------------------------------------------------------------------

rrw_2:                                  ; ...
                mov     eax, 15         ; RAA_BLKSHIFT (left side)
                jmp     rrw_4
; ---------------------------------------------------------------------------

rrw_3:                                  ; ...
                mov     eax, 15         ; RAA_LAYERSHIFT (right side)

rrw_4:                                  ; ...
                mov     ecx, [ebp+tmp1]
                mov     ecx, [ecx]      ; (r->shift + LAYERSHIFT(r))
                add     ecx, eax
                mov     eax, 1          ; UINT32_C(1)
                shl     eax, cl         ; (UINT32_C(1) << (r->shift + LAYERSHIFT(r))
                mov     ecx, [ebp+posn]
                cmp     eax, ecx        ; <= (uint32_t) posn
                ja      rrw_8
                mov     eax, 20008h     ; BRANCHSIZ
                push    eax
                call    nasm_zalloc
                add     esp, 4          ; struct real_raa *s;
                mov     [ebp+s], eax    ; s = nasm_zalloc(BRANCHSIZ);
                mov     eax, [ebp+s]
                mov     ecx, [ebp+r]
                mov     edx, [ecx]
                inc     edx
                mov     [eax], edx      ; s->layers = r->layers + 1;
                mov     eax, [ebp+s]
                add     eax, 4
                mov     ecx, [ebp+r]
                mov     edx, [ecx]
                cmp     edx, 0
                mov     ecx, 0
                setz    cl
                mov     [ebp+tmp2], eax ; s->shift address
                cmp     ecx, 0
                jz      rrw_5
                jmp     rrw_6
; ---------------------------------------------------------------------------

rrw_5:                                  ; ...
                mov     eax, 15         ; RAA_BLKSHIFT
                jmp     rrw_7
; ---------------------------------------------------------------------------

rrw_6:                                  ; ...
                mov     eax, 15         ; RAA_LAYERSHIFT

rrw_7:                                  ; ...
                mov     ecx, [ebp+r]
                add     ecx, 4
                mov     edx, [ecx]      ; r->shift
                add     eax, edx        ; + LAYERSHIFT(r)
                mov     ecx, [ebp+tmp2] ; s->shift
                mov     [ecx], eax      ; s->shift = LAYERSHIFT(r) + r->shift;
                mov     eax, [ebp+s]
                add     eax, 8
                mov     ecx, [ebp+r]
                mov     [eax], ecx      ; s->u.b.data[0] = r;
                mov     eax, [ebp+s]
                mov     [ebp+r], eax    ; r = s;
                jmp     rrw_1
; ---------------------------------------------------------------------------

rrw_8:                                  ; ...
                mov     eax, [ebp+r]
                mov     [ebp+result], eax ; result = r;

rrw_9:                                  ; ...
                mov     eax, [ebp+r]    ; while (r->layers > 0) {
                mov     ecx, [eax]
                cmp     ecx, 0
                jle     rrw_12
                mov     eax, [ebp+r]    ; struct real_raa **s;
                add     eax, 4          ; r->shift address
                mov     ecx, [ebp+posn]
                mov     [ebp+tmp3], ecx
                mov     ecx, [eax]      ; r->shift value
                mov     eax, [ebp+tmp3]
                sar     eax, cl
                mov     [ebp+l], eax    ; int32_t l = posn >> r->shift;
                mov     eax, [ebp+r]
                add     eax, 4
                mov     ecx, 1
                mov     [ebp+tmp4], ecx
                mov     ecx, [eax]      ; r->shift
                mov     eax, [ebp+tmp4] ; UINT32_C(1)
                shl     eax, cl         ; UINT32_C(1) << r->shift
                dec     eax             ; -1
                mov     ecx, [ebp+posn]
                and     ecx, eax
                mov     [ebp+posn], ecx ; posn &= (UINT32_C(1) << r->shift) - 1;
                mov     eax, [ebp+r]
                add     eax, 8
                mov     ecx, [ebp+l]
                shl     ecx, 2
                add     eax, ecx
                mov     [ebp+sr], eax   ; s = &r->u.b.data[l];
                mov     eax, [ebp+sr]   ; if (!*s)
                mov     ecx, [eax]
                cmp     ecx, 0
                jz      rrw_10
                jmp     rrw_11
; ---------------------------------------------------------------------------

rrw_10:                                 ; ...
                mov     eax, [ebp+sr]
                mov     ecx, [ebp+r]
                mov     edx, [ecx]
                dec     edx             ; r->layers - 1
                push    edx
                mov     [ebp+tmp5], eax
                call    raa_init_layer
                add     esp, 4
                mov     ecx, [ebp+tmp5]
                mov     [ecx], eax      ; *s = raa_init_layer(r->layers - 1);

rrw_11:                                 ; ...
                mov     eax, [ebp+sr]
                mov     ecx, [eax]
                mov     [ebp+r], ecx    ; r = *s;
                jmp     rrw_9
; ---------------------------------------------------------------------------

rrw_12:                                 ; ...
                mov     eax, [ebp+r]
                add     eax, 8
                mov     ecx, [ebp+posn]
                shl     ecx, 3
                add     eax, ecx        ; r->u.l.data[posn]
                mov     ecx, 8
                push    ecx
                lea     ecx, [ebp+value] ; value address
                push    ecx
                push    eax
                call    memmove         ; r->u.l.data[posn] = value;
                add     esp, 12
                mov     eax, [ebp+result]
                leave
                retn


; ===========================================================================
; DATA (raa.asm, raa.c)
; ===========================================================================

; section .data

; L_197:        db 'raa.c',0            ; ...
; L_198:        db 'posn >= 0',0        ; ...

