; ===========================================================================
; NASM v2.14.02 - NETWIDE ASSEMBLER FOR TRDOS 386 - Erdogan Tan - 18/09/2026 
; Disassembled from "realpath.c" (Dissassembler: IDA)
; NASM Syntax: Erdogan Tan
; Last Update: 25/09/2026
; ===========================================================================
; realpath.asm
; ------------
; This file will be included in the "nasm386.asm" file
; Inclusion order: 9

; target: NASM.PRG (flat binary)
; main assembly file: nasm386.asm
; library section: libnasm.asm
; TRDOS 386 functions: system.asm 
; data section: data.asm
; bss section: bss.asm
; launcher: crt0.asm

;
; +-------------------------------------------------------------------------+
; |   This file has been generated by The Interactive Disassembler (IDA)    |
; |           Copyright (c) 2018 Hex-Rays, <support@hex-rays.com>           |
; |                            Freeware version                             |
; +-------------------------------------------------------------------------+
;

; File Name   : C:\Users\90542\OneDrive\Masaüstü\nasm_214_c_o\realpath.o
; Format      : ELF for Intel 386 (Relocatable)
;
; Source File : 'realpath.c'

; ===========================================================================
; CODE
; ===========================================================================

; section .text

; =============== S U B R O U T I N E =======================================

; ---------------------------------------------------------------------------
; Function: nasm_realpath
;
; Description:
;
; C Declaration: char *nasm_realpath(const char *rel_path)
;
; Input (Stack): [EBP+8] = *rel_path
;
; Output (EAX): real path address
;
; Modified Registers: EAX
; ---------------------------------------------------------------------------

%assign rel_path 8

nasm_realpath:
                push    ebp
                mov     ebp, esp
                sub     esp, 0
                nop
                mov     eax, [ebp+rel_path]
                push    eax
                call    nasm_strdup     ; return nasm_strdup(rel_path);
                add     esp, 4
                leave
                retn

