; NASM 2.14.02 port to TRDOS 386 (Beginning: 18/09/2026)
; ---------------------------------------------------------------------------
; NASM Syntax: Erdogan Tan
; Last Update: 07/10/2026
; ===========================================================================
; regflags.asm

; target: NASM.PRG (flat binary)
; main assembly file: nasm386.asm
; library section: libnasm.asm
; TRDOS 386 functions: system.asm 
; data section: data.asm
; bss section: bss.asm
; launcher: crt0.asm

; Source File : 'regflags.c'

; const opflags_t nasm_reg_flags[] = {

nasm_reg_flags:
    dq 0
    dq REG_HIGH  ; ah
    dq REG_AL    ; al
    dq REG_AX    ; ax
    dq REG_HIGH  ; bh
    dq REG8NA    ; bl
    dq BNDREG    ; bnd0
    dq BNDREG    ; bnd1
    dq BNDREG    ; bnd2
    dq BNDREG    ; bnd3
    dq REG16NA   ; bp
    dq REG8NA    ; bpl
    dq REG16NA   ; bx
    dq REG_HIGH  ; ch
    dq REG_CL    ; cl
    dq REG_CREG  ; cr0
    dq REG_CREG  ; cr1
    dq REG_CREG  ; cr10
    dq REG_CREG  ; cr11
    dq REG_CREG  ; cr12
    dq REG_CREG  ; cr13
    dq REG_CREG  ; cr14
    dq REG_CREG  ; cr15
    dq REG_CREG  ; cr2
    dq REG_CREG  ; cr3
    dq REG_CREG  ; cr4
    dq REG_CREG  ; cr5
    dq REG_CREG  ; cr6
    dq REG_CREG  ; cr7
    dq REG_CREG  ; cr8
    dq REG_CREG  ; cr9
    dq REG_CS    ; cs
    dq REG_CX    ; cx
    dq REG_HIGH  ; dh
    dq REG16NA   ; di
    dq REG8NA    ; dil
    dq REG_DL    ; dl
    dq REG_DREG  ; dr0
    dq REG_DREG  ; dr1
    dq REG_DREG  ; dr10
    dq REG_DREG  ; dr11
    dq REG_DREG  ; dr12
    dq REG_DREG  ; dr13
    dq REG_DREG  ; dr14
    dq REG_DREG  ; dr15
    dq REG_DREG  ; dr2
    dq REG_DREG  ; dr3
    dq REG_DREG  ; dr4
    dq REG_DREG  ; dr5
    dq REG_DREG  ; dr6
    dq REG_DREG  ; dr7
    dq REG_DREG  ; dr8
    dq REG_DREG  ; dr9
    dq REG_DS    ; ds
    dq REG_DX    ; dx
    dq REG_EAX   ; eax
    dq REG32NA   ; ebp
    dq REG32NA   ; ebx
    dq REG_ECX   ; ecx
    dq REG32NA   ; edi
    dq REG_EDX   ; edx
    dq REG_ES    ; es
    dq REG32NA   ; esi
    dq REG32NA   ; esp
    dq REG_FS    ; fs
    dq REG_GS    ; gs
    dq OPMASK0   ; k0
    dq OPMASKREG ; k1
    dq OPMASKREG ; k2
    dq OPMASKREG ; k3
    dq OPMASKREG ; k4
    dq OPMASKREG ; k5
    dq OPMASKREG ; k6
    dq OPMASKREG ; k7
    dq MMXREG    ; mm0
    dq MMXREG    ; mm1
    dq MMXREG    ; mm2
    dq MMXREG    ; mm3
    dq MMXREG    ; mm4
    dq MMXREG    ; mm5
    dq MMXREG    ; mm6
    dq MMXREG    ; mm7
    dq REG64NA   ; r10
    dq REG8NA    ; r10b
    dq REG32NA   ; r10d
    dq REG16NA   ; r10w
    dq REG64NA   ; r11
    dq REG8NA    ; r11b
    dq REG32NA   ; r11d
    dq REG16NA   ; r11w
    dq REG64NA   ; r12
    dq REG8NA    ; r12b
    dq REG32NA   ; r12d
    dq REG16NA   ; r12w
    dq REG64NA   ; r13
    dq REG8NA    ; r13b
    dq REG32NA   ; r13d
    dq REG16NA   ; r13w
    dq REG64NA   ; r14
    dq REG8NA    ; r14b
    dq REG32NA   ; r14d
    dq REG16NA   ; r14w
    dq REG64NA   ; r15
    dq REG8NA    ; r15b
    dq REG32NA   ; r15d
    dq REG16NA   ; r15w
    dq REG64NA   ; r8
    dq REG8NA    ; r8b
    dq REG32NA   ; r8d
    dq REG16NA   ; r8w
    dq REG64NA   ; r9
    dq REG8NA    ; r9b
    dq REG32NA   ; r9d
    dq REG16NA   ; r9w
    dq REG_RAX   ; rax
    dq REG64NA   ; rbp
    dq REG64NA   ; rbx
    dq REG_RCX   ; rcx
    dq REG64NA   ; rdi
    dq REG_RDX   ; rdx
    dq REG64NA   ; rsi
    dq REG64NA   ; rsp
    dq REG_SEG67 ; segr6
    dq REG_SEG67 ; segr7
    dq REG16NA   ; si
    dq REG8NA    ; sil
    dq REG16NA   ; sp
    dq REG8NA    ; spl
    dq REG_SS    ; ss
    dq FPU0      ; st0
    dq FPUREG    ; st1
    dq FPUREG    ; st2
    dq FPUREG    ; st3
    dq FPUREG    ; st4
    dq FPUREG    ; st5
    dq FPUREG    ; st6
    dq FPUREG    ; st7
    dq REG_TREG  ; tr0
    dq REG_TREG  ; tr1
    dq REG_TREG  ; tr2
    dq REG_TREG  ; tr3
    dq REG_TREG  ; tr4
    dq REG_TREG  ; tr5
    dq REG_TREG  ; tr6
    dq REG_TREG  ; tr7
    dq XMM0      ; xmm0
    dq XMM_L16   ; xmm1
    dq XMM_L16   ; xmm10
    dq XMM_L16   ; xmm11
    dq XMM_L16   ; xmm12
    dq XMM_L16   ; xmm13
    dq XMM_L16   ; xmm14
    dq XMM_L16   ; xmm15
    dq XMMREG    ; xmm16
    dq XMMREG    ; xmm17
    dq XMMREG    ; xmm18
    dq XMMREG    ; xmm19
    dq XMM_L16   ; xmm2
    dq XMMREG    ; xmm20
    dq XMMREG    ; xmm21
    dq XMMREG    ; xmm22
    dq XMMREG    ; xmm23
    dq XMMREG    ; xmm24
    dq XMMREG    ; xmm25
    dq XMMREG    ; xmm26
    dq XMMREG    ; xmm27
    dq XMMREG    ; xmm28
    dq XMMREG    ; xmm29
    dq XMM_L16   ; xmm3
    dq XMMREG    ; xmm30
    dq XMMREG    ; xmm31
    dq XMM_L16   ; xmm4
    dq XMM_L16   ; xmm5
    dq XMM_L16   ; xmm6
    dq XMM_L16   ; xmm7
    dq XMM_L16   ; xmm8
    dq XMM_L16   ; xmm9
    dq YMM0      ; ymm0
    dq YMM_L16   ; ymm1
    dq YMM_L16   ; ymm10
    dq YMM_L16   ; ymm11
    dq YMM_L16   ; ymm12
    dq YMM_L16   ; ymm13
    dq YMM_L16   ; ymm14
    dq YMM_L16   ; ymm15
    dq YMMREG    ; ymm16
    dq YMMREG    ; ymm17
    dq YMMREG    ; ymm18
    dq YMMREG    ; ymm19
    dq YMM_L16   ; ymm2
    dq YMMREG    ; ymm20
    dq YMMREG    ; ymm21
    dq YMMREG    ; ymm22
    dq YMMREG    ; ymm23
    dq YMMREG    ; ymm24
    dq YMMREG    ; ymm25
    dq YMMREG    ; ymm26
    dq YMMREG    ; ymm27
    dq YMMREG    ; ymm28
    dq YMMREG    ; ymm29
    dq YMM_L16   ; ymm3
    dq YMMREG    ; ymm30
    dq YMMREG    ; ymm31
    dq YMM_L16   ; ymm4
    dq YMM_L16   ; ymm5
    dq YMM_L16   ; ymm6
    dq YMM_L16   ; ymm7
    dq YMM_L16   ; ymm8
    dq YMM_L16   ; ymm9
    dq ZMM0      ; zmm0
    dq ZMM_L16   ; zmm1
    dq ZMM_L16   ; zmm10
    dq ZMM_L16   ; zmm11
    dq ZMM_L16   ; zmm12
    dq ZMM_L16   ; zmm13
    dq ZMM_L16   ; zmm14
    dq ZMM_L16   ; zmm15
    dq ZMMREG    ; zmm16
    dq ZMMREG    ; zmm17
    dq ZMMREG    ; zmm18
    dq ZMMREG    ; zmm19
    dq ZMM_L16   ; zmm2
    dq ZMMREG    ; zmm20
    dq ZMMREG    ; zmm21
    dq ZMMREG    ; zmm22
    dq ZMMREG    ; zmm23
    dq ZMMREG    ; zmm24
    dq ZMMREG    ; zmm25
    dq ZMMREG    ; zmm26
    dq ZMMREG    ; zmm27
    dq ZMMREG    ; zmm28
    dq ZMMREG    ; zmm29
    dq ZMM_L16   ; zmm3
    dq ZMMREG    ; zmm30
    dq ZMMREG    ; zmm31
    dq ZMM_L16   ; zmm4
    dq ZMM_L16   ; zmm5
    dq ZMM_L16   ; zmm6
    dq ZMM_L16   ; zmm7
    dq ZMM_L16   ; zmm8
    dq ZMM_L16   ; zmm9

; };
