

;
; +-------------------------------------------------------------------------+
; |   This file has been generated by The Interactive Disassembler (IDA)    |
; |           Copyright (c) 2018 Hex-Rays, <support@hex-rays.com>           |
; |                            Freeware version                             |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : BB9F70B63B43937819CD53F0262742527861A9C05D1E36C3B85DFF6319BEC2D9
; Input MD5    : D1C678FD886D6E3550E9D9C770171E03
; Input CRC32  : C07078A3

; File Name   : C:\Users\90542\OneDrive\Masaüstü\file_tcc.o
; Format      : ELF for Intel 386 (Relocatable)
;
; Source File : 'file.c'

                .686p
                .mmx
                .model flat
.intel_syntax noprefix

; ===========================================================================

; Segment type: Pure code
; Segment permissions: Read/Execute
; Segment alignment '32byte' can not be represented in assembly
_text           segment para public 'CODE' use32
                assume cs:_text
                ;org 8000000h
                assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing

; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

                public vsnprintf
vsnprintf       proc near

arg_0           = dword ptr  8
arg_4           = dword ptr  0Ch
arg_8           = dword ptr  10h
arg_C           = dword ptr  14h

                push    ebp
                mov     ebp, esp
                sub     esp, 0
                nop
                mov     eax, [ebp+arg_C]
                push    eax
                mov     eax, [ebp+arg_8]
                push    eax
                mov     eax, [ebp+arg_4]
                push    eax
                mov     eax, [ebp+arg_0]
                push    eax
                call    _vsnprintf
                add     esp, 10h
                jmp     $+5
; ---------------------------------------------------------------------------

locret_8000027:                         ; ...
                leave
                retn
vsnprintf       endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

                public vsnwprintf
vsnwprintf      proc near

arg_0           = dword ptr  8
arg_4           = dword ptr  0Ch
arg_8           = dword ptr  10h
arg_C           = dword ptr  14h

                push    ebp
                mov     ebp, esp
                sub     esp, 0
                nop
                mov     eax, [ebp+arg_C]
                push    eax
                mov     eax, [ebp+arg_8]
                push    eax
                mov     eax, [ebp+arg_4]
                push    eax
                mov     eax, [ebp+arg_0]
                push    eax
                call    _vsnwprintf
                add     esp, 10h
                jmp     $+5
; ---------------------------------------------------------------------------

locret_8000050:                         ; ...
                leave
                retn
vsnwprintf      endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

overflow_general proc near

var_3C          = dword ptr -3Ch
var_38          = dword ptr -38h
var_34          = dword ptr -34h
var_30          = dword ptr -30h
var_2C          = dword ptr -2Ch
var_28          = dword ptr -28h
var_24          = dword ptr -24h
var_20          = dword ptr -20h
var_1C          = dword ptr -1Ch
var_18          = dword ptr -18h
var_14          = dword ptr -14h
var_C           = dword ptr -0Ch
var_4           = dword ptr -4
arg_0           = dword ptr  8
arg_8           = dword ptr  10h

                push    ebp
                mov     ebp, esp
                sub     esp, 3Ch
                nop
                mov     eax, [ebp+arg_8]
                cmp     eax, 8
                jl      loc_8000072
                mov     eax, 0
                jmp     locret_8000194
; ---------------------------------------------------------------------------

loc_8000072:                            ; ...
                mov     eax, [ebp+arg_8]
                shl     eax, 3
                sub     eax, 1
                mov     [ebp+var_4], eax
                mov     eax, [ebp+var_4]
                push    eax
                mov     eax, 2
                mov     ecx, 0
                push    ecx
                push    eax
                call    __shldi3
                add     esp, 0Ch
                mov     ecx, 1
                mov     [ebp+var_18], eax
                mov     eax, 0
                mov     [ebp+var_1C], edx
                mov     edx, [ebp+var_18]
                sub     edx, ecx
                mov     ecx, [ebp+var_1C]
                sbb     ecx, eax
                mov     [ebp+var_C], edx
                lea     eax, [ebp+var_C]
                add     eax, 4
                mov     [eax], ecx
                mov     eax, [ebp+var_4]
                push    eax
                mov     eax, 2
                mov     ecx, 0
                push    ecx
                push    eax
                call    __shldi3
                add     esp, 0Ch
                mov     ecx, 0
                mov     [ebp+var_24], eax
                mov     [ebp+var_20], edx
                mov     eax, 0
                mov     [ebp+var_28], ecx
                mov     [ebp+var_2C], eax
                mov     edx, [ebp+var_24]
                lea     eax, [ebp+var_24]
                add     eax, 4
                mov     ecx, [eax]
                mov     eax, [ebp+var_28]
                sub     eax, edx
                mov     edx, [ebp+var_2C]
                sbb     edx, ecx
                mov     [ebp+var_14], eax
                lea     ecx, [ebp+var_14]
                add     ecx, 4
                mov     [ecx], edx
                mov     eax, [ebp+arg_0]
                lea     ecx, [ebp+arg_0]
                add     ecx, 4
                mov     edx, [ecx]
                mov     [ebp+var_30], eax
                mov     [ebp+var_34], edx
                mov     ecx, [ebp+var_14]
                lea     eax, [ebp+var_14]
                add     eax, 4
                mov     edx, [eax]
                mov     eax, [ebp+var_34]
                cmp     eax, edx
                jg      loc_8000146
                jnz     loc_8000141
                mov     eax, [ebp+var_30]
                cmp     eax, ecx
                jnb     loc_8000146

loc_8000141:                            ; ...
                jmp     loc_800018A
; ---------------------------------------------------------------------------

loc_8000146:                            ; ...
                mov     eax, [ebp+arg_0]
                lea     ecx, [ebp+arg_0]
                add     ecx, 4
                mov     edx, [ecx]
                mov     [ebp+var_38], eax
                mov     [ebp+var_3C], edx
                mov     ecx, [ebp+var_C]
                lea     eax, [ebp+var_C]
                add     eax, 4
                mov     edx, [eax]
                mov     eax, [ebp+var_3C]
                cmp     eax, edx
                jl      loc_8000183
                jnz     loc_800017E
                mov     eax, [ebp+var_38]
                cmp     eax, ecx
                jbe     loc_8000183

loc_800017E:                            ; ...
                jmp     loc_800018A
; ---------------------------------------------------------------------------

loc_8000183:                            ; ...
                mov     eax, 0
                jmp     short loc_800018F
; ---------------------------------------------------------------------------

loc_800018A:                            ; ...
                mov     eax, 1

loc_800018F:                            ; ...
                jmp     $+5
; ---------------------------------------------------------------------------

locret_8000194:                         ; ...
                leave
                retn
overflow_general endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

overflow_signed proc near

var_3C          = dword ptr -3Ch
var_38          = dword ptr -38h
var_34          = dword ptr -34h
var_30          = dword ptr -30h
var_2C          = dword ptr -2Ch
var_28          = dword ptr -28h
var_24          = dword ptr -24h
var_20          = dword ptr -20h
var_1C          = dword ptr -1Ch
var_18          = dword ptr -18h
var_14          = dword ptr -14h
var_C           = dword ptr -0Ch
var_4           = dword ptr -4
arg_0           = dword ptr  8
arg_8           = dword ptr  10h

                push    ebp
                mov     ebp, esp
                sub     esp, 3Ch
                nop
                mov     eax, [ebp+arg_8]
                cmp     eax, 8
                jl      loc_80001B6
                mov     eax, 0
                jmp     locret_80002D8
; ---------------------------------------------------------------------------

loc_80001B6:                            ; ...
                mov     eax, [ebp+arg_8]
                shl     eax, 3
                sub     eax, 1
                mov     [ebp+var_4], eax
                mov     eax, [ebp+var_4]
                push    eax
                mov     eax, 1
                mov     ecx, 0
                push    ecx
                push    eax
                call    __shldi3
                add     esp, 0Ch
                mov     ecx, 1
                mov     [ebp+var_18], eax
                mov     eax, 0
                mov     [ebp+var_1C], edx
                mov     edx, [ebp+var_18]
                sub     edx, ecx
                mov     ecx, [ebp+var_1C]
                sbb     ecx, eax
                mov     [ebp+var_C], edx
                lea     eax, [ebp+var_C]
                add     eax, 4
                mov     [eax], ecx
                mov     eax, [ebp+var_4]
                push    eax
                mov     eax, 1
                mov     ecx, 0
                push    ecx
                push    eax
                call    __shldi3
                add     esp, 0Ch
                mov     ecx, 0
                mov     [ebp+var_24], eax
                mov     [ebp+var_20], edx
                mov     eax, 0
                mov     [ebp+var_28], ecx
                mov     [ebp+var_2C], eax
                mov     edx, [ebp+var_24]
                lea     eax, [ebp+var_24]
                add     eax, 4
                mov     ecx, [eax]
                mov     eax, [ebp+var_28]
                sub     eax, edx
                mov     edx, [ebp+var_2C]
                sbb     edx, ecx
                mov     [ebp+var_14], eax
                lea     ecx, [ebp+var_14]
                add     ecx, 4
                mov     [ecx], edx
                mov     eax, [ebp+arg_0]
                lea     ecx, [ebp+arg_0]
                add     ecx, 4
                mov     edx, [ecx]
                mov     [ebp+var_30], eax
                mov     [ebp+var_34], edx
                mov     ecx, [ebp+var_14]
                lea     eax, [ebp+var_14]
                add     eax, 4
                mov     edx, [eax]
                mov     eax, [ebp+var_34]
                cmp     eax, edx
                jg      loc_800028A
                jnz     loc_8000285
                mov     eax, [ebp+var_30]
                cmp     eax, ecx
                jnb     loc_800028A

loc_8000285:                            ; ...
                jmp     loc_80002CE
; ---------------------------------------------------------------------------

loc_800028A:                            ; ...
                mov     eax, [ebp+arg_0]
                lea     ecx, [ebp+arg_0]
                add     ecx, 4
                mov     edx, [ecx]
                mov     [ebp+var_38], eax
                mov     [ebp+var_3C], edx
                mov     ecx, [ebp+var_C]
                lea     eax, [ebp+var_C]
                add     eax, 4
                mov     edx, [eax]
                mov     eax, [ebp+var_3C]
                cmp     eax, edx
                jl      loc_80002C7
                jnz     loc_80002C2
                mov     eax, [ebp+var_38]
                cmp     eax, ecx
                jbe     loc_80002C7

loc_80002C2:                            ; ...
                jmp     loc_80002CE
; ---------------------------------------------------------------------------

loc_80002C7:                            ; ...
                mov     eax, 0
                jmp     short loc_80002D3
; ---------------------------------------------------------------------------

loc_80002CE:                            ; ...
                mov     eax, 1

loc_80002D3:                            ; ...
                jmp     $+5
; ---------------------------------------------------------------------------

locret_80002D8:                         ; ...
                leave
                retn
overflow_signed endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

overflow_unsigned proc near

var_2C          = dword ptr -2Ch
var_28          = dword ptr -28h
var_24          = dword ptr -24h
var_20          = dword ptr -20h
var_1C          = dword ptr -1Ch
var_18          = dword ptr -18h
var_14          = dword ptr -14h
var_C           = dword ptr -0Ch
var_4           = dword ptr -4
arg_0           = dword ptr  8
arg_8           = dword ptr  10h

                push    ebp
                mov     ebp, esp
                sub     esp, 2Ch
                nop
                mov     eax, [ebp+arg_8]
                cmp     eax, 8
                jl      loc_80002FA
                mov     eax, 0
                jmp     locret_80003E3
; ---------------------------------------------------------------------------

loc_80002FA:                            ; ...
                mov     eax, [ebp+arg_8]
                shl     eax, 3
                sub     eax, 1
                mov     [ebp+var_4], eax
                mov     eax, [ebp+var_4]
                push    eax
                mov     eax, 2
                mov     ecx, 0
                push    ecx
                push    eax
                call    __shldi3
                add     esp, 0Ch
                mov     ecx, 1
                mov     [ebp+var_18], eax
                mov     eax, 0
                mov     [ebp+var_1C], edx
                mov     edx, [ebp+var_18]
                sub     edx, ecx
                mov     ecx, [ebp+var_1C]
                sbb     ecx, eax
                mov     [ebp+var_C], edx
                lea     eax, [ebp+var_C]
                add     eax, 4
                mov     [eax], ecx
                mov     eax, 0
                mov     ecx, 0
                mov     [ebp+var_14], eax
                lea     edx, [ebp+var_14]
                add     edx, 4
                mov     [edx], ecx
                mov     eax, [ebp+arg_0]
                lea     ecx, [ebp+arg_0]
                add     ecx, 4
                mov     edx, [ecx]
                mov     [ebp+var_20], eax
                mov     [ebp+var_24], edx
                mov     ecx, [ebp+var_14]
                lea     eax, [ebp+var_14]
                add     eax, 4
                mov     edx, [eax]
                mov     eax, [ebp+var_24]
                cmp     eax, edx
                jg      loc_8000395
                jnz     loc_8000390
                mov     eax, [ebp+var_20]
                cmp     eax, ecx
                jnb     loc_8000395

loc_8000390:                            ; ...
                jmp     loc_80003D9
; ---------------------------------------------------------------------------

loc_8000395:                            ; ...
                mov     eax, [ebp+arg_0]
                lea     ecx, [ebp+arg_0]
                add     ecx, 4
                mov     edx, [ecx]
                mov     [ebp+var_28], eax
                mov     [ebp+var_2C], edx
                mov     ecx, [ebp+var_C]
                lea     eax, [ebp+var_C]
                add     eax, 4
                mov     edx, [eax]
                mov     eax, [ebp+var_2C]
                cmp     eax, edx
                jl      loc_80003D2
                jnz     loc_80003CD
                mov     eax, [ebp+var_28]
                cmp     eax, ecx
                jbe     loc_80003D2

loc_80003CD:                            ; ...
                jmp     loc_80003D9
; ---------------------------------------------------------------------------

loc_80003D2:                            ; ...
                mov     eax, 0
                jmp     short loc_80003DE
; ---------------------------------------------------------------------------

loc_80003D9:                            ; ...
                mov     eax, 1

loc_80003DE:                            ; ...
                jmp     $+5
; ---------------------------------------------------------------------------

locret_80003E3:                         ; ...
                leave
                retn
overflow_unsigned endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

nasm_set_verror proc near

var_4           = dword ptr -4
arg_0           = dword ptr  8

                push    ebp
                mov     ebp, esp
                sub     esp, 4
                nop
                mov     eax, ds:nasm_verror
                mov     [ebp+var_4], eax
                mov     eax, [ebp+arg_0]
                mov     ds:nasm_verror, eax
                mov     eax, [ebp+var_4]
                jmp     $+5
; ---------------------------------------------------------------------------

locret_8000409:                         ; ...
                leave
                retn
nasm_set_verror endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

                public nasm_read
nasm_read       proc near

n               = dword ptr -4
ptr             = dword ptr  8
size            = dword ptr  0Ch
f               = dword ptr  10h

                push    ebp
                mov     ebp, esp
                sub     esp, 4
                nop
                mov     eax, [ebp+f]    ; void nasm_read(void *ptr, size_t size, FILE *f)
                push    eax
                mov     eax, [ebp+size]
                push    eax
                mov     eax, 1
                push    eax
                mov     eax, [ebp+ptr]
                push    eax
                call    fread
                add     esp, 10h
                mov     [ebp+n], eax    ; size_t n = fread(ptr, 1, size, f);
                mov     eax, [ebp+f]
                push    eax
                call    ferror          ; if (ferror(f)) {
                add     esp, 4
                test    eax, eax
                jz      nr_1
                call    _errno
                mov     ecx, [eax]
                push    ecx
                call    strerror
                add     esp, 4
                push    eax
                mov     eax, offset L_181 ; "unable to read input: %s"
                push    eax
                mov     eax, 0
                push    eax
                call    nasm_fatal      ; nasm_fatal(0, "unable to read input: %s", strerror(errno));
                add     esp, 0Ch
                jmp     nr_3
; ---------------------------------------------------------------------------

nr_1:                                   ; ...
                mov     eax, [ebp+n]    ;  } else if (n != size || feof(f)) {
                mov     ecx, [ebp+size]
                cmp     eax, ecx
                jnz     nr_2
                mov     eax, [ebp+f]
                push    eax
                call    feof
                add     esp, 4
                test    eax, eax
                jnz     nr_2
                jmp     nr_3
; ---------------------------------------------------------------------------

nr_2:                                   ; ...
                mov     eax, offset L_182 ; "fatal short read on input"
                push    eax
                mov     eax, 0
                push    eax
                call    nasm_fatal      ; nasm_fatal(0, "fatal short read on input");
                add     esp, 8

nr_3:                                   ; ...
                leave
                retn
nasm_read       endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

                public nasm_write
nasm_write      proc near               ; ...

n               = dword ptr -4
ptr             = dword ptr  8
size            = dword ptr  0Ch
f               = dword ptr  10h

                push    ebp             ; void nasm_write(const void *ptr, size_t size, FILE *f)
                mov     ebp, esp
                sub     esp, 4
                nop
                mov     eax, [ebp+f]
                push    eax
                mov     eax, [ebp+size]
                push    eax
                mov     eax, 1
                push    eax
                mov     eax, [ebp+ptr]
                push    eax
                call    fwrite
                add     esp, 16
                mov     [ebp+n], eax    ; size_t n = fwrite(ptr, 1, size, f);
                mov     eax, [ebp+n]    ; if (n != size || ferror(f) || feof(f))
                mov     ecx, [ebp+size]
                cmp     eax, ecx
                jnz     nw_1
                mov     eax, [ebp+f]
                push    eax
                call    ferror
                add     esp, 4
                test    eax, eax
                jnz     nw_1
                mov     eax, [ebp+f]
                push    eax
                call    feof
                add     esp, 4
                test    eax, eax
                jnz     nw_1
                jmp     nw_2
; ---------------------------------------------------------------------------

nw_1:                                   ; ...
                call    _errno
                mov     ecx, [eax]
                push    ecx
                call    strerror
                add     esp, 4
                push    eax
                mov     eax, offset L_183 ; "unable to write output: %s"
                push    eax
                mov     eax, 0
                push    eax
                call    nasm_fatal      ; nasm_fatal(0, "unable to write output: %s", strerror(errno));
                add     esp, 12

nw_2:                                   ; ...
                leave
                retn
nasm_write      endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

                public fwriteint16_t
fwriteint16_t   proc near

data            = word ptr  8
fp              = dword ptr  0Ch

                push    ebp
                mov     ebp, esp
                sub     esp, 0
                nop
                movzx   eax, [ebp+data]
                mov     [ebp+data], ax  ; data = cpu_to_le16(data);
                mov     eax, [ebp+fp]
                push    eax
                mov     eax, 2
                push    eax
                lea     eax, [ebp+data]
                push    eax
                call    nasm_write      ; nasm_write(&data, 2, fp);
                add     esp, 12
                leave
                retn
fwriteint16_t   endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

                public fwriteint32_t
fwriteint32_t   proc near

data            = dword ptr  8
fp              = dword ptr  0Ch

                push    ebp
                mov     ebp, esp
                sub     esp, 0
                nop
                mov     eax, [ebp+data]
                mov     [ebp+data], eax ; data = cpu_to_le32(data);
                mov     eax, [ebp+fp]
                push    eax
                mov     eax, 4
                push    eax
                lea     eax, [ebp+data]
                push    eax
                call    nasm_write      ; nasm_write(&data, 4, fp);
                add     esp, 12
                leave
                retn
fwriteint32_t   endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

                public fwritezero
fwritezero      proc near

blksize         = dword ptr -4
bytes           = dword ptr  8
fp              = dword ptr  0Ch

                push    ebp             ; void fwritezero(off_t bytes, FILE *fp)
                mov     ebp, esp
                sub     esp, 4
                nop

fwz_1:                                  ; ...
                mov     eax, [ebp+bytes] ; while (bytes > 0) {
                cmp     eax, 0
                jle     fwz_5
                mov     eax, [ebp+bytes]
                cmp     eax, 65536      ; blksize = (bytes < ZERO_BUF_SIZE) ? bytes : ZERO_BUF_SIZE;
                mov     eax, 0
                setl    al
                test    eax, eax
                jz      fwz_2
                jmp     fwz_3
; ---------------------------------------------------------------------------

fwz_2:                                  ; ...
                mov     eax, 65536
                jmp     fwz_4
; ---------------------------------------------------------------------------

fwz_3:                                  ; ...
                mov     eax, [ebp+bytes]

fwz_4:                                  ; ...
                mov     [ebp+blksize], eax
                mov     eax, [ebp+fp]
                push    eax
                mov     eax, [ebp+blksize]
                push    eax
                mov     eax, offset zero_buffer
                push    eax
                call    nasm_write      ; nasm_write(zero_buffer, blksize, fp);
                add     esp, 12
                mov     eax, [ebp+bytes]
                mov     ecx, [ebp+blksize]
                sub     eax, ecx
                mov     [ebp+bytes], eax ; bytes -= blksize;
                jmp     short fwz_1
; ---------------------------------------------------------------------------

fwz_5:                                  ; ...
                leave
                retn
fwritezero      endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

                public nasm_open_read
nasm_open_read  proc near               ; ...

again           = dword ptr -8
f               = dword ptr -4
filename        = dword ptr  8
flags           = dword ptr  0Ch

                push    ebp             ; FILE *nasm_open_read(const char *filename, enum file_flags flags)
                mov     ebp, esp
                sub     esp, 8
                nop
                mov     eax, 0
                mov     [ebp+f], eax    ; FILE *f = NULL;
                mov     eax, 1
                mov     [ebp+again], eax
                mov     eax, [ebp+again] ; if (again)
                test    eax, eax
                jz      nor_4
                mov     eax, [ebp+flags]
                and     eax, 1
                test    eax, eax
                jz      nor_1
                jmp     nor_2
; ---------------------------------------------------------------------------

nor_1:                                  ; ...
                mov     eax, offset L_185 ; "rb"
                jmp     nor_3
; ---------------------------------------------------------------------------

nor_2:                                  ; ...
                mov     eax, offset L_184 ; "rt"

nor_3:                                  ; ...
                push    eax
                mov     eax, [ebp+filename]
                push    eax
                call    fopen           ; f = fopen(filename, (flags & NF_TEXT) ? "rt" : "rb");
                add     esp, 8
                mov     [ebp+f], eax

nor_4:                                  ; ...
                mov     eax, [ebp+f]    ; if (!f && (flags & NF_FATAL))
                test    eax, eax
                jz      nor_5
                jmp     nor_6
; ---------------------------------------------------------------------------

nor_5:                                  ; ...
                mov     eax, [ebp+flags] ; nasm_fatal(ERR_NOFILE, "unable to open input file: `%s': %s",
                                        ; filename, strerror(errno));
                and     eax, 2
                test    eax, eax
                jz      nor_6
                call    _errno
                mov     ecx, [eax]
                push    ecx
                call    strerror
                add     esp, 4
                push    eax
                mov     eax, [ebp+filename]
                push    eax
                mov     eax, offset L_186 ; "unable to open input file: `%s': %s"
                push    eax
                mov     eax, 10h        ; ERR_NOFILE
                push    eax
                call    nasm_fatal
                add     esp, 16

nor_6:                                  ; ...
                mov     eax, [ebp+f]
                jmp     $+5
; ---------------------------------------------------------------------------

nor_7:                                  ; ...
                leave
                retn
nasm_open_read  endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

                public nasm_open_write
nasm_open_write proc near

f               = dword ptr -4
filename        = dword ptr  8
flags           = dword ptr  0Ch

                push    ebp             ; FILE *nasm_open_write(const char *filename, enum file_flags flags)
                mov     ebp, esp
                sub     esp, 4
                nop
                mov     eax, [ebp+flags] ; f = fopen(filename, (flags & NF_TEXT) ? "wt" : "wb");
                and     eax, 1
                test    eax, eax
                jz      now_1
                jmp     now_2
; ---------------------------------------------------------------------------

now_1:                                  ; ...
                mov     eax, offset L_188 ; "wb"
                jmp     now_3
; ---------------------------------------------------------------------------

now_2:                                  ; ...
                mov     eax, offset L_187 ; "wt"

now_3:                                  ; ...
                push    eax
                mov     eax, [ebp+filename]
                push    eax
                call    fopen
                add     esp, 8
                mov     [ebp+f], eax
                mov     eax, [ebp+f]    ; if (!f && (flags & NF_FATAL))
                test    eax, eax
                jz      now_4
                jmp     now_5
; ---------------------------------------------------------------------------

now_4:                                  ; ...
                mov     eax, [ebp+flags]
                and     eax, 2
                test    eax, eax
                jz      now_5
                call    _errno
                mov     ecx, [eax]
                push    ecx
                call    strerror
                add     esp, 4
                push    eax
                mov     eax, [ebp+filename]
                push    eax
                mov     eax, offset L_189 ; "unable to open output file: `%s': %s"
                push    eax
                mov     eax, 10h        ; ERR_NOFILE
                push    eax
                call    nasm_fatal      ; nasm_fatal(ERR_NOFILE, "unable to open output file: `%s': %s",
                                        ; filename, strerror(errno));
                add     esp, 16

now_5:                                  ; ...
                mov     eax, [ebp+f]
                jmp     $+5
; ---------------------------------------------------------------------------

now_6:                                  ; ...
                leave
                retn
nasm_open_write endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

                public nasm_file_exists
nasm_file_exists proc near

f               = dword ptr -4
filename        = dword ptr  8

                push    ebp             ; bool nasm_file_exists(const char *filename)
                mov     ebp, esp
                sub     esp, 4
                nop                     ; FILE *f;
                mov     eax, offset L_190 ; "rb"
                push    eax
                mov     eax, [ebp+filename]
                push    eax
                call    fopen
                add     esp, 8
                mov     [ebp+f], eax    ; f = fopen(filename, "rb");
                mov     eax, [ebp+f]    ; if (f) {
                test    eax, eax
                jz      nfe_1
                mov     eax, [ebp+f]
                push    eax
                call    fclose          ; fclose(f);
                add     esp, 4
                mov     eax, 1          ; return true;
                jmp     nfe_2
; ---------------------------------------------------------------------------
                jmp     nfe_2
; ---------------------------------------------------------------------------

nfe_1:                                  ; ...
                mov     eax, 0          ; return false;
                jmp     $+5
; ---------------------------------------------------------------------------

nfe_2:                                  ; ...
                leave
                retn
nasm_file_exists endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

                public nasm_file_size
nasm_file_size  proc near               ; ...

f               = dword ptr  8

                push    ebp             ; off_t nasm_file_size(FILE *f)
                mov     ebp, esp
                sub     esp, 0          ; #elif defined(nasm_fstat)
                nop
                mov     eax, 2          ; #else
                push    eax
                mov     eax, 0
                push    eax
                mov     eax, [ebp+f]
                push    eax
                call    fseeko          ; if (fseeko(f, 0, SEEK_END))
                add     esp, 12
                test    eax, eax
                jz      nfs_1
                mov     eax, -1         ; return (off_t)-1;
                jmp     nfs_2
; ---------------------------------------------------------------------------

nfs_1:                                  ; ...
                mov     eax, [ebp+f]
                push    eax
                call    ftello          ; return ftello(f);
                add     esp, 4
                jmp     $+5
; ---------------------------------------------------------------------------

nfs_2:                                  ; ...
                leave
                retn
nasm_file_size  endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

                public nasm_file_size_by_path
nasm_file_size_by_path proc near

len             = dword ptr -8
fp              = dword ptr -4
pathname        = dword ptr  8

                push    ebp             ; off_t nasm_file_size_by_path(const char *pathname)
                mov     ebp, esp        ; #ifdef nasm_stat
                sub     esp, 8          ; #else
                nop                     ; FILE *fp;
                mov     eax, 0          ; off_t len;
                push    eax             ; (NF_BINARY = 0)
                mov     eax, [ebp+pathname]
                push    eax
                call    nasm_open_read  ; fp = nasm_open_read(pathname, NF_BINARY);
                add     esp, 8
                mov     [ebp+fp], eax
                mov     eax, [ebp+fp]   ; if (!fp)
                test    eax, eax
                jz      nfsp_1
                jmp     nfsp_2
; ---------------------------------------------------------------------------

nfsp_1:                                 ; ...
                mov     eax, -1         ; return (off_t)-1;
                jmp     nfsp_3
; ---------------------------------------------------------------------------

nfsp_2:                                 ; ...
                mov     eax, [ebp+fp]
                push    eax
                call    nasm_file_size
                add     esp, 4
                mov     [ebp+len], eax  ; len = nasm_file_size(fp);
                mov     eax, [ebp+fp]
                push    eax
                call    fclose          ; fclose(fp);
                add     esp, 4
                mov     eax, [ebp+len]  ; return len;
                jmp     $+5
; ---------------------------------------------------------------------------

nfsp_3:                                 ; ...
                leave
                retn
nasm_file_size_by_path endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

                public nasm_file_time
nasm_file_time  proc near
                push    ebp             ; bool nasm_file_time(time_t *t, const char *pathname)
                mov     ebp, esp
                sub     esp, 0          ; #ifdef nasm_stat
                nop                     ; #else
                mov     eax, 0          ; return false;
                                        ; /* No idea how to do this on this OS */
                jmp     $+5
; ---------------------------------------------------------------------------

nft_1:                                  ; ...
                leave
                retn
nasm_file_time  endp

_text           ends

; ===========================================================================

; Segment type: Pure data
; Segment permissions: Read/Write
; Segment alignment '32byte' can not be represented in assembly
_data           segment para public 'DATA' use32
                assume cs:_data
                ;org 8000840h
L_181           db 'unable to read input: %s',0 ; ...
L_182           db 'fatal short read on input',0 ; ...
L_183           db 'unable to write output: %s',0 ; ...
L_184           db 'rt',0               ; ...
L_185           db 'rb',0               ; ...
L_186           db 'unable to open input file: `%s',27h,': %s',0 ; ...
L_187           db 'wt',0               ; ...
L_188           db 'wb',0               ; ...
L_189           db 'unable to open output file: `%s',27h,': %s',0 ; ...
L_190           db 'rb',0               ; ...
_data           ends

; ===========================================================================

; Segment type: Zero-length
; Segment permissions: Read/Write
; Segment alignment '32byte' can not be represented in assembly
_bss            segment para public 'BSS' use32
_bss            ends

; ===========================================================================

; Segment type: Externs
; extern
                extrn _vsnprintf:near   ; ...
                extrn _vsnwprintf:near  ; ...
                extrn __shldi3:near     ; ...
                extrn nasm_verror:dword ; ...
                extrn fread:near        ; ...
                extrn ferror:near       ; ...
                extrn _errno:near       ; ...
                extrn strerror:near     ; ...
                extrn nasm_fatal:near   ; ...
                extrn feof:near         ; ...
                extrn fwrite:near       ; ...
                extrn zero_buffer       ; ...
                extrn fopen:near        ; ...
                extrn fclose:near       ; ...
                extrn fseeko:near       ; ...
                extrn ftello:near       ; ...


                end
