

;
; +-------------------------------------------------------------------------+
; |   This file has been generated by The Interactive Disassembler (IDA)    |
; |           Copyright (c) 2018 Hex-Rays, <support@hex-rays.com>           |
; |                            Freeware version                             |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : 812EF5C06BA5702483A54D0957923449A4F813362CDA8B36DC53FEA8D6368EFB
; Input MD5    : E47DA90A1609EEB62DF29EDB82E42214
; Input CRC32  : 314F479B

; File Name   : C:\Users\90542\OneDrive\Masaüstü\nasm_214_c_o\path.o
; Format      : ELF for Intel 386 (Relocatable)
;
; Source File : 'path.c'

                .686p
                .mmx
                .model flat
.intel_syntax noprefix

; ===========================================================================

; Segment type: Pure code
; Segment permissions: Read/Execute
_text           segment dword public 'CODE' use32
                assume cs:_text
                ;org 8000000h
                assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing

; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

overflow_general proc near

var_18          = dword ptr -18h
var_14          = dword ptr -14h
var_10          = dword ptr -10h
var_C           = dword ptr -0Ch
var_4           = dword ptr -4
arg_0           = dword ptr  8
arg_4           = dword ptr  0Ch
arg_8           = dword ptr  10h

                push    ebp
                mov     ebp, esp
                sub     esp, 18h
                nop
                mov     eax, [ebp+arg_8]
                cmp     eax, 8
                jl      loc_8000020
                mov     eax, 0
                jmp     locret_80000D4
; ---------------------------------------------------------------------------

loc_8000020:                            ; ...
                mov     eax, [ebp+arg_8]
                shl     eax, 3
                dec     eax
                mov     [ebp+var_4], eax
                mov     eax, [ebp+var_4]
                push    eax
                mov     eax, 2
                mov     ecx, 0
                push    ecx
                push    eax
                call    __ashldi3
                add     esp, 0Ch
                sub     eax, 1
                sbb     edx, 0
                mov     [ebp+var_10], eax
                mov     [ebp+var_C], edx
                mov     eax, [ebp+var_4]
                push    eax
                mov     eax, 2
                mov     ecx, 0
                push    ecx
                push    eax
                call    __ashldi3
                add     esp, 0Ch
                mov     ecx, 0
                sub     ecx, eax
                mov     eax, 0
                sbb     eax, edx
                mov     [ebp+var_18], ecx
                mov     [ebp+var_14], eax
                mov     eax, [ebp+arg_4]
                mov     ecx, [ebp+var_14]
                cmp     eax, ecx
                jg      loc_80000A1
                jnz     loc_800009C
                mov     eax, [ebp+arg_0]
                mov     ecx, [ebp+var_18]
                cmp     eax, ecx
                jnb     loc_80000A1

loc_800009C:                            ; ...
                jmp     loc_80000CF
; ---------------------------------------------------------------------------

loc_80000A1:                            ; ...
                mov     eax, [ebp+arg_4]
                mov     ecx, [ebp+var_C]
                cmp     eax, ecx
                jl      loc_80000C8
                jnz     loc_80000C3
                mov     eax, [ebp+arg_0]
                mov     ecx, [ebp+var_10]
                cmp     eax, ecx
                jbe     loc_80000C8

loc_80000C3:                            ; ...
                jmp     loc_80000CF
; ---------------------------------------------------------------------------

loc_80000C8:                            ; ...
                mov     eax, 0
                jmp     short locret_80000D4
; ---------------------------------------------------------------------------

loc_80000CF:                            ; ...
                mov     eax, 1

locret_80000D4:                         ; ...
                leave
                retn
overflow_general endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

overflow_signed proc near

var_18          = dword ptr -18h
var_14          = dword ptr -14h
var_10          = dword ptr -10h
var_C           = dword ptr -0Ch
var_4           = dword ptr -4
arg_0           = dword ptr  8
arg_4           = dword ptr  0Ch
arg_8           = dword ptr  10h

                push    ebp
                mov     ebp, esp
                sub     esp, 18h
                nop
                mov     eax, [ebp+arg_8]
                cmp     eax, 8
                jl      loc_80000F6
                mov     eax, 0
                jmp     locret_80001AA
; ---------------------------------------------------------------------------

loc_80000F6:                            ; ...
                mov     eax, [ebp+arg_8]
                shl     eax, 3
                dec     eax
                mov     [ebp+var_4], eax
                mov     eax, [ebp+var_4]
                push    eax
                mov     eax, 1
                mov     ecx, 0
                push    ecx
                push    eax
                call    __ashldi3
                add     esp, 0Ch
                sub     eax, 1
                sbb     edx, 0
                mov     [ebp+var_10], eax
                mov     [ebp+var_C], edx
                mov     eax, [ebp+var_4]
                push    eax
                mov     eax, 1
                mov     ecx, 0
                push    ecx
                push    eax
                call    __ashldi3
                add     esp, 0Ch
                mov     ecx, 0
                sub     ecx, eax
                mov     eax, 0
                sbb     eax, edx
                mov     [ebp+var_18], ecx
                mov     [ebp+var_14], eax
                mov     eax, [ebp+arg_4]
                mov     ecx, [ebp+var_14]
                cmp     eax, ecx
                jg      loc_8000177
                jnz     loc_8000172
                mov     eax, [ebp+arg_0]
                mov     ecx, [ebp+var_18]
                cmp     eax, ecx
                jnb     loc_8000177

loc_8000172:                            ; ...
                jmp     loc_80001A5
; ---------------------------------------------------------------------------

loc_8000177:                            ; ...
                mov     eax, [ebp+arg_4]
                mov     ecx, [ebp+var_C]
                cmp     eax, ecx
                jl      loc_800019E
                jnz     loc_8000199
                mov     eax, [ebp+arg_0]
                mov     ecx, [ebp+var_10]
                cmp     eax, ecx
                jbe     loc_800019E

loc_8000199:                            ; ...
                jmp     loc_80001A5
; ---------------------------------------------------------------------------

loc_800019E:                            ; ...
                mov     eax, 0
                jmp     short locret_80001AA
; ---------------------------------------------------------------------------

loc_80001A5:                            ; ...
                mov     eax, 1

locret_80001AA:                         ; ...
                leave
                retn
overflow_signed endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

overflow_unsigned proc near

var_18          = dword ptr -18h
var_14          = dword ptr -14h
var_10          = dword ptr -10h
var_C           = dword ptr -0Ch
var_4           = dword ptr -4
arg_0           = dword ptr  8
arg_4           = dword ptr  0Ch
arg_8           = dword ptr  10h

                push    ebp
                mov     ebp, esp
                sub     esp, 18h
                nop
                mov     eax, [ebp+arg_8]
                cmp     eax, 8
                jl      loc_80001CC
                mov     eax, 0
                jmp     locret_8000264
; ---------------------------------------------------------------------------

loc_80001CC:                            ; ...
                mov     eax, [ebp+arg_8]
                shl     eax, 3
                dec     eax
                mov     [ebp+var_4], eax
                mov     eax, [ebp+var_4]
                push    eax
                mov     eax, 2
                mov     ecx, 0
                push    ecx
                push    eax
                call    __ashldi3
                add     esp, 0Ch
                sub     eax, 1
                sbb     edx, 0
                mov     [ebp+var_10], eax
                mov     [ebp+var_C], edx
                mov     eax, 0
                mov     ecx, 0
                mov     [ebp+var_18], eax
                mov     [ebp+var_14], ecx
                mov     eax, [ebp+arg_4]
                mov     ecx, [ebp+var_14]
                cmp     eax, ecx
                jg      loc_8000231
                jnz     loc_800022C
                mov     eax, [ebp+arg_0]
                mov     ecx, [ebp+var_18]
                cmp     eax, ecx
                jnb     loc_8000231

loc_800022C:                            ; ...
                jmp     loc_800025F
; ---------------------------------------------------------------------------

loc_8000231:                            ; ...
                mov     eax, [ebp+arg_4]
                mov     ecx, [ebp+var_C]
                cmp     eax, ecx
                jl      loc_8000258
                jnz     loc_8000253
                mov     eax, [ebp+arg_0]
                mov     ecx, [ebp+var_10]
                cmp     eax, ecx
                jbe     loc_8000258

loc_8000253:                            ; ...
                jmp     loc_800025F
; ---------------------------------------------------------------------------

loc_8000258:                            ; ...
                mov     eax, 0
                jmp     short locret_8000264
; ---------------------------------------------------------------------------

loc_800025F:                            ; ...
                mov     eax, 1

locret_8000264:                         ; ...
                leave
                retn
overflow_unsigned endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

signed_bits     proc near

arg_0           = dword ptr  8
arg_4           = dword ptr  0Ch
arg_8           = dword ptr  10h

                push    ebp
                mov     ebp, esp
                sub     esp, 0
                nop
                mov     eax, [ebp+arg_8]
                cmp     eax, 40h
                jge     loc_8000307
                mov     eax, [ebp+arg_8]
                push    eax
                mov     eax, 1
                mov     ecx, 0
                push    ecx
                push    eax
                call    __ashldi3
                add     esp, 0Ch
                sub     eax, 1
                sbb     edx, 0
                mov     ecx, [ebp+arg_0]
                and     ecx, eax
                mov     eax, [ebp+arg_4]
                and     eax, edx
                mov     [ebp+arg_0], ecx
                mov     [ebp+arg_4], eax
                mov     eax, [ebp+arg_8]
                dec     eax
                push    eax
                mov     eax, 1
                mov     ecx, 0
                push    ecx
                push    eax
                call    __ashldi3
                add     esp, 0Ch
                mov     ecx, [ebp+arg_0]
                and     ecx, eax
                mov     eax, [ebp+arg_4]
                and     eax, edx
                cmp     eax, 0
                jnz     loc_80002DF
                cmp     ecx, 0
                jz      loc_8000307

loc_80002DF:                            ; ...
                mov     eax, [ebp+arg_8]
                push    eax
                mov     eax, 0FFFFFFFFh
                mov     ecx, 0FFFFFFFFh
                push    ecx
                push    eax
                call    __ashldi3
                add     esp, 0Ch
                mov     ecx, [ebp+arg_0]
                or      ecx, eax
                mov     eax, [ebp+arg_4]
                or      eax, edx
                mov     [ebp+arg_0], ecx
                mov     [ebp+arg_4], eax

loc_8000307:                            ; ...
                mov     eax, [ebp+arg_0]
                mov     edx, [ebp+arg_4]
                leave
                retn
signed_bits     endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

nasm_set_verror proc near

var_4           = dword ptr -4
arg_0           = dword ptr  8

                push    ebp
                mov     ebp, esp
                sub     esp, 4
                nop
                mov     eax, ds:nasm_verror
                mov     [ebp+var_4], eax
                mov     eax, [ebp+arg_0]
                mov     ds:nasm_verror, eax
                mov     eax, [ebp+var_4]
                leave
                retn
nasm_set_verror endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

ismatch         proc near               ; ...

p               = dword ptr -4
charset         = dword ptr  8
chr             = byte ptr  0Ch

                push    ebp             ; static inline bool ismatch(const char *charset, char ch)
                mov     ebp, esp
                sub     esp, 4
                nop
                mov     eax, [ebp+charset] ; const char *p;
                mov     [ebp+p], eax    ; for (p = charset; *p; p++) {

im_1:                                   ; ...
                mov     eax, [ebp+p]
                movsx   ecx, byte ptr [eax] ; *p
                cmp     ecx, 0
                jz      im_5
                jmp     im_3
; ---------------------------------------------------------------------------

im_2:                                   ; ...
                mov     eax, [ebp+p]    ; (next) p++
                mov     ecx, eax
                inc     eax
                mov     [ebp+p], eax
                jmp     short im_1
; ---------------------------------------------------------------------------

im_3:                                   ; ...
                mov     eax, [ebp+p]    ; if (ch == *p)
                movsx   ecx, [ebp+chr]
                movsx   edx, byte ptr [eax]
                cmp     ecx, edx
                jnz     im_4
                mov     eax, 1          ; return true;
                jmp     im_6
; ---------------------------------------------------------------------------

im_4:                                   ; ...
                jmp     short im_2
; ---------------------------------------------------------------------------

im_5:                                   ; ...
                mov     eax, 0          ; return false;

im_6:                                   ; ...
                leave
                retn
ismatch         endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

first_filename_char proc near           ; ...

p               = dword ptr -4
path            = dword ptr  8

                push    ebp             ; static const char *first_filename_char(const char *path)
                mov     ebp, esp
                sub     esp, 4
                nop
                mov     eax, [ebp+path]
                push    eax
                call    strlen
                add     esp, 4
                mov     ecx, [ebp+path]
                add     ecx, eax
                mov     [ebp+p], ecx    ; const char *p = path + strlen(path);

ffnc_1:                                 ; ...
                mov     eax, [ebp+p]    ; while (p > path) {
                mov     ecx, [ebp+path]
                cmp     eax, ecx
                jbe     ffnc_3
                mov     eax, [ebp+p]    ; if (ismatch(separators, p[-1]))
                add     eax, -1
                movsx   ecx, byte ptr [eax]
                push    ecx
                mov     eax, offset L_191 ; "/\\:"
                push    eax
                call    ismatch
                add     esp, 8
                cmp     eax, 0
                jz      ffnc_2
                mov     eax, [ebp+p]    ; return p;
                jmp     ffnc_4
; ---------------------------------------------------------------------------

ffnc_2:                                 ; ...
                mov     eax, [ebp+p]    ; p--;
                mov     ecx, eax
                add     eax, -1
                mov     [ebp+p], eax
                jmp     short ffnc_1
; ---------------------------------------------------------------------------

ffnc_3:                                 ; ...
                mov     eax, [ebp+p]    ; return p;

ffnc_4:                                 ; ...
                leave
                retn
first_filename_char endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

                public nasm_basename
nasm_basename   proc near

path            = dword ptr  8

                push    ebp             ; char *nasm_basename(const char *path)
                mov     ebp, esp
                sub     esp, 0
                nop
                mov     eax, [ebp+path]
                push    eax
                call    first_filename_char
                add     esp, 4
                push    eax
                call    nasm_strdup     ; return nasm_strdup(first_filename_char(path));
                add     esp, 4
                leave
                retn
nasm_basename   endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

                public nasm_dirname
nasm_dirname    proc near

p0              = dword ptr -8
p               = dword ptr -4
path            = dword ptr  8

                push    ebp             ; char *nasm_dirname(const char *path)
                mov     ebp, esp
                sub     esp, 8
                nop
                mov     eax, [ebp+path]
                push    eax
                call    first_filename_char
                add     esp, 4
                mov     [ebp+p], eax    ; const char *p = first_filename_char(path);
                mov     eax, [ebp+p]
                mov     [ebp+p0], eax   ; const char *p0 = p;
                mov     eax, [ebp+p]    ; (void)p0;
                mov     ecx, [ebp+path] ; if (p == path)
                cmp     eax, ecx
                jnz     ndn_1
                mov     eax, offset L_192 ; "."
                push    eax
                call    nasm_strdup     ; return nasm_strdup(curdir);
                add     esp, 4
                jmp     ndn_4
; ---------------------------------------------------------------------------

ndn_1:                                  ; ...
                mov     eax, [ebp+path] ; while (p > path+leaveonclean) {
                add     eax, 2          ; leaveonclean
                mov     ecx, [ebp+p]
                cmp     ecx, eax
                jbe     ndn_3
                mov     eax, [ebp+p]
                add     eax, -1
                movsx   ecx, byte ptr [eax]
                push    ecx             ; p[-1]
                mov     eax, offset L_193 ; "/\\"
                push    eax             ; cleandirend
                call    ismatch         ; if (ismatch(cleandirend, p[-1]))
                add     esp, 8
                cmp     eax, 0
                jz      ndn_2
                jmp     ndn_3           ; break;
; ---------------------------------------------------------------------------

ndn_2:                                  ; ...
                mov     eax, [ebp+p]    ; p--;
                mov     ecx, eax
                add     eax, 0FFFFFFFFh ; -1
                mov     [ebp+p], eax
                jmp     short ndn_1
; ---------------------------------------------------------------------------

ndn_3:                                  ; ...
                mov     eax, [ebp+p]
                mov     ecx, [ebp+path]
                sub     eax, ecx
                push    eax
                mov     eax, [ebp+path]
                push    eax
                call    nasm_strndup    ; return nasm_strndup(path, p-path);
                add     esp, 8

ndn_4:                                  ; ...
                leave
                retn
nasm_dirname    endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

                public nasm_catfile
nasm_catfile    proc near

dosep           = dword ptr -14h
pp              = dword ptr -10h
p               = dword ptr -0Ch
fl              = dword ptr -8
dln             = dword ptr -4
dir             = dword ptr  8
file            = dword ptr  0Ch

                push    ebp             ; char *nasm_catfile(const char *dir, const char *file)
                mov     ebp, esp
                sub     esp, 20
                nop
                mov     eax, [ebp+dir]
                push    eax
                call    strlen
                add     esp, 4
                mov     [ebp+dln], eax  ; size_t dl = strlen(dir);
                mov     eax, [ebp+file]
                push    eax
                call    strlen          ; size_t fl = strlen(file);
                add     esp, 4
                mov     [ebp+fl], eax   ; char *p, *pp;
                mov     eax, 1
                mov     [ebp+dosep], eax ; bool dosep = true;
                mov     eax, [ebp+dln]
                cmp     eax, 0          ; if (!dl || ismatch(separators, dir[dl-1])) {
                jz      ncf_1
                mov     eax, [ebp+dln]
                dec     eax
                mov     ecx, [ebp+dir]
                add     ecx, eax
                movsx   eax, byte ptr [ecx]
                push    eax
                mov     eax, offset L_194 ; "/\\:"
                push    eax
                call    ismatch
                add     esp, 8
                cmp     eax, 0
                jnz     ncf_1
                jmp     ncf_2
; ---------------------------------------------------------------------------

ncf_1:                                  ; ...
                mov     eax, 0          ; /* No separator necessary */
                mov     [ebp+dosep], eax ; dosep = false;

ncf_2:                                  ; ...
                mov     eax, [ebp+dln]
                mov     ecx, [ebp+fl]
                add     eax, ecx
                mov     ecx, [ebp+dosep]
                add     eax, ecx
                inc     eax
                push    eax
                call    nasm_malloc
                add     esp, 4
                mov     [ebp+pp], eax
                mov     [ebp+p], eax    ; p = pp = nasm_malloc(dl + fl + dosep + 1);
                mov     eax, [ebp+dln]
                push    eax
                mov     eax, [ebp+dir]
                push    eax
                mov     eax, [ebp+pp]
                push    eax
                call    memcpy          ; memcpy(pp, dir, dl);
                add     esp, 12
                mov     eax, [ebp+dln]
                mov     ecx, [ebp+pp]
                add     ecx, eax
                mov     [ebp+pp], ecx   ; pp += dl;
                mov     eax, [ebp+dosep]
                cmp     eax, 0          ; if (dosep)
                jz      ncf_3
                mov     eax, [ebp+pp]
                mov     ecx, eax
                inc     eax
                mov     [ebp+pp], eax
                mov     eax, '\'        ; catsep
                mov     [ecx], al       ; *pp++ = catsep;

ncf_3:                                  ; ...
                mov     eax, [ebp+fl]
                inc     eax
                push    eax
                mov     eax, [ebp+file]
                push    eax
                mov     eax, [ebp+pp]
                push    eax
                call    memcpy          ; memcpy(pp, file, fl+1);
                add     esp, 12
                mov     eax, [ebp+p]    ; return p;
                leave
                retn
nasm_catfile    endp

_text           ends

; ===========================================================================

; Segment type: Pure data
; Segment permissions: Read/Write
_data           segment dword public 'DATA' use32
                assume cs:_data
                ;org 8000588h
L_191           db '/\:',0              ; ...
L_192           db '.',0                ; ...
L_193           db '/\',0               ; ...
L_194           db '/\:',0              ; ...
_data           ends

; ===========================================================================

; Segment type: Zero-length
; Segment permissions: Read/Write
_bss            segment dword public 'BSS' use32
_bss            ends

; ===========================================================================

; Segment type: Externs
; extern
                extrn __ashldi3:near    ; ...
                extrn nasm_verror:dword ; ...
                extrn strlen:near       ; ...
                extrn nasm_strdup:near  ; ...
                extrn nasm_strndup:near ; ...
                extrn nasm_malloc:near  ; ...
                extrn memcpy:near       ; ...


                end
