

;
; +-------------------------------------------------------------------------+
; |   This file has been generated by The Interactive Disassembler (IDA)    |
; |           Copyright (c) 2018 Hex-Rays, <support@hex-rays.com>           |
; |                            Freeware version                             |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : A95BD46256C87213024076CD82373EC3C8E58ED040C3464FDE6F1545F2883048
; Input MD5    : A9295080F47386D1BC39D772270264FE
; Input CRC32  : CB82BC4B

; File Name   : C:\Users\90542\OneDrive\Masaüstü\nasm_214_c_o\rbtree.o
; Format      : ELF for Intel 386 (Relocatable)
;
; Source File : 'rbtree.c'

                .686p
                .mmx
                .model flat
.intel_syntax noprefix

; ===========================================================================

; Segment type: Pure code
; Segment permissions: Read/Execute
_text           segment dword public 'CODE' use32
                assume cs:_text
                ;org 8000000h
                assume es:nothing, ss:nothing, ds:_text, fs:nothing, gs:nothing

; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

                public rb_search
rb_search       proc near

best            = dword ptr -4
tree            = dword ptr  8
key             = dword ptr  0Ch
key_h           = dword ptr  10h

                push    ebp             ; struct rbtree *rb_search(struct rbtree *tree, uint64_t key)
                mov     ebp, esp
                sub     esp, 4
                nop
                mov     eax, 0
                mov     [ebp+best], eax ; struct rbtree *best = NULL;

rbs_1:                                  ; ...
                mov     eax, [ebp+tree] ; while (tree) {
                cmp     eax, 0
                jz      rbs_6
                mov     eax, [ebp+tree] ; if (tree->key == key)
                mov     ecx, [eax]
                add     eax, 4
                mov     edx, [eax]
                mov     eax, [ebp+key_h]
                cmp     edx, eax
                jnz     rbs_2
                mov     eax, [ebp+key]
                cmp     ecx, eax
                jnz     rbs_2
                mov     eax, [ebp+tree] ; return tree;
                jmp     rbs_7
; ---------------------------------------------------------------------------
                jmp     rbs_5
; ---------------------------------------------------------------------------

rbs_2:                                  ; ...
                mov     eax, [ebp+tree] ; else if (tree->key > key)
                mov     ecx, [eax]
                add     eax, 4          ; tree->key (high)
                mov     edx, [eax]
                mov     eax, [ebp+key_h]
                cmp     edx, eax
                jb      rbs_4
                jnz     rbs_3
                mov     eax, [ebp+key]  ; tree->key (low)
                cmp     ecx, eax
                jbe     rbs_4

rbs_3:                                  ; ...
                mov     eax, [ebp+tree]
                add     eax, 8          ; tree->left
                mov     ecx, [eax]
                mov     [ebp+tree], ecx ; tree = tree->left;
                jmp     rbs_5
; ---------------------------------------------------------------------------

rbs_4:                                  ; ...
                mov     eax, [ebp+tree] ; else {
                mov     [ebp+best], eax ; best = tree;
                mov     eax, [ebp+tree]
                add     eax, 12         ; tree->right
                mov     ecx, [eax]
                mov     [ebp+tree], ecx ; tree = tree->right;

rbs_5:                                  ; ...
                jmp     rbs_1
; ---------------------------------------------------------------------------

rbs_6:                                  ; ...
                mov     eax, [ebp+best] ; return best;

rbs_7:                                  ; ...
                leave
                retn
rb_search       endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

is_red          proc near               ; ...

h               = dword ptr  8

                push    ebp             ; static bool is_red(struct rbtree *h)
                mov     ebp, esp
                sub     esp, 0
                nop
                mov     eax, [ebp+h]
                cmp     eax, 0
                jz      ir_1
                mov     eax, [ebp+h]    ; return h && h->red;
                add     eax, 16
                mov     ecx, [eax]
                cmp     ecx, 0
                jz      ir_1
                mov     eax, 1
                jmp     short ir_2
; ---------------------------------------------------------------------------

ir_1:                                   ; ...
                mov     eax, 0

ir_2:                                   ; ...
                leave
                retn
is_red          endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

rotate_left     proc near               ; ...

x               = dword ptr -4
h               = dword ptr  8

                push    ebp             ; static struct rbtree *rotate_left(struct rbtree *h)
                mov     ebp, esp
                sub     esp, 4
                nop
                mov     eax, [ebp+h]
                add     eax, 12
                mov     ecx, [eax]
                mov     [ebp+x], ecx    ; struct rbtree *x = h->right;
                mov     eax, [ebp+h]
                add     eax, 12
                mov     ecx, [ebp+x]
                add     ecx, 8
                mov     edx, [ecx]
                mov     [eax], edx      ; h->right = x->left;
                mov     eax, [ebp+x]
                add     eax, 8
                mov     ecx, [ebp+h]
                mov     [eax], ecx      ; x->left = h;
                mov     eax, [ebp+x]
                add     eax, 16
                mov     ecx, [ebp+x]
                add     ecx, 8
                mov     edx, [ecx]
                add     edx, 16
                mov     ecx, [edx]
                mov     [eax], ecx      ; x->red = x->left->red;
                mov     eax, [ebp+x]
                add     eax, 8
                mov     ecx, [eax]
                add     ecx, 16
                mov     eax, 1
                mov     [ecx], eax      ; x->left->red = true;
                mov     eax, [ebp+x]    ; return x;
                leave
                retn
rotate_left     endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

rotate_right    proc near               ; ...

x               = dword ptr -4
h               = dword ptr  8

                push    ebp             ; static struct rbtree *rotate_right(struct rbtree *h)
                mov     ebp, esp
                sub     esp, 4
                nop
                mov     eax, [ebp+h]
                add     eax, 8
                mov     ecx, [eax]
                mov     [ebp+x], ecx    ; struct rbtree *x = h->left;
                mov     eax, [ebp+h]
                add     eax, 8
                mov     ecx, [ebp+x]
                add     ecx, 12
                mov     edx, [ecx]
                mov     [eax], edx      ; h->left = x->right;
                mov     eax, [ebp+x]
                add     eax, 12
                mov     ecx, [ebp+h]
                mov     [eax], ecx      ; x->right = h;
                mov     eax, [ebp+x]
                add     eax, 16
                mov     ecx, [ebp+x]
                add     ecx, 12
                mov     edx, [ecx]
                add     edx, 16
                mov     ecx, [edx]
                mov     [eax], ecx      ; x->red = x->right->red;
                mov     eax, [ebp+x]
                add     eax, 12
                mov     ecx, [eax]
                add     ecx, 16
                mov     eax, 1
                mov     [ecx], eax      ; x->right->red = true;
                mov     eax, [ebp+x]    ; return x;
                leave
                retn
rotate_right    endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

color_flip      proc near               ; ...

tmp3            = dword ptr -0Ch
tmp2            = dword ptr -8
tmp1            = dword ptr -4
h               = dword ptr  8

                push    ebp             ; static void color_flip(struct rbtree *h)
                mov     ebp, esp
                sub     esp, 12
                nop
                mov     eax, [ebp+h]
                add     eax, 16
                mov     ecx, [ebp+h]
                add     ecx, 16
                mov     [ebp+tmp1], eax ; h->red
                mov     eax, [ecx]
                cmp     eax, 0
                jz      cf_1
                mov     eax, 0          ; !h->red = 0
                jmp     short cf_2
; ---------------------------------------------------------------------------

cf_1:                                   ; ...
                mov     eax, 1          ; !h->red = 1

cf_2:                                   ; ...
                mov     ecx, [ebp+tmp1]
                mov     [ecx], eax      ; h->red = !h->red
                mov     eax, [ebp+h]
                add     eax, 8
                mov     ecx, [eax]
                add     ecx, 16
                mov     eax, [ebp+h]
                add     eax, 8
                mov     edx, [eax]
                add     edx, 16
                mov     [ebp+tmp2], ecx ; h->left->red
                mov     eax, [edx]
                cmp     eax, 0
                jz      cf_3
                mov     eax, 0          ; !h->left->red = 0
                jmp     short cf_4
; ---------------------------------------------------------------------------

cf_3:                                   ; ...
                mov     eax, 1          ; !h->left->red = 1

cf_4:                                   ; ...
                mov     ecx, [ebp+tmp2]
                mov     [ecx], eax      ; h->left->red = !h->left->red;
                mov     eax, [ebp+h]
                add     eax, 12
                mov     ecx, [eax]
                add     ecx, 16
                mov     eax, [ebp+h]
                add     eax, 12
                mov     edx, [eax]
                add     edx, 16
                mov     [ebp+tmp3], ecx ; h->right->red
                mov     eax, [edx]
                cmp     eax, 0
                jz      cf_5
                mov     eax, 0          ; !h->right->red = 0
                jmp     short cf_6
; ---------------------------------------------------------------------------

cf_5:                                   ; ...
                mov     eax, 1          ; !h->right->red = 1

cf_6:                                   ; ...
                mov     ecx, [ebp+tmp3]
                mov     [ecx], eax      ; h->right->red = !h->right->red;
                leave
                retn
color_flip      endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

                public rb_insert
rb_insert       proc near               ; ...

tmp5            = dword ptr -14h
tmp4            = dword ptr -10h
tmp3            = dword ptr -0Ch
tmp2            = dword ptr -8
tmp1            = dword ptr -4
tree            = dword ptr  8
node            = dword ptr  0Ch

                push    ebp             ; struct rbtree *rb_insert(struct rbtree *tree, struct rbtree *node)
                mov     ebp, esp
                sub     esp, 20
                nop
                mov     eax, [ebp+tree] ; if (!tree) {
                cmp     eax, 0
                jz      rbi_1
                jmp     rbi_2
; ---------------------------------------------------------------------------

rbi_1:                                  ; ...
                mov     eax, [ebp+node]
                add     eax, 16
                mov     ecx, 1
                mov     [eax], ecx      ; node->red = true;
                mov     eax, [ebp+node] ; return node;
                jmp     rbi_9
; ---------------------------------------------------------------------------

rbi_2:                                  ; ...
                mov     eax, [ebp+tree] ; if (is_red(tree->left) && is_red(tree->right))
                add     eax, 8
                mov     ecx, [eax]
                push    ecx
                call    is_red          ; is_red(tree->left)
                add     esp, 4
                cmp     eax, 0
                jz      rbi_3
                mov     eax, [ebp+tree]
                add     eax, 12
                mov     ecx, [eax]
                push    ecx
                call    is_red          ; is_red(tree->right)
                add     esp, 4
                cmp     eax, 0
                jz      rbi_3
                mov     eax, [ebp+tree]
                push    eax
                call    color_flip      ; color_flip(tree);
                add     esp, 4

rbi_3:                                  ; ...
                mov     eax, [ebp+node] ; if (node->key < tree->key)
                mov     ecx, [ebp+tree]
                mov     edx, [eax]      ; node->key
                add     eax, 4          ; node->key (high, address)
                mov     [ebp+tmp1], ecx ; tree->key (low, address)
                mov     ecx, [eax]      ; node->key
                mov     eax, [ebp+tmp1]
                mov     eax, [eax]      ; tree->key (low)
                mov     [ebp+tmp2], edx ; node->key (low)
                mov     edx, [ebp+tmp1] ; tree->key (low, address)
                add     edx, 4          ; tree->key (high, address)
                mov     [ebp+tmp3], ecx ; node->key (high)
                mov     ecx, [edx]      ; tree->key (high)
                mov     edx, [ebp+tmp3]
                cmp     edx, ecx
                ja      rbi_5
                jnz     rbi_4
                mov     ecx, [ebp+tmp2] ; node->key (low)
                cmp     ecx, eax
                jnb     rbi_5

rbi_4:                                  ; ...
                mov     eax, [ebp+tree]
                add     eax, 8
                mov     ecx, [ebp+tree]
                add     ecx, 8
                mov     edx, [ebp+node]
                push    edx
                mov     edx, [ecx]
                push    edx
                mov     [ebp+tmp4], eax ; tree->left (address)
                call    rb_insert
                add     esp, 8
                mov     ecx, [ebp+tmp4]
                mov     [ecx], eax      ; tree->left = rb_insert(tree->left, node);
                jmp     rbi_6
; ---------------------------------------------------------------------------

rbi_5:                                  ; ...
                mov     eax, [ebp+tree]
                add     eax, 12
                mov     ecx, [ebp+tree]
                add     ecx, 12
                mov     edx, [ebp+node]
                push    edx
                mov     edx, [ecx]
                push    edx
                mov     [ebp+tmp5], eax ; tree->right (address)
                call    rb_insert
                add     esp, 8
                mov     ecx, [ebp+tmp5]
                mov     [ecx], eax      ; tree->right = rb_insert(tree->right, node);

rbi_6:                                  ; ...
                mov     eax, [ebp+tree] ; if (is_red(tree->right))
                add     eax, 12
                mov     ecx, [eax]
                push    ecx
                call    is_red
                add     esp, 4
                cmp     eax, 0
                jz      rbi_7
                mov     eax, [ebp+tree]
                push    eax
                call    rotate_left
                add     esp, 4
                mov     [ebp+tree], eax ; tree = rotate_left(tree);

rbi_7:                                  ; ...
                mov     eax, [ebp+tree] ; if (is_red(tree->left) && is_red(tree->left->left))
                add     eax, 8
                mov     ecx, [eax]
                push    ecx
                call    is_red          ; is_red(tree->left)
                add     esp, 4
                cmp     eax, 0
                jz      rbi_8
                mov     eax, [ebp+tree]
                add     eax, 8
                mov     ecx, [eax]
                add     ecx, 8
                mov     eax, [ecx]
                push    eax
                call    is_red          ; is_red(tree->left->left)
                add     esp, 4
                cmp     eax, 0
                jz      rbi_8
                mov     eax, [ebp+tree]
                push    eax
                call    rotate_right
                add     esp, 4
                mov     [ebp+tree], eax ; tree = rotate_right(tree);

rbi_8:                                  ; ...
                mov     eax, [ebp+tree] ; return tree;

rbi_9:                                  ; ...
                leave
                retn
rb_insert       endp

_text           ends

; ===========================================================================

; Segment type: Zero-length
; Segment permissions: Read/Write
_data           segment dword public 'DATA' use32
_data           ends

; ===========================================================================

; Segment type: Zero-length
; Segment permissions: Read/Write
_bss            segment dword public 'BSS' use32
_bss            ends


                end
