

;
; +-------------------------------------------------------------------------+
; |   This file has been generated by The Interactive Disassembler (IDA)    |
; |           Copyright (c) 2018 Hex-Rays, <support@hex-rays.com>           |
; |                            Freeware version                             |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : B8EDEFD6F9904E53B1DD9D63416AB5E841C290380D763D6F01028F6E775A6657
; Input MD5    : B02AEED572D3B73AEAD1F4A44034899D
; Input CRC32  : 98DCCE9F

; File Name   : C:\Users\90542\OneDrive\Masaüstü\nasm_214_c_o\hashtbl.o
; Format      : ELF for Intel 386 (Relocatable)
;
; Source File : 'hashtbl.c'

                .686p
                .mmx
                .model flat
.intel_syntax noprefix

; ===========================================================================

; Segment type: Pure code
; Segment permissions: Read/Execute
_text           segment dword public 'CODE' use32
                assume cs:_text
                ;org 8000000h
                assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing

; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

overflow_general proc near

var_18          = dword ptr -18h
var_14          = dword ptr -14h
var_10          = dword ptr -10h
var_C           = dword ptr -0Ch
var_4           = dword ptr -4
arg_0           = dword ptr  8
arg_4           = dword ptr  0Ch
arg_8           = dword ptr  10h

                push    ebp
                mov     ebp, esp
                sub     esp, 18h
                nop
                mov     eax, [ebp+arg_8]
                cmp     eax, 8
                jl      loc_8000020
                mov     eax, 0
                jmp     locret_80000D4
; ---------------------------------------------------------------------------

loc_8000020:                            ; ...
                mov     eax, [ebp+arg_8]
                shl     eax, 3
                dec     eax
                mov     [ebp+var_4], eax
                mov     eax, [ebp+var_4]
                push    eax
                mov     eax, 2
                mov     ecx, 0
                push    ecx
                push    eax
                call    __ashldi3
                add     esp, 0Ch
                sub     eax, 1
                sbb     edx, 0
                mov     [ebp+var_10], eax
                mov     [ebp+var_C], edx
                mov     eax, [ebp+var_4]
                push    eax
                mov     eax, 2
                mov     ecx, 0
                push    ecx
                push    eax
                call    __ashldi3
                add     esp, 0Ch
                mov     ecx, 0
                sub     ecx, eax
                mov     eax, 0
                sbb     eax, edx
                mov     [ebp+var_18], ecx
                mov     [ebp+var_14], eax
                mov     eax, [ebp+arg_4]
                mov     ecx, [ebp+var_14]
                cmp     eax, ecx
                jg      loc_80000A1
                jnz     loc_800009C
                mov     eax, [ebp+arg_0]
                mov     ecx, [ebp+var_18]
                cmp     eax, ecx
                jnb     loc_80000A1

loc_800009C:                            ; ...
                jmp     loc_80000CF
; ---------------------------------------------------------------------------

loc_80000A1:                            ; ...
                mov     eax, [ebp+arg_4]
                mov     ecx, [ebp+var_C]
                cmp     eax, ecx
                jl      loc_80000C8
                jnz     loc_80000C3
                mov     eax, [ebp+arg_0]
                mov     ecx, [ebp+var_10]
                cmp     eax, ecx
                jbe     loc_80000C8

loc_80000C3:                            ; ...
                jmp     loc_80000CF
; ---------------------------------------------------------------------------

loc_80000C8:                            ; ...
                mov     eax, 0
                jmp     short locret_80000D4
; ---------------------------------------------------------------------------

loc_80000CF:                            ; ...
                mov     eax, 1

locret_80000D4:                         ; ...
                leave
                retn
overflow_general endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

overflow_signed proc near

var_18          = dword ptr -18h
var_14          = dword ptr -14h
var_10          = dword ptr -10h
var_C           = dword ptr -0Ch
var_4           = dword ptr -4
arg_0           = dword ptr  8
arg_4           = dword ptr  0Ch
arg_8           = dword ptr  10h

                push    ebp
                mov     ebp, esp
                sub     esp, 18h
                nop
                mov     eax, [ebp+arg_8]
                cmp     eax, 8
                jl      loc_80000F6
                mov     eax, 0
                jmp     locret_80001AA
; ---------------------------------------------------------------------------

loc_80000F6:                            ; ...
                mov     eax, [ebp+arg_8]
                shl     eax, 3
                dec     eax
                mov     [ebp+var_4], eax
                mov     eax, [ebp+var_4]
                push    eax
                mov     eax, 1
                mov     ecx, 0
                push    ecx
                push    eax
                call    __ashldi3
                add     esp, 0Ch
                sub     eax, 1
                sbb     edx, 0
                mov     [ebp+var_10], eax
                mov     [ebp+var_C], edx
                mov     eax, [ebp+var_4]
                push    eax
                mov     eax, 1
                mov     ecx, 0
                push    ecx
                push    eax
                call    __ashldi3
                add     esp, 0Ch
                mov     ecx, 0
                sub     ecx, eax
                mov     eax, 0
                sbb     eax, edx
                mov     [ebp+var_18], ecx
                mov     [ebp+var_14], eax
                mov     eax, [ebp+arg_4]
                mov     ecx, [ebp+var_14]
                cmp     eax, ecx
                jg      loc_8000177
                jnz     loc_8000172
                mov     eax, [ebp+arg_0]
                mov     ecx, [ebp+var_18]
                cmp     eax, ecx
                jnb     loc_8000177

loc_8000172:                            ; ...
                jmp     loc_80001A5
; ---------------------------------------------------------------------------

loc_8000177:                            ; ...
                mov     eax, [ebp+arg_4]
                mov     ecx, [ebp+var_C]
                cmp     eax, ecx
                jl      loc_800019E
                jnz     loc_8000199
                mov     eax, [ebp+arg_0]
                mov     ecx, [ebp+var_10]
                cmp     eax, ecx
                jbe     loc_800019E

loc_8000199:                            ; ...
                jmp     loc_80001A5
; ---------------------------------------------------------------------------

loc_800019E:                            ; ...
                mov     eax, 0
                jmp     short locret_80001AA
; ---------------------------------------------------------------------------

loc_80001A5:                            ; ...
                mov     eax, 1

locret_80001AA:                         ; ...
                leave
                retn
overflow_signed endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

overflow_unsigned proc near

var_18          = dword ptr -18h
var_14          = dword ptr -14h
var_10          = dword ptr -10h
var_C           = dword ptr -0Ch
var_4           = dword ptr -4
arg_0           = dword ptr  8
arg_4           = dword ptr  0Ch
arg_8           = dword ptr  10h

                push    ebp
                mov     ebp, esp
                sub     esp, 18h
                nop
                mov     eax, [ebp+arg_8]
                cmp     eax, 8
                jl      loc_80001CC
                mov     eax, 0
                jmp     locret_8000264
; ---------------------------------------------------------------------------

loc_80001CC:                            ; ...
                mov     eax, [ebp+arg_8]
                shl     eax, 3
                dec     eax
                mov     [ebp+var_4], eax
                mov     eax, [ebp+var_4]
                push    eax
                mov     eax, 2
                mov     ecx, 0
                push    ecx
                push    eax
                call    __ashldi3
                add     esp, 0Ch
                sub     eax, 1
                sbb     edx, 0
                mov     [ebp+var_10], eax
                mov     [ebp+var_C], edx
                mov     eax, 0
                mov     ecx, 0
                mov     [ebp+var_18], eax
                mov     [ebp+var_14], ecx
                mov     eax, [ebp+arg_4]
                mov     ecx, [ebp+var_14]
                cmp     eax, ecx
                jg      loc_8000231
                jnz     loc_800022C
                mov     eax, [ebp+arg_0]
                mov     ecx, [ebp+var_18]
                cmp     eax, ecx
                jnb     loc_8000231

loc_800022C:                            ; ...
                jmp     loc_800025F
; ---------------------------------------------------------------------------

loc_8000231:                            ; ...
                mov     eax, [ebp+arg_4]
                mov     ecx, [ebp+var_C]
                cmp     eax, ecx
                jl      loc_8000258
                jnz     loc_8000253
                mov     eax, [ebp+arg_0]
                mov     ecx, [ebp+var_10]
                cmp     eax, ecx
                jbe     loc_8000258

loc_8000253:                            ; ...
                jmp     loc_800025F
; ---------------------------------------------------------------------------

loc_8000258:                            ; ...
                mov     eax, 0
                jmp     short locret_8000264
; ---------------------------------------------------------------------------

loc_800025F:                            ; ...
                mov     eax, 1

locret_8000264:                         ; ...
                leave
                retn
overflow_unsigned endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

signed_bits     proc near

arg_0           = dword ptr  8
arg_4           = dword ptr  0Ch
arg_8           = dword ptr  10h

                push    ebp
                mov     ebp, esp
                sub     esp, 0
                nop
                mov     eax, [ebp+arg_8]
                cmp     eax, 40h
                jge     loc_8000307
                mov     eax, [ebp+arg_8]
                push    eax
                mov     eax, 1
                mov     ecx, 0
                push    ecx
                push    eax
                call    __ashldi3
                add     esp, 0Ch
                sub     eax, 1
                sbb     edx, 0
                mov     ecx, [ebp+arg_0]
                and     ecx, eax
                mov     eax, [ebp+arg_4]
                and     eax, edx
                mov     [ebp+arg_0], ecx
                mov     [ebp+arg_4], eax
                mov     eax, [ebp+arg_8]
                dec     eax
                push    eax
                mov     eax, 1
                mov     ecx, 0
                push    ecx
                push    eax
                call    __ashldi3
                add     esp, 0Ch
                mov     ecx, [ebp+arg_0]
                and     ecx, eax
                mov     eax, [ebp+arg_4]
                and     eax, edx
                cmp     eax, 0
                jnz     loc_80002DF
                cmp     ecx, 0
                jz      loc_8000307

loc_80002DF:                            ; ...
                mov     eax, [ebp+arg_8]
                push    eax
                mov     eax, 0FFFFFFFFh
                mov     ecx, 0FFFFFFFFh
                push    ecx
                push    eax
                call    __ashldi3
                add     esp, 0Ch
                mov     ecx, [ebp+arg_0]
                or      ecx, eax
                mov     eax, [ebp+arg_4]
                or      eax, edx
                mov     [ebp+arg_0], ecx
                mov     [ebp+arg_4], eax

loc_8000307:                            ; ...
                mov     eax, [ebp+arg_0]
                mov     edx, [ebp+arg_4]
                leave
                retn
signed_bits     endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

directive_find  proc near

arg_0           = dword ptr  8

                push    ebp
                mov     ebp, esp
                sub     esp, 0
                nop
                mov     eax, [ebp+arg_0]
                push    eax
                mov     eax, offset directive_hash
                push    eax
                call    perfhash_find
                add     esp, 8
                leave
                retn
directive_find  endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

directive_name  proc near               ; ...

var_4           = dword ptr -4
arg_0           = dword ptr  8

                push    ebp
                mov     ebp, esp
                sub     esp, 4
                nop
                mov     eax, [ebp+arg_0]
                sub     eax, 3
                mov     [ebp+var_4], eax
                mov     eax, [ebp+var_4]
                cmp     eax, 26h
                jb      loc_8000356
                mov     eax, 0
                jmp     locret_8000365
; ---------------------------------------------------------------------------

loc_8000356:                            ; ...
                mov     eax, [ebp+var_4]
                shl     eax, 2
                mov     ecx, offset directive_tbl
                add     ecx, eax
                mov     eax, [ecx]

locret_8000365:                         ; ...
                leave
                retn
directive_name  endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

directive_dname proc near

var_4           = dword ptr -4
arg_0           = dword ptr  8

                push    ebp
                mov     ebp, esp
                sub     esp, 4
                nop
                mov     eax, [ebp+arg_0]
                push    eax
                call    directive_name
                add     esp, 4
                mov     [ebp+var_4], eax
                mov     eax, [ebp+var_4]
                cmp     eax, 0
                jz      loc_8000391
                jmp     loc_80003A2
; ---------------------------------------------------------------------------

loc_8000391:                            ; ...
                mov     eax, [ebp+arg_0]
                push    eax
                call    invalid_enum_str
                add     esp, 4
                jmp     locret_80003A5
; ---------------------------------------------------------------------------

loc_80003A2:                            ; ...
                mov     eax, [ebp+var_4]

locret_80003A5:                         ; ...
                leave
                retn
directive_dname endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

is_class        proc near               ; ...

arg_0           = dword ptr  8
arg_4           = dword ptr  0Ch
arg_8           = dword ptr  10h
arg_C           = dword ptr  14h

                push    ebp
                mov     ebp, esp
                sub     esp, 0
                nop
                mov     eax, [ebp+arg_8]
                xor     eax, 0FFFFFFFFh
                mov     ecx, [ebp+arg_C]
                xor     ecx, 0FFFFFFFFh
                mov     edx, [ebp+arg_0]
                and     edx, eax
                mov     eax, [ebp+arg_4]
                and     eax, ecx
                cmp     eax, 0
                jnz     loc_80003D9
                cmp     edx, 0
                jz      loc_80003E0

loc_80003D9:                            ; ...
                mov     eax, 0
                jmp     short locret_80003E5
; ---------------------------------------------------------------------------

loc_80003E0:                            ; ...
                mov     eax, 1

locret_80003E5:                         ; ...
                leave
                retn
is_class        endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

is_reg_class    proc near

arg_0           = dword ptr  8
arg_4           = dword ptr  0Ch
arg_8           = dword ptr  10h
arg_C           = dword ptr  14h

                push    ebp
                mov     ebp, esp
                sub     esp, 0
                nop
                mov     eax, [ebp+arg_C]
                cmp     eax, 0
                jb      loc_800045B
                jnz     loc_800040F
                mov     eax, [ebp+arg_8]
                cmp     eax, 1
                jb      loc_800045B

loc_800040F:                            ; ...
                mov     eax, [ebp+arg_C]
                cmp     eax, 0
                ja      loc_800045B
                jnz     loc_8000430
                mov     eax, [ebp+arg_8]
                cmp     eax, 0F0h
                ja      loc_800045B

loc_8000430:                            ; ...
                mov     eax, [ebp+arg_8]
                shl     eax, 3
                mov     ecx, offset nasm_reg_flags
                add     ecx, eax
                mov     eax, [ecx]
                add     ecx, 4
                mov     edx, [ecx]
                push    edx
                push    eax
                mov     eax, [ebp+arg_0]
                mov     ecx, [ebp+arg_4]
                push    ecx
                push    eax
                call    is_class
                add     esp, 10h
                jmp     locret_8000460
; ---------------------------------------------------------------------------

loc_800045B:                            ; ...
                mov     eax, 0

locret_8000460:                         ; ...
                leave
                retn
is_reg_class    endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

nasm_skip_identifier proc near

var_4           = dword ptr -4
arg_0           = dword ptr  8

                push    ebp
                mov     ebp, esp
                sub     esp, 4
                nop
                mov     eax, [ebp+arg_0]
                mov     [ebp+var_4], eax
                mov     eax, [ebp+var_4]
                mov     ecx, eax
                inc     eax
                mov     [ebp+var_4], eax
                movsx   eax, byte ptr [ecx]
                and     eax, 0FFh
                push    eax
                call    isalpha
                add     esp, 4
                cmp     eax, 0
                jnz     loc_80004EF
                mov     eax, [ebp+var_4]
                mov     ecx, eax
                inc     eax
                mov     [ebp+var_4], eax
                movsx   eax, byte ptr [ecx]
                cmp     eax, 5Fh
                jz      loc_80004EF
                mov     eax, [ebp+var_4]
                mov     ecx, eax
                inc     eax
                mov     [ebp+var_4], eax
                movsx   eax, byte ptr [ecx]
                cmp     eax, 2Eh
                jz      loc_80004EF
                mov     eax, [ebp+var_4]
                mov     ecx, eax
                inc     eax
                mov     [ebp+var_4], eax
                movsx   eax, byte ptr [ecx]
                cmp     eax, 3Fh
                jz      loc_80004EF
                mov     eax, [ebp+var_4]
                mov     ecx, eax
                inc     eax
                mov     [ebp+var_4], eax
                movsx   eax, byte ptr [ecx]
                cmp     eax, 40h
                jz      loc_80004EF
                jmp     loc_80004F4
; ---------------------------------------------------------------------------

loc_80004EF:                            ; ...
                jmp     loc_8000501
; ---------------------------------------------------------------------------

loc_80004F4:                            ; ...
                mov     eax, 0
                mov     [ebp+var_4], eax
                jmp     loc_80005E6
; ---------------------------------------------------------------------------

loc_8000501:                            ; ...
                mov     eax, [ebp+var_4]
                mov     ecx, eax
                inc     eax
                mov     [ebp+var_4], eax
                movsx   eax, byte ptr [ecx]
                and     eax, 0FFh
                push    eax
                call    isalpha
                add     esp, 4
                cmp     eax, 0
                jnz     loc_80005E1
                mov     eax, [ebp+var_4]
                mov     ecx, eax
                inc     eax
                mov     [ebp+var_4], eax
                movsx   eax, byte ptr [ecx]
                cmp     eax, 5Fh
                jz      loc_80005E1
                mov     eax, [ebp+var_4]
                mov     ecx, eax
                inc     eax
                mov     [ebp+var_4], eax
                movsx   eax, byte ptr [ecx]
                cmp     eax, 2Eh
                jz      loc_80005E1
                mov     eax, [ebp+var_4]
                mov     ecx, eax
                inc     eax
                mov     [ebp+var_4], eax
                movsx   eax, byte ptr [ecx]
                cmp     eax, 3Fh
                jz      loc_80005E1
                mov     eax, [ebp+var_4]
                mov     ecx, eax
                inc     eax
                mov     [ebp+var_4], eax
                movsx   eax, byte ptr [ecx]
                cmp     eax, 40h
                jz      loc_80005E1
                mov     eax, [ebp+var_4]
                mov     ecx, eax
                inc     eax
                mov     [ebp+var_4], eax
                movsx   eax, byte ptr [ecx]
                and     eax, 0FFh
                push    eax
                call    isdigit
                add     esp, 4
                cmp     eax, 0
                jnz     loc_80005E1
                mov     eax, [ebp+var_4]
                mov     ecx, eax
                inc     eax
                mov     [ebp+var_4], eax
                movsx   eax, byte ptr [ecx]
                cmp     eax, 24h
                jz      loc_80005E1
                mov     eax, [ebp+var_4]
                mov     ecx, eax
                inc     eax
                mov     [ebp+var_4], eax
                movsx   eax, byte ptr [ecx]
                cmp     eax, 23h
                jz      loc_80005E1
                mov     eax, [ebp+var_4]
                mov     ecx, eax
                inc     eax
                mov     [ebp+var_4], eax
                movsx   eax, byte ptr [ecx]
                cmp     eax, 7Eh
                jz      loc_80005E1
                jmp     loc_80005E6
; ---------------------------------------------------------------------------

loc_80005E1:                            ; ...
                jmp     loc_8000501
; ---------------------------------------------------------------------------

loc_80005E6:                            ; ...
                mov     eax, [ebp+var_4]
                leave
                retn
nasm_skip_identifier endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

is_register     proc near

arg_0           = dword ptr  8

                push    ebp
                mov     ebp, esp
                sub     esp, 0
                nop
                mov     eax, [ebp+arg_0]
                cmp     eax, 1
                jl      loc_8000617
                mov     eax, [ebp+arg_0]
                cmp     eax, 0F1h
                jge     loc_8000617
                mov     eax, 1
                jmp     short locret_800061C
; ---------------------------------------------------------------------------

loc_8000617:                            ; ...
                mov     eax, 0

locret_800061C:                         ; ...
                leave
                retn
is_register     endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

get_cond_opcode proc near

arg_0           = dword ptr  8

                push    ebp
                mov     ebp, esp
                sub     esp, 0
                nop
                mov     eax, [ebp+arg_0]
                mov     ecx, offset ccode_opcodes
                add     ecx, eax
                movzx   eax, byte ptr [ecx]
                leave
                retn
get_cond_opcode endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

alloc_table     proc near               ; ...

bytes           = dword ptr -4
newsize         = dword ptr  8

                push    ebp             ; struct hash_tbl_node {
                                        ;     uint64_t hash;
                                        ;     const char *key;
                                        ;     void *data;
                                        ; };
                                        ;
                                        ; static struct hash_tbl_node *alloc_table(size_t newsize)
                mov     ebp, esp
                sub     esp, 4
                nop
                mov     eax, [ebp+newsize]
                shl     eax, 4
                mov     [ebp+bytes], eax ; size_t bytes = newsize * sizeof(struct hash_tbl_node);
                mov     eax, [ebp+bytes]
                push    eax
                call    nasm_zalloc     ; return nasm_zalloc(bytes);
                add     esp, 4
                leave
                retn
alloc_table     endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

                public hash_init
hash_init       proc near

tmp             = dword ptr -4
head            = dword ptr  8
size            = dword ptr  0Ch

                push    ebp             ; struct hash_table {
                                        ;     struct hash_tbl_node *table;
                                        ;     size_t load;
                                        ;     size_t size;
                                        ;     size_t max_load;
                                        ; };
                                        ;
                                        ; void hash_init(struct hash_table *head, size_t size)
                mov     ebp, esp
                sub     esp, 4
                nop
                mov     eax, [ebp+size] ; #define is_power2(v) ((v) && ((v) & ((v) - 1)) == 0)
                cmp     eax, 0
                jz      hi_1
                mov     eax, [ebp+size]
                dec     eax
                mov     ecx, [ebp+size]
                and     ecx, eax
                cmp     ecx, 0
                jnz     hi_1
                jmp     hi_2
; ---------------------------------------------------------------------------

hi_1:                                   ; ...
                jmp     hi_3
; ---------------------------------------------------------------------------

hi_2:                                   ; ...
                jmp     hi_4
; ---------------------------------------------------------------------------

hi_3:                                   ; ...
                mov     eax, offset L_196 ; "is_power2(size)"
                push    eax
                mov     eax, 65         ; (hashtbl.c line 65)
                push    eax
                mov     eax, offset L_195 ; "hashtbl.c"
                push    eax
                call    nasm_assert_failed ; nasm_assert(is_power2(size));
                add     esp, 12

hi_4:                                   ; ...
                mov     eax, [ebp+head]
                mov     ecx, [ebp+size]
                push    ecx
                mov     [ebp+tmp], eax
                call    alloc_table
                add     esp, 4
                mov     ecx, [ebp+tmp]
                mov     [ecx], eax      ; head->table = alloc_table(size);
                mov     eax, [ebp+head]
                add     eax, 4
                mov     ecx, 0
                mov     [eax], ecx      ; head->load = 0;
                mov     eax, [ebp+head]
                add     eax, 8
                mov     ecx, [ebp+size]
                mov     [eax], ecx      ; head->size = size;
                mov     eax, [ebp+head]
                add     eax, 12
                mov     ecx, [ebp+size]
                shr     ecx, 1          ; #define HASH_MAX_LOAD 2
                                        ;        /* Higher = more memory-efficient, slower */
                                        ; #define hash_max_load(size)
                                        ;        ((size) * (HASH_MAX_LOAD - 1) / HASH_MAX_LOAD)
                mov     [eax], ecx      ; head->max_load = hash_max_load(size);
                leave
                retn
hash_init       endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

                public hash_find
hash_find       proc near

tmp_h           = dword ptr -28h
tmp             = dword ptr -24h
incr            = dword ptr -1Ch
pos             = dword ptr -18h
mask            = dword ptr -14h
hash            = dword ptr -10h
hash_h          = dword ptr -0Ch
tbl             = dword ptr -8
np              = dword ptr -4
head            = dword ptr  8
key             = dword ptr  0Ch
insert          = dword ptr  10h

                push    ebp             ; void **hash_find(struct hash_table *head, const char *key,
                                        ;                  struct hash_insert *insert)
                mov     ebp, esp
                sub     esp, 40         ; struct hash_tbl_node *np;
                nop
                mov     eax, [ebp+head]
                mov     ecx, [eax]
                mov     [ebp+tbl], ecx  ; struct hash_tbl_node *tbl = head->table;
                mov     eax, [ebp+key]  ; #define hash_calc(key) crc64(CRC64_INIT, (key))
                push    eax
                mov     eax, 0FFFFFFFFh ; CRC64_INIT
                mov     ecx, 0FFFFFFFFh
                push    ecx
                push    eax
                call    crc64
                add     esp, 12
                mov     [ebp+hash], eax ; uint64_t hash = hash_calc(key);
                mov     [ebp+hash_h], edx
                mov     eax, [ebp+head]
                add     eax, 8          ; head->size
                mov     ecx, [eax]      ; #define hash_mask(size) ((size) - 1)
                dec     ecx
                mov     [ebp+mask], ecx ; size_t mask = hash_mask(head->size);
                mov     eax, [ebp+mask]
                mov     ecx, 0
                mov     edx, [ebp+hash] ; #define hash_pos(hash, mask) ((hash) & (mask))
                and     edx, eax
                mov     eax, [ebp+hash_h]
                and     eax, ecx
                mov     [ebp+pos], edx  ; size_t pos = hash_pos(hash, mask);
                mov     eax, [ebp+hash_h]
                mov     ecx, 0
                mov     edx, [ebp+mask]
                mov     [ebp+tmp_h], eax
                mov     [ebp+tmp], ecx
                mov     ecx, 0
                mov     eax, [ebp+tmp_h] ; #define hash_inc(hash, mask)
                                        ;    ((((hash) >> 32) & (mask)) | 1) /* always odd */
                and     eax, edx        ; ((hash) >> 32) & mask
                mov     edx, [ebp+tmp]
                and     edx, ecx
                or      eax, 1          ; | 1
                mov     [ebp+incr], eax ; size_t inc = hash_inc(hash, mask);

hf_1:                                   ; ...
                mov     eax, [ebp+pos]  ; while ((np = &tbl[pos])->key) {
                shl     eax, 4
                mov     ecx, [ebp+tbl]
                add     ecx, eax
                mov     [ebp+np], ecx
                add     ecx, 8
                mov     eax, [ecx]
                cmp     eax, 0
                jz      hf_4
                mov     eax, [ebp+np]   ; if (hash == np->hash && !strcmp(key, np->key))
                mov     ecx, [eax]
                add     eax, 4
                mov     edx, [eax]
                mov     eax, [ebp+hash_h]
                cmp     eax, edx
                jnz     hf_3
                mov     eax, [ebp+hash]
                cmp     eax, ecx
                jnz     hf_3
                mov     eax, [ebp+np]
                add     eax, 8
                mov     ecx, [eax]
                push    ecx
                mov     eax, [ebp+key]
                push    eax
                call    strcmp
                add     esp, 8
                cmp     eax, 0
                jz      hf_2            ; !strcmp(key, np->key)
                jmp     hf_3
; ---------------------------------------------------------------------------

hf_2:                                   ; ...
                mov     eax, [ebp+np]   ; return &np->data;
                add     eax, 12
                jmp     hf_6
; ---------------------------------------------------------------------------

hf_3:                                   ; ...
                mov     eax, [ebp+pos]  ; #define hash_pos_next(pos, inc, mask) (((pos) + (inc)) & (mask))
                mov     ecx, [ebp+incr]
                add     eax, ecx
                mov     ecx, [ebp+mask]
                and     eax, ecx
                mov     [ebp+pos], eax  ; pos = hash_pos_next(pos, inc, mask);
                jmp     short hf_1
; ---------------------------------------------------------------------------

hf_4:                                   ; ...
                mov     eax, [ebp+insert] ; /* Not found. Store info for insert if requested. */
                cmp     eax, 0          ; if (insert) {
                jz      hf_5
                mov     eax, [ebp+insert] ; struct hash_insert {
                                        ;     uint64_t hash;
                                        ;     struct hash_table *head;
                                        ;     struct hash_tbl_node *where;
                                        ; };
                add     eax, 8
                mov     ecx, [ebp+head]
                mov     [eax], ecx      ; insert->head = head;
                mov     eax, [ebp+insert]
                mov     ecx, [ebp+hash]
                mov     edx, [ebp+hash_h]
                mov     [eax], ecx      ; insert->hash = hash;
                add     eax, 4
                mov     [eax], edx      ; insert->where = np;
                mov     eax, [ebp+insert]
                add     eax, 12
                mov     ecx, [ebp+np]
                mov     [eax], ecx

hf_5:                                   ; ...
                mov     eax, 0          ; return NULL;

hf_6:                                   ; ...
                leave
                retn
hash_find       endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

                public hash_findi
hash_findi      proc near

tmp_h           = dword ptr -28h
tmp             = dword ptr -24h
incr            = dword ptr -1Ch
pos             = dword ptr -18h
mask            = dword ptr -14h
hash            = dword ptr -10h
hash_h          = dword ptr -0Ch
tbl             = dword ptr -8
np              = dword ptr -4
head            = dword ptr  8
key             = dword ptr  0Ch
insert          = dword ptr  10h

                push    ebp             ; /* Same as hash_find, but for case-insensitive hashing. */
                mov     ebp, esp
                sub     esp, 40         ; void **hash_findi(struct hash_table *head, const char *key,
                                        ;                   struct hash_insert *insert)
                nop
                mov     eax, [ebp+head] ; struct hash_tbl_node *np;
                mov     ecx, [eax]
                mov     [ebp+tbl], ecx  ; struct hash_tbl_node *tbl = head->table;
                mov     eax, [ebp+key]
                push    eax
                mov     eax, 0FFFFFFFFh ; CRC64_INIT
                mov     ecx, 0FFFFFFFFh
                push    ecx
                push    eax
                call    crc64i          ; #define hash_calci(key) crc64i(CRC64_INIT, (key))
                add     esp, 12
                mov     [ebp+hash], eax ; uint64_t hash = hash_calci(key);
                mov     [ebp+hash_h], edx
                mov     eax, [ebp+head]
                add     eax, 8
                mov     ecx, [eax]
                dec     ecx
                mov     [ebp+mask], ecx ; size_t mask = hash_mask(head->size);
                mov     eax, [ebp+mask]
                mov     ecx, 0
                mov     edx, [ebp+hash]
                and     edx, eax
                mov     eax, [ebp+hash_h]
                and     eax, ecx
                mov     [ebp+pos], edx  ; size_t pos = hash_pos(hash, mask);
                mov     eax, [ebp+hash_h]
                mov     ecx, 0
                mov     edx, [ebp+mask]
                mov     [ebp+tmp_h], eax
                mov     [ebp+tmp], ecx
                mov     ecx, 0
                mov     eax, [ebp+tmp_h]
                and     eax, edx
                mov     edx, [ebp+tmp]
                and     edx, ecx
                or      eax, 1
                mov     [ebp+incr], eax ; size_t inc = hash_inc(hash, mask);

hfi_1:                                  ; ...
                mov     eax, [ebp+pos]  ; while ((np = &tbl[pos])->key) {
                shl     eax, 4
                mov     ecx, [ebp+tbl]
                add     ecx, eax
                mov     [ebp+np], ecx
                add     ecx, 8
                mov     eax, [ecx]
                cmp     eax, 0
                jz      hfi_4
                mov     eax, [ebp+np]   ; if (hash == np->hash && !nasm_stricmp(key, np->key))
                mov     ecx, [eax]
                add     eax, 4
                mov     edx, [eax]
                mov     eax, [ebp+hash_h]
                cmp     eax, edx
                jnz     hfi_3
                mov     eax, [ebp+hash]
                cmp     eax, ecx
                jnz     hfi_3
                mov     eax, [ebp+np]
                add     eax, 8
                mov     ecx, [eax]
                push    ecx
                mov     eax, [ebp+key]
                push    eax
                call    nasm_stricmp
                add     esp, 8
                cmp     eax, 0
                jz      hfi_2           ; !nasm_stricmp(key, np->key)
                jmp     hfi_3
; ---------------------------------------------------------------------------

hfi_2:                                  ; ...
                mov     eax, [ebp+np]   ; return &np->data;
                add     eax, 12
                jmp     hfi_6
; ---------------------------------------------------------------------------

hfi_3:                                  ; ...
                mov     eax, [ebp+pos]
                mov     ecx, [ebp+incr]
                add     eax, ecx
                mov     ecx, [ebp+mask]
                and     eax, ecx
                mov     [ebp+pos], eax  ; pos = hash_pos_next(pos, inc, mask);
                jmp     short hfi_1
; ---------------------------------------------------------------------------

hfi_4:                                  ; ...
                mov     eax, [ebp+insert] ; /* Not found. Store info for insert if requested. */
                cmp     eax, 0          ; if (insert) {
                jz      hfi_5
                mov     eax, [ebp+insert]
                add     eax, 8
                mov     ecx, [ebp+head]
                mov     [eax], ecx      ; insert->head = head;
                mov     eax, [ebp+insert]
                mov     ecx, [ebp+hash]
                mov     edx, [ebp+hash_h]
                mov     [eax], ecx
                add     eax, 4
                mov     [eax], edx      ; insert->hash = hash;
                mov     eax, [ebp+insert]
                add     eax, 12
                mov     ecx, [ebp+np]
                mov     [eax], ecx      ; insert->where = np;

hfi_5:                                  ; ...
                mov     eax, 0          ; return NULL;

hfi_6:                                  ; ...
                leave
                retn
hash_findi      endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

                public hash_add
hash_add        proc near

tmp4            = dword ptr -44h
tmp3_h          = dword ptr -40h
tmp3            = dword ptr -3Ch
incr            = dword ptr -34h
tmp2            = dword ptr -30h
tmp2_h          = dword ptr -2Ch
pos             = dword ptr -28h
i               = dword ptr -24h
xp              = dword ptr -20h
op              = dword ptr -1Ch
mask            = dword ptr -18h
newtbl          = dword ptr -14h
newsize         = dword ptr -10h
tmp1            = dword ptr -0Ch
np              = dword ptr -8
head            = dword ptr -4
insert          = dword ptr  8
key             = dword ptr  0Ch
data            = dword ptr  10h

                push    ebp             ; /* Insert node. Return a pointer to the "data" element of the newly
                                        ;    created hash node. */
                                        ;
                                        ; void **hash_add(struct hash_insert *insert, const char *key, void *data)
                mov     ebp, esp
                sub     esp, 68         ; struct hash_tbl_node {
                                        ;     uint64_t hash;
                                        ;     const char *key;
                                        ;     void *data;
                                        ; };
                nop                     ; struct hash_insert {
                                        ;     uint64_t hash;
                                        ;     struct hash_table *head;
                                        ;     struct hash_tbl_node *where;
                                        ; };
                                        ; struct hash_table {
                                        ;     struct hash_tbl_node *table;
                                        ;     size_t load;
                                        ;     size_t size;
                                        ;     size_t max_load;
                                        ; };
                mov     eax, [ebp+insert]
                add     eax, 8
                mov     ecx, [eax]
                mov     [ebp+head], ecx ; struct hash_table *head = insert->head;
                mov     eax, [ebp+insert]
                add     eax, 12
                mov     ecx, [eax]
                mov     [ebp+np], ecx   ; struct hash_tbl_node *np = insert->where;
                mov     eax, [ebp+np]
                mov     ecx, [ebp+insert] ; /* Insert node. We can always do this, even if we need to
                                        ;    rebalance immediately after. */
                mov     edx, [ecx]
                add     ecx, 4
                mov     [ebp+tmp1], eax ; *np
                mov     eax, [ecx]
                mov     ecx, [ebp+tmp1]
                mov     [ecx], edx      ; hash
                add     ecx, 4          ; hash_h
                mov     [ecx], eax      ; np->hash = insert->hash;
                mov     eax, [ebp+np]
                add     eax, 8
                mov     ecx, [ebp+key]
                mov     [eax], ecx      ; np->key = key;
                mov     eax, [ebp+np]
                add     eax, 12
                mov     ecx, [ebp+data]
                mov     [eax], ecx      ; np->data = data;
                mov     eax, [ebp+head]
                add     eax, 4
                mov     ecx, [eax]      ; head->load
                inc     ecx
                mov     [eax], ecx      ; ++head->load
                mov     eax, [ebp+head]
                add     eax, 12
                mov     edx, [eax]      ; head->max_load
                cmp     ecx, edx        ; if (++head->load > head->max_load) {
                jbe     ha_9
                mov     eax, [ebp+head] ; /* Need to expand the table */
                add     eax, 8
                mov     ecx, [eax]      ; head->size
                shl     ecx, 1          ; #define hash_expand(size) ((size) << 1)
                mov     [ebp+newsize], ecx ; size_t newsize = hash_expand(head->size);
                mov     eax, [ebp+newsize]
                push    eax
                call    alloc_table
                add     esp, 4
                mov     [ebp+newtbl], eax ; struct hash_tbl_node *newtbl = alloc_table(newsize);
                mov     eax, [ebp+newsize]
                dec     eax             ; #define hash_mask(size) ((size) - 1)
                mov     [ebp+mask], eax ; size_t mask = hash_mask(newsize);
                mov     eax, [ebp+head]
                mov     ecx, [eax]      ; struct hash_tbl_node *op, *xp;
                cmp     ecx, 0          ; if (head->table) {
                jz      ha_8
                mov     eax, 0          ; size_t i;
                mov     [ebp+i], eax    ; i = 0
                mov     eax, [ebp+head]
                mov     ecx, [eax]
                mov     [ebp+op], ecx   ; op = head->table

ha_1:                                   ; ...
                mov     eax, [ebp+head] ; /* Rebalance all the entries */
                                        ; for (i = 0, op = head->table; i < head->size; i++, op++) {
                add     eax, 8
                mov     ecx, [ebp+i]
                mov     edx, [eax]
                cmp     ecx, edx        ; (if) i < head->size;
                jnb     ha_7
                jmp     ha_3
; ---------------------------------------------------------------------------

ha_2:                                   ; ...
                mov     eax, [ebp+i]    ; (next) i++
                mov     ecx, eax
                inc     eax
                mov     [ebp+i], eax
                mov     eax, [ebp+op]   ; (next) op++
                mov     ecx, eax
                add     eax, 16         ; + (hash_tbl_node structure size)
                mov     [ebp+op], eax
                jmp     short ha_1
; ---------------------------------------------------------------------------

ha_3:                                   ; ...
                mov     eax, [ebp+op]   ; if (op->key) {
                add     eax, 8
                mov     ecx, [eax]
                cmp     ecx, 0
                jz      ha_6
                mov     eax, [ebp+op]
                mov     ecx, [ebp+mask]
                mov     edx, 0          ; #define hash_pos(hash, mask) ((hash) & (mask))
                mov     [ebp+tmp2], ecx ; mask
                mov     [ebp+tmp2_h], edx ; mask_h
                mov     edx, [eax]      ; op->hash
                add     eax, 4
                mov     ecx, [eax]      ; op->hash_h
                mov     eax, [ebp+tmp2]
                and     edx, eax
                mov     eax, [ebp+tmp2_h]
                and     ecx, eax
                mov     [ebp+pos], edx  ; size_t pos = hash_pos(op->hash, mask);
                mov     eax, [ebp+op]
                mov     ecx, [eax]      ; op->hash
                add     eax, 4
                mov     edx, [eax]      ; op->hash_h
                mov     eax, 0
                mov     ecx, [ebp+mask] ; #define hash_inc(hash, mask) ((((hash) >> 32) & (mask)) | 1)
                mov     [ebp+tmp3_h], edx
                mov     [ebp+tmp3], eax
                mov     eax, 0
                mov     edx, [ebp+tmp3_h]
                and     edx, ecx        ; ((hash) >> 32) & mask
                mov     ecx, [ebp+tmp3]
                and     ecx, eax
                or      edx, 1          ; | 1
                mov     [ebp+incr], edx ; size_t inc = hash_inc(op->hash, mask);

ha_4:                                   ; ...
                mov     eax, [ebp+pos]  ; while ((xp = &newtbl[pos])->key)
                shl     eax, 4
                mov     ecx, [ebp+newtbl]
                add     ecx, eax
                mov     [ebp+xp], ecx
                add     ecx, 8
                mov     eax, [ecx]
                cmp     eax, 0
                jz      ha_5
                mov     eax, [ebp+pos]  ; #define hash_pos_next(pos, inc, mask) (((pos) + (inc)) & (mask))
                mov     ecx, [ebp+incr]
                add     eax, ecx
                mov     ecx, [ebp+mask]
                and     eax, ecx
                mov     [ebp+pos], eax  ; pos = hash_pos_next(pos, inc, mask);
                jmp     short ha_4
; ---------------------------------------------------------------------------

ha_5:                                   ; ...
                mov     eax, [ebp+xp]
                mov     ecx, [ebp+op]
                mov     edx, 16
                push    edx
                push    ecx
                push    eax
                mov     [ebp+tmp4], ecx
                call    memmove         ; *xp = *op;
                add     esp, 12
                mov     eax, [ebp+op]   ; if (op == np)
                mov     ecx, [ebp+np]
                cmp     eax, ecx
                jnz     ha_6
                mov     eax, [ebp+xp]
                mov     [ebp+np], eax   ; np = xp;

ha_6:                                   ; ...
                jmp     ha_2
; ---------------------------------------------------------------------------

ha_7:                                   ; ...
                mov     eax, [ebp+head]
                mov     ecx, [eax]
                push    ecx
                call    nasm_free       ; nasm_free(head->table);
                add     esp, 4

ha_8:                                   ; ...
                mov     eax, [ebp+head]
                mov     ecx, [ebp+newtbl]
                mov     [eax], ecx      ; head->table = newtbl;
                mov     eax, [ebp+head]
                add     eax, 8
                mov     ecx, [ebp+newsize]
                mov     [eax], ecx      ; head->size = newsize;
                mov     eax, [ebp+head]
                add     eax, 12
                mov     ecx, [ebp+newsize]
                shr     ecx, 1          ; #define hash_max_load(size)
                                        ;    ((size) * (HASH_MAX_LOAD - 1) / HASH_MAX_LOAD)
                mov     [eax], ecx      ; head->max_load = hash_max_load(newsize);

ha_9:                                   ; ...
                mov     eax, [ebp+np]
                add     eax, 12         ; return &np->data;
                leave
                retn
hash_add        endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

                public hash_iterate
hash_iterate    proc near               ; ...

tmp             = dword ptr -0Ch
ep              = dword ptr -8
np              = dword ptr -4
head            = dword ptr  8
iterator        = dword ptr  0Ch
key             = dword ptr  10h

                push    ebp             ; /* Iterate over all members of a hash set.
                                        ;    For the first call, iterator should be initialized to NULL.
                                        ;    Returns the data pointer, or NULL on failure. */
                                        ;
                                        ; void *hash_iterate(const struct hash_table *head,
                                        ;                    struct hash_tbl_node **iterator,
                                        ;                    const char **key)
                mov     ebp, esp
                sub     esp, 12
                nop
                mov     eax, [ebp+iterator]
                mov     ecx, [eax]
                mov     [ebp+np], ecx   ; struct hash_tbl_node *np = *iterator;
                mov     eax, [ebp+head]
                mov     ecx, [ebp+head]
                add     ecx, 8
                mov     edx, [ecx]
                shl     edx, 4
                mov     ecx, [eax]
                add     ecx, edx
                mov     [ebp+ep], ecx   ; struct hash_tbl_node *ep = head->table + head->size;
                mov     eax, [ebp+np]
                cmp     eax, 0          ; if (!np) {
                jz      hite_1
                jmp     hite_3
; ---------------------------------------------------------------------------

hite_1:                                 ; ...
                mov     eax, [ebp+head]
                mov     ecx, [eax]
                mov     [ebp+np], ecx   ; np = head->table;
                mov     eax, [ebp+np]   ; if (!np)
                cmp     eax, 0
                jz      hite_2
                jmp     hite_3
; ---------------------------------------------------------------------------

hite_2:                                 ; ...
                mov     eax, 0          ; return NULL; /* Uninitialized table */
                jmp     hite_8
; ---------------------------------------------------------------------------

hite_3:                                 ; ...
                mov     eax, [ebp+np]   ; while (np < ep) {
                mov     ecx, [ebp+ep]
                cmp     eax, ecx
                jnb     hite_6
                mov     eax, [ebp+np]
                add     eax, 8          ; np->key
                mov     ecx, [eax]
                cmp     ecx, 0          ; if (np->key) {
                jz      hite_5
                mov     eax, [ebp+iterator]
                mov     ecx, [ebp+np]
                add     ecx, 16
                mov     [eax], ecx      ; *iterator = np + 1;
                mov     eax, [ebp+key]
                cmp     eax, 0          ; if (key)
                jz      hite_4
                mov     eax, [ebp+key]
                mov     ecx, [ebp+np]
                add     ecx, 8
                mov     edx, [ecx]
                mov     [eax], edx      ; *key = np->key;

hite_4:                                 ; ...
                mov     eax, [ebp+np]
                add     eax, 12
                mov     [ebp+tmp], eax
                mov     eax, [ebp+tmp]
                mov     eax, [eax]      ; return np->data;
                jmp     hite_8
; ---------------------------------------------------------------------------

hite_5:                                 ; ...
                mov     eax, [ebp+np]
                mov     ecx, eax
                add     eax, 16         ; + structure size
                mov     [ebp+np], eax   ; np++;
                jmp     short hite_3
; ---------------------------------------------------------------------------

hite_6:                                 ; ...
                mov     eax, [ebp+iterator]
                mov     ecx, 0
                mov     [eax], ecx      ; *iterator = NULL;
                mov     eax, [ebp+key]
                cmp     eax, 0          ; if (key)
                jz      hite_7
                mov     eax, [ebp+key]
                mov     ecx, 0
                mov     [eax], ecx      ; *key = NULL;

hite_7:                                 ; ...
                mov     eax, 0

hite_8:                                 ; ...
                leave                   ; return NULL;
                retn
hash_iterate    endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

                public hash_free
hash_free       proc near               ; ...

p               = dword ptr -4
head            = dword ptr  8

                push    ebp             ; /* Free the hash itself. Doesn't free the data elements; use
                                        ;    hash_iterate() to do that first, if needed.
                                        ;    This function is normally used when the hash data entries are
                                        ;    either freed separately, or compound objects which can't be
                                        ;    freed in a single operation. */
                                        ;
                                        ; void hash_free(struct hash_table *head)
                mov     ebp, esp
                sub     esp, 4
                nop
                mov     eax, [ebp+head]
                mov     ecx, [eax]
                mov     [ebp+p], ecx    ; void *p = head->table;
                mov     eax, [ebp+head]
                mov     ecx, 0
                mov     [eax], ecx      ; head->table = NULL;
                mov     eax, [ebp+p]
                push    eax
                call    nasm_free       ; nasm_free(p);
                add     esp, 4
                leave
                retn
hash_free       endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

                public hash_free_all
hash_free_all   proc near

d               = dword ptr -0Ch
keyp            = dword ptr -8
iter            = dword ptr -4
head            = dword ptr  8
free_keys       = dword ptr  0Ch

                push    ebp             ; /* Frees the hash *and* all data elements. This is applicable only in
                                        ;    the case where the data element is a single allocation. If the
                                        ;    second argument is false, the key string is part of the data
                                        ;    allocation or belongs to an allocation which will be freed
                                        ;    separately, if it is true the keys are also freed. */
                                        ;
                                        ; void hash_free_all(struct hash_table *head, bool free_keys)
                mov     ebp, esp
                sub     esp, 12
                nop
                mov     eax, 0
                mov     [ebp+iter], eax ; struct hash_tbl_node *iter = NULL;

hfa_1:                                  ; ...
                lea     eax, [ebp+keyp] ; const char *keyp;
                push    eax
                lea     eax, [ebp+iter]
                push    eax
                mov     eax, [ebp+head]
                push    eax
                call    hash_iterate
                add     esp, 12         ; void *d;
                mov     [ebp+d], eax
                cmp     eax, 0          ; while ((d = hash_iterate(head, &iter, &keyp))) {
                jz      hfa_3
                mov     eax, [ebp+d]
                push    eax
                call    nasm_free       ; nasm_free(d);
                add     esp, 4
                mov     eax, [ebp+free_keys] ; if (free_keys)
                cmp     eax, 0
                jz      hfa_2
                mov     eax, [ebp+keyp]
                push    eax
                call    nasm_free       ; nasm_free((void *)keyp);
                add     esp, 4

hfa_2:                                  ; ...
                jmp     short hfa_1
; ---------------------------------------------------------------------------

hfa_3:                                  ; ...
                mov     eax, [ebp+head]
                push    eax
                call    hash_free       ; hash_free(head);
                add     esp, 4
                leave
                retn
hash_free_all   endp

_text           ends

; ===========================================================================

; Segment type: Pure data
; Segment permissions: Read/Write
_data           segment dword public 'DATA' use32
                assume cs:_data
                ;org 8000C8Ch
ccode_opcodes   db    7                 ; ...
                db    3
                db    2
                db    6
                db    2
                db    4
                db  0Fh
                db  0Dh
                db  0Ch
                db  0Eh
                db    6
                db    2
                db    3
                db    7
                db    3
                db    5
                db  0Eh
                db  0Ch
                db  0Dh
                db  0Fh
                db    1
                db  0Bh
                db    9
                db    5
                db    0
                db  0Ah
                db  0Ah
                db  0Bh
                db    8
                db    4
L_195           db 'hashtbl.c',0        ; ...
L_196           db 'is_power2(size)',0  ; ...
_data           ends

; ===========================================================================

; Segment type: Zero-length
; Segment permissions: Read/Write
_bss            segment dword public 'BSS' use32
_bss            ends

; ===========================================================================

; Segment type: Externs
; extern
                extrn __ashldi3:near    ; ...
                extrn directive_hash    ; ...
                extrn perfhash_find:near ; ...
                extrn directive_tbl     ; ...
                extrn invalid_enum_str:near ; ...
                extrn nasm_reg_flags    ; ...
                extrn isalpha:near      ; ...
                extrn isdigit:near      ; ...
                extrn nasm_zalloc:near  ; ...
                extrn nasm_assert_failed:near ; ...
                extrn crc64:near        ; ...
                extrn strcmp:near       ; ...
                extrn crc64i:near       ; ...
                extrn nasm_stricmp:near ; ...
                extrn memmove:near      ; ...
                extrn nasm_free:near    ; ...


                end
