

;
; +-------------------------------------------------------------------------+
; |   This file has been generated by The Interactive Disassembler (IDA)    |
; |           Copyright (c) 2018 Hex-Rays, <support@hex-rays.com>           |
; |                            Freeware version                             |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : 68E64EE66650001AA23CCE83BDD1F437CE3A72ED3CFCB6ABC87D707335DF59B6
; Input MD5    : 50C68B68126BD0B59A4B9CBFD5D269CF
; Input CRC32  : 67FBD22D

; File Name   : C:\Users\90542\OneDrive\Masaüstü\nasm_214_c_o\saa.o
; Format      : ELF for Intel 386 (Relocatable)
;
; Source File : 'saa.c'

                .686p
                .mmx
                .model flat
.intel_syntax noprefix

; ===========================================================================

; Segment type: Pure code
; Segment permissions: Read/Execute
_text           segment dword public 'CODE' use32
                assume cs:_text
                ;org 8000000h
                assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing

; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

overflow_general proc near

var_18          = dword ptr -18h
var_14          = dword ptr -14h
var_10          = dword ptr -10h
var_C           = dword ptr -0Ch
var_4           = dword ptr -4
arg_0           = dword ptr  8
arg_4           = dword ptr  0Ch
arg_8           = dword ptr  10h

                push    ebp
                mov     ebp, esp
                sub     esp, 18h
                nop
                mov     eax, [ebp+arg_8]
                cmp     eax, 8
                jl      loc_8000020
                mov     eax, 0
                jmp     locret_80000D4
; ---------------------------------------------------------------------------

loc_8000020:                            ; ...
                mov     eax, [ebp+arg_8]
                shl     eax, 3
                dec     eax
                mov     [ebp+var_4], eax
                mov     eax, [ebp+var_4]
                push    eax
                mov     eax, 2
                mov     ecx, 0
                push    ecx
                push    eax
                call    __ashldi3
                add     esp, 0Ch
                sub     eax, 1
                sbb     edx, 0
                mov     [ebp+var_10], eax
                mov     [ebp+var_C], edx
                mov     eax, [ebp+var_4]
                push    eax
                mov     eax, 2
                mov     ecx, 0
                push    ecx
                push    eax
                call    __ashldi3
                add     esp, 0Ch
                mov     ecx, 0
                sub     ecx, eax
                mov     eax, 0
                sbb     eax, edx
                mov     [ebp+var_18], ecx
                mov     [ebp+var_14], eax
                mov     eax, [ebp+arg_4]
                mov     ecx, [ebp+var_14]
                cmp     eax, ecx
                jg      loc_80000A1
                jnz     loc_800009C
                mov     eax, [ebp+arg_0]
                mov     ecx, [ebp+var_18]
                cmp     eax, ecx
                jnb     loc_80000A1

loc_800009C:                            ; ...
                jmp     loc_80000CF
; ---------------------------------------------------------------------------

loc_80000A1:                            ; ...
                mov     eax, [ebp+arg_4]
                mov     ecx, [ebp+var_C]
                cmp     eax, ecx
                jl      loc_80000C8
                jnz     loc_80000C3
                mov     eax, [ebp+arg_0]
                mov     ecx, [ebp+var_10]
                cmp     eax, ecx
                jbe     loc_80000C8

loc_80000C3:                            ; ...
                jmp     loc_80000CF
; ---------------------------------------------------------------------------

loc_80000C8:                            ; ...
                mov     eax, 0
                jmp     short locret_80000D4
; ---------------------------------------------------------------------------

loc_80000CF:                            ; ...
                mov     eax, 1

locret_80000D4:                         ; ...
                leave
                retn
overflow_general endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

overflow_signed proc near

var_18          = dword ptr -18h
var_14          = dword ptr -14h
var_10          = dword ptr -10h
var_C           = dword ptr -0Ch
var_4           = dword ptr -4
arg_0           = dword ptr  8
arg_4           = dword ptr  0Ch
arg_8           = dword ptr  10h

                push    ebp
                mov     ebp, esp
                sub     esp, 18h
                nop
                mov     eax, [ebp+arg_8]
                cmp     eax, 8
                jl      loc_80000F6
                mov     eax, 0
                jmp     locret_80001AA
; ---------------------------------------------------------------------------

loc_80000F6:                            ; ...
                mov     eax, [ebp+arg_8]
                shl     eax, 3
                dec     eax
                mov     [ebp+var_4], eax
                mov     eax, [ebp+var_4]
                push    eax
                mov     eax, 1
                mov     ecx, 0
                push    ecx
                push    eax
                call    __ashldi3
                add     esp, 0Ch
                sub     eax, 1
                sbb     edx, 0
                mov     [ebp+var_10], eax
                mov     [ebp+var_C], edx
                mov     eax, [ebp+var_4]
                push    eax
                mov     eax, 1
                mov     ecx, 0
                push    ecx
                push    eax
                call    __ashldi3
                add     esp, 0Ch
                mov     ecx, 0
                sub     ecx, eax
                mov     eax, 0
                sbb     eax, edx
                mov     [ebp+var_18], ecx
                mov     [ebp+var_14], eax
                mov     eax, [ebp+arg_4]
                mov     ecx, [ebp+var_14]
                cmp     eax, ecx
                jg      loc_8000177
                jnz     loc_8000172
                mov     eax, [ebp+arg_0]
                mov     ecx, [ebp+var_18]
                cmp     eax, ecx
                jnb     loc_8000177

loc_8000172:                            ; ...
                jmp     loc_80001A5
; ---------------------------------------------------------------------------

loc_8000177:                            ; ...
                mov     eax, [ebp+arg_4]
                mov     ecx, [ebp+var_C]
                cmp     eax, ecx
                jl      loc_800019E
                jnz     loc_8000199
                mov     eax, [ebp+arg_0]
                mov     ecx, [ebp+var_10]
                cmp     eax, ecx
                jbe     loc_800019E

loc_8000199:                            ; ...
                jmp     loc_80001A5
; ---------------------------------------------------------------------------

loc_800019E:                            ; ...
                mov     eax, 0
                jmp     short locret_80001AA
; ---------------------------------------------------------------------------

loc_80001A5:                            ; ...
                mov     eax, 1

locret_80001AA:                         ; ...
                leave
                retn
overflow_signed endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

overflow_unsigned proc near

var_18          = dword ptr -18h
var_14          = dword ptr -14h
var_10          = dword ptr -10h
var_C           = dword ptr -0Ch
var_4           = dword ptr -4
arg_0           = dword ptr  8
arg_4           = dword ptr  0Ch
arg_8           = dword ptr  10h

                push    ebp
                mov     ebp, esp
                sub     esp, 18h
                nop
                mov     eax, [ebp+arg_8]
                cmp     eax, 8
                jl      loc_80001CC
                mov     eax, 0
                jmp     locret_8000264
; ---------------------------------------------------------------------------

loc_80001CC:                            ; ...
                mov     eax, [ebp+arg_8]
                shl     eax, 3
                dec     eax
                mov     [ebp+var_4], eax
                mov     eax, [ebp+var_4]
                push    eax
                mov     eax, 2
                mov     ecx, 0
                push    ecx
                push    eax
                call    __ashldi3
                add     esp, 0Ch
                sub     eax, 1
                sbb     edx, 0
                mov     [ebp+var_10], eax
                mov     [ebp+var_C], edx
                mov     eax, 0
                mov     ecx, 0
                mov     [ebp+var_18], eax
                mov     [ebp+var_14], ecx
                mov     eax, [ebp+arg_4]
                mov     ecx, [ebp+var_14]
                cmp     eax, ecx
                jg      loc_8000231
                jnz     loc_800022C
                mov     eax, [ebp+arg_0]
                mov     ecx, [ebp+var_18]
                cmp     eax, ecx
                jnb     loc_8000231

loc_800022C:                            ; ...
                jmp     loc_800025F
; ---------------------------------------------------------------------------

loc_8000231:                            ; ...
                mov     eax, [ebp+arg_4]
                mov     ecx, [ebp+var_C]
                cmp     eax, ecx
                jl      loc_8000258
                jnz     loc_8000253
                mov     eax, [ebp+arg_0]
                mov     ecx, [ebp+var_10]
                cmp     eax, ecx
                jbe     loc_8000258

loc_8000253:                            ; ...
                jmp     loc_800025F
; ---------------------------------------------------------------------------

loc_8000258:                            ; ...
                mov     eax, 0
                jmp     short locret_8000264
; ---------------------------------------------------------------------------

loc_800025F:                            ; ...
                mov     eax, 1

locret_8000264:                         ; ...
                leave
                retn
overflow_unsigned endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

signed_bits     proc near

arg_0           = dword ptr  8
arg_4           = dword ptr  0Ch
arg_8           = dword ptr  10h

                push    ebp
                mov     ebp, esp
                sub     esp, 0
                nop
                mov     eax, [ebp+arg_8]
                cmp     eax, 40h
                jge     loc_8000307
                mov     eax, [ebp+arg_8]
                push    eax
                mov     eax, 1
                mov     ecx, 0
                push    ecx
                push    eax
                call    __ashldi3
                add     esp, 0Ch
                sub     eax, 1
                sbb     edx, 0
                mov     ecx, [ebp+arg_0]
                and     ecx, eax
                mov     eax, [ebp+arg_4]
                and     eax, edx
                mov     [ebp+arg_0], ecx
                mov     [ebp+arg_4], eax
                mov     eax, [ebp+arg_8]
                dec     eax
                push    eax
                mov     eax, 1
                mov     ecx, 0
                push    ecx
                push    eax
                call    __ashldi3
                add     esp, 0Ch
                mov     ecx, [ebp+arg_0]
                and     ecx, eax
                mov     eax, [ebp+arg_4]
                and     eax, edx
                cmp     eax, 0
                jnz     loc_80002DF
                cmp     ecx, 0
                jz      loc_8000307

loc_80002DF:                            ; ...
                mov     eax, [ebp+arg_8]
                push    eax
                mov     eax, 0FFFFFFFFh
                mov     ecx, 0FFFFFFFFh
                push    ecx
                push    eax
                call    __ashldi3
                add     esp, 0Ch
                mov     ecx, [ebp+arg_0]
                or      ecx, eax
                mov     eax, [ebp+arg_4]
                or      eax, edx
                mov     [ebp+arg_0], ecx
                mov     [ebp+arg_4], eax

loc_8000307:                            ; ...
                mov     eax, [ebp+arg_0]
                mov     edx, [ebp+arg_4]
                leave
                retn
signed_bits     endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

                public saa_init
saa_init        proc near

tmp3            = dword ptr -14h
tmp2            = dword ptr -10h
tmp1            = dword ptr -0Ch
data            = dword ptr -8
s               = dword ptr -4
elem_len        = dword ptr  8

                push    ebp             ; struct SAA *saa_init(size_t elem_len)
                mov     ebp, esp        ; struct SAA *s;
                sub     esp, 20         ; char *data;
                nop
                mov     eax, 52         ; sizeof(struct SAA)
                push    eax
                call    nasm_zalloc
                add     esp, 4
                mov     [ebp+s], eax    ; s = nasm_zalloc(sizeof(struct SAA));
                mov     eax, [ebp+elem_len] ; #define SAA_BLKSHIFT 16
                                        ; #define SAA_BLKLEN ((size_t)1 << SAA_BLKSHIFT)
                cmp     eax, 10000h     ; if (elem_len >= SAA_BLKLEN)
                jb      si_1
                mov     eax, [ebp+s]
                add     eax, 4
                mov     ecx, [ebp+elem_len]
                mov     [eax], ecx      ; s->blk_len = elem_len;
                jmp     si_2
; ---------------------------------------------------------------------------

si_1:                                   ; ...
                mov     eax, [ebp+s]    ; s->blk_len = SAA_BLKLEN - (SAA_BLKLEN % elem_len);
                add     eax, 4
                mov     [ebp+tmp1], eax
                mov     eax, 10000h     ; SAA_BLKLEN = 65536
                mov     ecx, [ebp+elem_len]
                xor     edx, edx
                div     ecx
                mov     eax, 10000h
                sub     eax, edx
                mov     ecx, [ebp+tmp1]
                mov     [ecx], eax

si_2:                                   ; ...
                mov     eax, [ebp+s]
                mov     ecx, [ebp+elem_len]
                mov     [eax], ecx      ; s->elem_len = elem_len;
                mov     eax, [ebp+s]
                add     eax, 16         ; s->length address
                mov     ecx, [ebp+s]
                add     ecx, 4
                mov     edx, [ecx]      ; s->blk_len
                mov     [eax], edx      ; s->length = s->blk_len;
                mov     eax, [ebp+s]
                add     eax, 4
                mov     ecx, [eax]
                push    ecx
                call    nasm_malloc
                add     esp, 4
                mov     [ebp+data], eax ; data = nasm_malloc(s->blk_len);
                mov     eax, [ebp+s]
                add     eax, 12
                mov     ecx, [ebp+s]
                add     ecx, 8
                mov     edx, 1
                mov     [ecx], edx      ; s->nblkptrs = s->nblks = 1;
                mov     [eax], edx
                mov     eax, [ebp+s]
                add     eax, 48
                mov     ecx, 4          ; sizeof(char *)
                push    ecx
                mov     [ebp+tmp2], eax ; s->blk_ptrs address
                call    nasm_malloc
                add     esp, 4
                mov     ecx, [ebp+tmp2]
                mov     [ecx], eax      ; s->blk_ptrs = nasm_malloc(sizeof(char *));
                mov     eax, [ebp+s]
                add     eax, 48
                mov     ecx, [eax]
                mov     eax, [ebp+data]
                mov     [ecx], eax      ; s->blk_ptrs[0] = data;
                mov     eax, [ebp+s]
                add     eax, 24
                mov     ecx, [ebp+s]
                add     ecx, 36
                mov     edx, [ebp+s]
                add     edx, 48
                mov     [ebp+tmp3], eax
                mov     eax, [edx]
                mov     [ecx], eax
                mov     ecx, [ebp+tmp3]
                mov     [ecx], eax      ; s->wblk = s->rblk = &s->blk_ptrs[0];
                mov     eax, [ebp+s]    ; return s;
                leave
                retn
saa_init        endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

                public saa_free
saa_free        proc near

n               = dword ptr -8
p               = dword ptr -4
s               = dword ptr  8

                push    ebp             ; void saa_free(struct SAA *s)
                mov     ebp, esp        ; char **p;
                sub     esp, 8          ; size_t n;
                nop
                mov     eax, [ebp+s]    ; for (p = s->blk_ptrs, n = s->nblks; n; p++, n--)
                add     eax, 48
                mov     ecx, [eax]      ; s->blk_ptrs
                mov     [ebp+p], ecx    ; p = s->blk_ptrs
                mov     eax, [ebp+s]
                add     eax, 8
                mov     ecx, [eax]      ; s->nblks
                mov     [ebp+n], ecx    ; n = s->nblks

sf_1:                                   ; ...
                mov     eax, [ebp+n]    ; (if) n
                cmp     eax, 0
                jz      sf_4
                jmp     sf_3
; ---------------------------------------------------------------------------

sf_2:                                   ; ...
                mov     eax, [ebp+p]    ; (next)
                mov     ecx, eax
                add     eax, 4          ; p++
                mov     [ebp+p], eax
                mov     eax, [ebp+n]
                mov     ecx, eax
                add     eax, -1
                mov     [ebp+n], eax    ; n--
                jmp     short sf_1
; ---------------------------------------------------------------------------

sf_3:                                   ; ...
                mov     eax, [ebp+p]
                mov     ecx, [eax]
                push    ecx
                call    nasm_free       ; nasm_free(*p);
                add     esp, 4
                jmp     short sf_2
; ---------------------------------------------------------------------------

sf_4:                                   ; ...
                mov     eax, [ebp+s]
                add     eax, 48
                mov     ecx, [eax]
                push    ecx
                call    nasm_free       ; nasm_free(s->blk_ptrs);
                add     esp, 4
                mov     eax, [ebp+s]
                push    eax
                call    nasm_free       ; nasm_free(s);
                add     esp, 4
                leave
                retn
saa_free        endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

saa_extend      proc near               ; ...

tmp5            = dword ptr -20h
tmp4            = dword ptr -1Ch
tmp3            = dword ptr -18h
tmp2            = dword ptr -14h
tmp1            = dword ptr -10h
windex          = dword ptr -0Ch
rindex          = dword ptr -8
blkn            = dword ptr -4
s               = dword ptr  8

                push    ebp             ; /* Add one allocation block to an SAA */
                                        ; static void saa_extend(struct SAA *s)
                mov     ebp, esp
                sub     esp, 32
                nop
                mov     eax, [ebp+s]
                add     eax, 8
                mov     ecx, [eax]
                mov     edx, ecx
                inc     ecx
                mov     [eax], ecx
                mov     [ebp+blkn], edx ; size_t blkn = s->nblks++;
                mov     eax, [ebp+s]
                add     eax, 12         ; s->nblkptrs address
                mov     ecx, [ebp+blkn]
                mov     edx, [eax]
                cmp     ecx, edx        ; if (blkn >= s->nblkptrs) {
                jb      se_1
                mov     eax, [ebp+s]
                add     eax, 36
                mov     ecx, [ebp+s]
                add     ecx, 48
                mov     edx, [eax]
                mov     eax, [ecx]
                sub     edx, eax
                sar     edx, 2
                mov     [ebp+rindex], edx ; size_t rindex = s->rblk - s->blk_ptrs;
                mov     eax, [ebp+s]
                add     eax, 24
                mov     ecx, [ebp+s]
                add     ecx, 48
                mov     edx, [eax]
                mov     eax, [ecx]
                sub     edx, eax
                sar     edx, 2
                mov     [ebp+windex], edx ; size_t windex = s->wblk - s->blk_ptrs;
                mov     eax, [ebp+s]
                add     eax, 12
                mov     ecx, [eax]
                shl     ecx, 1
                mov     [eax], ecx      ; s->nblkptrs <<= 1;
                mov     eax, [ebp+s]
                add     eax, 48
                mov     ecx, [ebp+s]
                add     ecx, 48         ; s->blk_ptrs address
                mov     edx, [ebp+s]
                add     edx, 12         ; s->nblkptrs address
                mov     [ebp+tmp1], eax ; s->blk_ptrs address
                mov     eax, [edx]
                shl     eax, 2          ; * sizeof(char *)
                push    eax
                mov     eax, [ecx]      ; s->blk_ptrs
                push    eax
                call    nasm_realloc
                add     esp, 8
                mov     ecx, [ebp+tmp1]
                mov     [ecx], eax      ; s->blk_ptrs =
                                        ; nasm_realloc(s->blk_ptrs, s->nblkptrs * sizeof(char *));
                mov     eax, [ebp+s]
                add     eax, 36
                mov     ecx, [ebp+s]
                add     ecx, 48
                mov     edx, [ebp+rindex]
                shl     edx, 2
                mov     [ebp+tmp2], eax
                mov     eax, [ecx]      ; s->blk_ptrs
                add     eax, edx
                mov     ecx, [ebp+tmp2]
                mov     [ecx], eax      ; s->rblk = s->blk_ptrs + rindex;
                mov     eax, [ebp+s]
                add     eax, 24
                mov     ecx, [ebp+s]
                add     ecx, 48
                mov     edx, [ebp+windex]
                shl     edx, 2
                mov     [ebp+tmp3], eax
                mov     eax, [ecx]      ; s->blk_ptrs
                add     eax, edx
                mov     ecx, [ebp+tmp3]
                mov     [ecx], eax      ; s->wblk = s->blk_ptrs + windex;

se_1:                                   ; ...
                mov     eax, [ebp+s]
                add     eax, 48
                mov     ecx, [ebp+blkn]
                shl     ecx, 2
                mov     edx, [eax]
                add     edx, ecx
                mov     eax, [ebp+s]
                add     eax, 4
                mov     ecx, [eax]      ; s->blk_len
                push    ecx
                mov     [ebp+tmp4], edx ; s->blk_ptrs[blkn]
                call    nasm_malloc
                add     esp, 4
                mov     ecx, [ebp+tmp4]
                mov     [ecx], eax      ; s->blk_ptrs[blkn] = nasm_malloc(s->blk_len)
                mov     eax, [ebp+s]
                add     eax, 16
                mov     ecx, [ebp+s]
                add     ecx, 4          ; s->blk_len address
                mov     edx, [eax]      ; s->length
                mov     [ebp+tmp5], eax ; s->length address
                mov     eax, [ecx]      ; s->blk_len
                add     edx, eax
                mov     eax, [ebp+tmp5]
                mov     [eax], edx      ; s->length += s->blk_len;
                leave
                retn
saa_extend      endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

                public saa_wstruct
saa_wstruct     proc near

tmp4            = dword ptr -14h
tmp3            = dword ptr -10h
tmp2            = dword ptr -0Ch
tmp1            = dword ptr -8
p               = dword ptr -4
s               = dword ptr  8

                push    ebp             ; void *saa_wstruct(struct SAA *s)
                mov     ebp, esp
                sub     esp, 20         ; void *p;
                nop
                mov     eax, [ebp+s]    ; nasm_assert((s->wpos % s->elem_len) == 0);
                add     eax, 28
                mov     ecx, [ebp+s]
                mov     [ebp+tmp1], eax
                mov     eax, [ebp+tmp1]
                mov     eax, [eax]      ; s->wpos
                mov     [ebp+tmp2], ecx
                mov     ecx, [ebp+tmp2]
                mov     ecx, [ecx]
                xor     edx, edx
                div     ecx             ; s->wpos % s->elem_len
                cmp     edx, 0          ; s->elem_len
                jz      sw_1
                mov     eax, offset L_200 ; "(s->wpos % s->elem_len) == 0"
                push    eax
                mov     eax, 102        ; (saa.c line 102)
                push    eax
                mov     eax, offset L_199 ; "saa.c"
                push    eax
                call    nasm_assert_failed
                add     esp, 12

sw_1:                                   ; ...
                mov     eax, [ebp+s]    ; if (s->wpos + s->elem_len > s->blk_len) {
                add     eax, 28
                mov     ecx, [ebp+s]
                mov     edx, [eax]      ; s->wpos
                mov     eax, [ecx]
                add     edx, eax        ; s->wpos + s->elem_len
                mov     eax, [ebp+s]
                add     eax, 4
                mov     ecx, [eax]      ; s->blk_len
                cmp     edx, ecx
                jbe     sw_4
                mov     eax, [ebp+s]    ; nasm_assert(s->wpos == s->blk_len);
                add     eax, 28
                mov     ecx, [ebp+s]
                add     ecx, 4
                mov     edx, [eax]
                mov     eax, [ecx]
                cmp     edx, eax
                jz      sw_2
                mov     eax, offset L_202 ; "s->wpos == s->blk_len"
                push    eax
                mov     eax, 105        ; (saa.c line 105)
                push    eax
                mov     eax, offset L_201 ; "saa.c"
                push    eax
                call    nasm_assert_failed
                add     esp, 12

sw_2:                                   ; ...
                mov     eax, [ebp+s]    ; if (s->wptr + s->elem_len > s->length)
                add     eax, 32
                mov     ecx, [ebp+s]
                mov     edx, [eax]      ; s->wptr
                mov     eax, [ecx]      ; s->elem_len
                add     edx, eax
                mov     eax, [ebp+s]
                add     eax, 16
                mov     ecx, [eax]      ; s->length
                cmp     edx, ecx
                jbe     sw_3
                mov     eax, [ebp+s]
                push    eax
                call    saa_extend      ; saa_extend(s);
                add     esp, 4

sw_3:                                   ; ...
                mov     eax, [ebp+s]    ; s->wblk++;
                add     eax, 24
                mov     ecx, [eax]
                mov     edx, ecx
                add     ecx, 4
                mov     [eax], ecx
                mov     eax, [ebp+s]
                add     eax, 28
                mov     ecx, 0
                mov     [eax], ecx      ; s->wpos = 0;

sw_4:                                   ; ...
                mov     eax, [ebp+s]
                add     eax, 24
                mov     ecx, [eax]      ; s->wblk
                mov     eax, [ebp+s]
                add     eax, 28
                mov     edx, [eax]      ; s->wpos
                mov     eax, [ecx]      ; *s->wblk
                add     eax, edx
                mov     [ebp+p], eax    ; p = *s->wblk + s->wpos;
                mov     eax, [ebp+s]
                add     eax, 28
                mov     ecx, [ebp+s]
                mov     edx, [eax]
                mov     [ebp+tmp3], eax ; s->wpos
                mov     eax, [ecx]      ; s->elem_len
                add     edx, eax
                mov     eax, [ebp+tmp3]
                mov     [eax], edx      ; s->wpos += s->elem_len;
                mov     eax, [ebp+s]
                add     eax, 32
                mov     ecx, [ebp+s]
                mov     edx, [eax]      ; s->wptr
                mov     [ebp+tmp4], eax
                mov     eax, [ecx]      ; s->elem_len
                add     edx, eax
                mov     eax, [ebp+tmp4]
                mov     [eax], edx      ; s->wptr += s->elem_len;
                mov     eax, [ebp+s]
                add     eax, 32         ; s->wptr address
                mov     ecx, [ebp+s]
                add     ecx, 20         ; s->datalen address
                mov     edx, [eax]      ; s->wptr
                mov     eax, [ecx]      ; s->datalen
                cmp     edx, eax        ; if (s->wptr > s->datalen)
                jbe     sw_5
                mov     eax, [ebp+s]
                add     eax, 20
                mov     ecx, [ebp+s]
                add     ecx, 32
                mov     edx, [ecx]
                mov     [eax], edx      ; s->datalen = s->wptr;

sw_5:                                   ; ...
                mov     eax, [ebp+p]    ; return p;
                leave
                retn
saa_wstruct     endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

                public saa_wbytes
saa_wbytes      proc near               ; ...

l               = dword ptr -8
d               = dword ptr -4
s               = dword ptr  8
data            = dword ptr  0Ch
len             = dword ptr  10h

                push    ebp             ; void saa_wbytes(struct SAA *s, const void *data, size_t len)
                mov     ebp, esp
                sub     esp, 8
                nop
                mov     eax, [ebp+data]
                mov     [ebp+d], eax    ; const char *d = data;

swb_1:                                  ; ...
                mov     eax, [ebp+len]
                cmp     eax, 0          ; while (len) {
                jz      swb_8
                mov     eax, [ebp+s]
                add     eax, 4
                mov     ecx, [ebp+s]
                add     ecx, 28
                mov     edx, [eax]
                mov     eax, [ecx]
                sub     edx, eax
                mov     [ebp+l], edx    ; size_t l = s->blk_len - s->wpos;
                mov     eax, [ebp+l]
                mov     ecx, [ebp+len]
                cmp     eax, ecx        ; if (l > len)
                jbe     swb_2
                mov     eax, [ebp+len]
                mov     [ebp+l], eax    ; l = len;

swb_2:                                  ; ...
                mov     eax, [ebp+l]    ; if (l) {
                cmp     eax, 0
                jz      swb_5
                mov     eax, [ebp+d]    ; if (d) {
                cmp     eax, 0
                jz      swb_3
                mov     eax, [ebp+s]    ; memcpy(*s->wblk + s->wpos, d, l);
                add     eax, 24
                mov     ecx, [eax]
                mov     eax, [ebp+s]
                add     eax, 28
                mov     edx, [eax]
                mov     eax, [ecx]
                add     eax, edx
                mov     ecx, [ebp+l]
                push    ecx
                mov     ecx, [ebp+d]
                push    ecx
                push    eax
                call    memcpy
                add     esp, 12
                mov     eax, [ebp+l]
                mov     ecx, [ebp+d]
                add     ecx, eax
                mov     [ebp+d], ecx    ; d += l;
                jmp     swb_4
; ---------------------------------------------------------------------------

swb_3:                                  ; ...
                mov     eax, [ebp+s]    ; } else
                add     eax, 24         ; memset(*s->wblk + s->wpos, 0, l);
                mov     ecx, [eax]
                mov     eax, [ebp+s]
                add     eax, 28
                mov     edx, [eax]
                mov     eax, [ecx]
                add     eax, edx
                mov     ecx, [ebp+l]
                push    ecx
                mov     ecx, 0
                push    ecx
                push    eax
                call    memset
                add     esp, 12

swb_4:                                  ; ...
                mov     eax, [ebp+s]
                add     eax, 28
                mov     ecx, [eax]
                mov     edx, [ebp+l]
                add     ecx, edx
                mov     [eax], ecx      ; s->wpos += l;
                mov     eax, [ebp+s]
                add     eax, 32
                mov     ecx, [eax]
                mov     edx, [ebp+l]
                add     ecx, edx
                mov     [eax], ecx      ; s->wptr += l;
                mov     eax, [ebp+len]
                mov     ecx, [ebp+l]
                sub     eax, ecx
                mov     [ebp+len], eax  ; len -= l;
                mov     eax, [ebp+s]
                add     eax, 20
                mov     ecx, [ebp+s]
                add     ecx, 32
                mov     edx, [eax]
                mov     eax, [ecx]
                cmp     edx, eax        ; if (s->datalen < s->wptr)
                jnb     swb_5
                mov     eax, [ebp+s]
                add     eax, 20
                mov     ecx, [ebp+s]
                add     ecx, 32
                mov     edx, [ecx]
                mov     [eax], edx      ; s->datalen = s->wptr;

swb_5:                                  ; ...
                mov     eax, [ebp+len]
                cmp     eax, 0          ; if (len) {
                jz      swb_7
                mov     eax, [ebp+s]
                add     eax, 32
                mov     ecx, [ebp+s]
                add     ecx, 16
                mov     edx, [eax]
                mov     eax, [ecx]
                cmp     edx, eax        ; if (s->wptr >= s->length)
                jb      swb_6
                mov     eax, [ebp+s]
                push    eax
                call    saa_extend      ; saa_extend(s);
                add     esp, 4

swb_6:                                  ; ...
                mov     eax, [ebp+s]
                add     eax, 24
                mov     ecx, [eax]
                mov     edx, ecx
                add     ecx, 4
                mov     [eax], ecx      ; s->wblk++;
                mov     eax, [ebp+s]
                add     eax, 28
                mov     ecx, 0
                mov     [eax], ecx      ; s->wpos = 0;

swb_7:                                  ; ...
                jmp     swb_1
; ---------------------------------------------------------------------------

swb_8:                                  ; ...
                leave
                retn
saa_wbytes      endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

                public saa_wcstring
saa_wcstring    proc near

bytes           = dword ptr -4
s               = dword ptr  8
str             = dword ptr  0Ch

                push    ebp             ; /* Writes a string, *including* the final null, to the specified SAA,
                                        ;    and return the number of bytes written. */
                                        ;
                                        ; size_t saa_wcstring(struct SAA *s, const char *str)
                mov     ebp, esp
                sub     esp, 4
                nop
                mov     eax, [ebp+str]
                push    eax
                call    strlen
                add     esp, 4
                inc     eax
                mov     [ebp+bytes], eax ; size_t bytes = strlen(str) + 1;
                mov     eax, [ebp+bytes]
                push    eax
                mov     eax, [ebp+str]
                push    eax
                mov     eax, [ebp+s]
                push    eax
                call    saa_wbytes      ; saa_wbytes(s, str, bytes);
                add     esp, 12
                mov     eax, [ebp+bytes] ; return bytes;
                leave
                retn
saa_wcstring    endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

                public saa_rewind
saa_rewind      proc near               ; ...

s               = dword ptr  8

                push    ebp             ; void saa_rewind(struct SAA *s)
                mov     ebp, esp
                sub     esp, 0
                nop
                mov     eax, [ebp+s]
                add     eax, 36
                mov     ecx, [ebp+s]
                add     ecx, 48
                mov     edx, [ecx]
                mov     [eax], edx
                mov     eax, [ebp+s]
                add     eax, 40
                mov     ecx, [ebp+s]
                add     ecx, 44
                mov     edx, 0
                mov     [ecx], edx      ; s->rblk = s->blk_ptrs;
                mov     [eax], edx      ; s->rpos = s->rptr = 0;
                leave
                retn
saa_rewind      endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

                public saa_rstruct
saa_rstruct     proc near

tmp4            = dword ptr -14h
tmp3            = dword ptr -10h
tmp2            = dword ptr -0Ch
tmp1            = dword ptr -8
p               = dword ptr -4
s               = dword ptr  8

                push    ebp             ; void *saa_rstruct(struct SAA *s)
                mov     ebp, esp
                sub     esp, 20         ; void *p;
                nop
                mov     eax, [ebp+s]    ; if (s->rptr + s->elem_len > s->datalen)
                add     eax, 44
                mov     ecx, [ebp+s]
                mov     edx, [eax]
                mov     eax, [ecx]
                add     edx, eax
                mov     eax, [ebp+s]
                add     eax, 20
                mov     ecx, [eax]
                cmp     edx, ecx
                jbe     sr_1
                mov     eax, 0          ; return NULL;
                jmp     sr_4
; ---------------------------------------------------------------------------

sr_1:                                   ; ...
                mov     eax, [ebp+s]    ; nasm_assert((s->rpos % s->elem_len) == 0);
                add     eax, 40
                mov     ecx, [ebp+s]
                mov     [ebp+tmp1], eax
                mov     eax, [ebp+tmp1]
                mov     eax, [eax]      ; s->rpos
                mov     [ebp+tmp2], ecx
                mov     ecx, [ebp+tmp2]
                mov     ecx, [ecx]      ; s->elem_len
                xor     edx, edx
                div     ecx
                cmp     edx, 0
                jz      sr_2
                mov     eax, offset L_204 ; "(s->rpos % s->elem_len) == 0"
                push    eax
                mov     eax, 178
                push    eax
                mov     eax, offset L_203 ; "saa.c"
                push    eax
                call    nasm_assert_failed
                add     esp, 0Ch

sr_2:                                   ; ...
                mov     eax, [ebp+s]    ; if (s->rpos + s->elem_len > s->blk_len) {
                add     eax, 40
                mov     ecx, [ebp+s]
                mov     edx, [eax]      ; s->rpos
                mov     eax, [ecx]      ; s->elem_len
                add     edx, eax
                mov     eax, [ebp+s]
                add     eax, 4
                mov     ecx, [eax]      ; s->blk_len
                cmp     edx, ecx
                jbe     sr_3
                mov     eax, [ebp+s]
                add     eax, 36
                mov     ecx, [eax]
                mov     edx, ecx
                add     ecx, 4
                mov     [eax], ecx      ; s->rblk++;
                mov     eax, [ebp+s]
                add     eax, 40
                mov     ecx, 0
                mov     [eax], ecx      ; s->rpos = 0;

sr_3:                                   ; ...
                mov     eax, [ebp+s]
                add     eax, 36
                mov     ecx, [eax]      ; s->rblk
                mov     eax, [ebp+s]
                add     eax, 40
                mov     edx, [eax]      ; s->rpos
                mov     eax, [ecx]      ; *s->rblk
                add     eax, edx
                mov     [ebp+p], eax    ; p = *s->rblk + s->rpos;
                mov     eax, [ebp+s]
                add     eax, 40
                mov     ecx, [ebp+s]
                mov     edx, [eax]
                mov     [ebp+tmp3], eax
                mov     eax, [ecx]
                add     edx, eax
                mov     eax, [ebp+tmp3]
                mov     [eax], edx
                mov     eax, [ebp+s]
                add     eax, 44
                mov     ecx, [ebp+s]
                mov     edx, [eax]      ; s->rptr
                mov     [ebp+tmp4], eax
                mov     eax, [ecx]      ; s->elem_len
                add     edx, eax
                mov     eax, [ebp+tmp4]
                mov     [eax], edx      ; s->rptr += s->elem_len;
                mov     eax, [ebp+p]    ; return p;

sr_4:                                   ; ...
                leave
                retn
saa_rstruct     endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

                public saa_rbytes
saa_rbytes      proc near               ; ...

len             = dword ptr -8
p               = dword ptr -4
s               = dword ptr  8
lenp            = dword ptr  0Ch

                push    ebp             ; const void *saa_rbytes(struct SAA *s, size_t * lenp)
                mov     ebp, esp
                sub     esp, 8          ; const void *p;
                nop                     ; size_t len;
                mov     eax, [ebp+s]
                add     eax, 44
                mov     ecx, [ebp+s]
                add     ecx, 20
                mov     edx, [eax]
                mov     eax, [ecx]
                cmp     edx, eax        ; if (s->rptr >= s->datalen) {
                jb      srb_1
                mov     eax, [ebp+lenp]
                mov     ecx, 0
                mov     [eax], ecx      ; *lenp = 0;
                mov     eax, 0
                jmp     srb_5           ; return NULL;
; ---------------------------------------------------------------------------

srb_1:                                  ; ...
                mov     eax, [ebp+s]
                add     eax, 40
                mov     ecx, [ebp+s]
                add     ecx, 4
                mov     edx, [eax]
                mov     eax, [ecx]
                cmp     edx, eax        ; if (s->rpos >= s->blk_len) {
                jb      srb_2
                mov     eax, [ebp+s]
                add     eax, 36
                mov     ecx, [eax]
                mov     edx, ecx
                add     ecx, 4
                mov     [eax], ecx      ; s->rblk++;
                mov     eax, [ebp+s]
                add     eax, 40
                mov     ecx, 0
                mov     [eax], ecx      ; s->rpos = 0;

srb_2:                                  ; ...
                mov     eax, [ebp+lenp]
                mov     ecx, [eax]
                mov     [ebp+len], ecx  ; len = *lenp;
                mov     eax, [ebp+s]
                add     eax, 20
                mov     ecx, [ebp+s]
                add     ecx, 44
                mov     edx, [eax]      ; s->datalen
                mov     eax, [ecx]      ; s->rptr
                sub     edx, eax
                mov     eax, [ebp+len]
                cmp     eax, edx        ; if (len > s->datalen - s->rptr)
                jbe     srb_3
                mov     eax, [ebp+s]
                add     eax, 20
                mov     ecx, [ebp+s]
                add     ecx, 44
                mov     edx, [eax]
                mov     eax, [ecx]
                sub     edx, eax
                mov     [ebp+len], edx

srb_3:                                  ; ...
                mov     eax, [ebp+s]    ; if (len > s->blk_len - s->rpos)
                add     eax, 4
                mov     ecx, [ebp+s]
                add     ecx, 40
                mov     edx, [eax]
                mov     eax, [ecx]
                sub     edx, eax
                mov     eax, [ebp+len]
                cmp     eax, edx
                jbe     srb_4
                mov     eax, [ebp+s]
                add     eax, 4
                mov     ecx, [ebp+s]
                add     ecx, 40
                mov     edx, [eax]
                mov     eax, [ecx]
                sub     edx, eax
                mov     [ebp+len], edx  ; len = s->blk_len - s->rpos;

srb_4:                                  ; ...
                mov     eax, [ebp+lenp]
                mov     ecx, [ebp+len]
                mov     [eax], ecx      ; *lenp = len;
                mov     eax, [ebp+s]
                add     eax, 36
                mov     ecx, [eax]
                mov     eax, [ebp+s]
                add     eax, 40
                mov     edx, [eax]
                mov     eax, [ecx]
                add     eax, edx
                mov     [ebp+p], eax    ; p = *s->rblk + s->rpos;
                mov     eax, [ebp+s]
                add     eax, 40
                mov     ecx, [eax]
                mov     edx, [ebp+len]
                add     ecx, edx
                mov     [eax], ecx      ; s->rpos += len;
                mov     eax, [ebp+s]
                add     eax, 44
                mov     ecx, [eax]
                mov     edx, [ebp+len]
                add     ecx, edx
                mov     [eax], ecx      ; s->rptr += len;
                mov     eax, [ebp+p]    ; return p;

srb_5:                                  ; ...
                leave
                retn
saa_rbytes      endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

                public saa_rnbytes
saa_rnbytes     proc near               ; ...

p               = dword ptr -0Ch
l               = dword ptr -8
d               = dword ptr -4
s               = dword ptr  8
data            = dword ptr  0Ch
len             = dword ptr  10h

                push    ebp             ; void saa_rnbytes(struct SAA *s, void *data, size_t len)
                mov     ebp, esp
                sub     esp, 12
                nop
                mov     eax, [ebp+data]
                mov     [ebp+d], eax    ; char *d = data;
                mov     eax, [ebp+s]    ; nasm_assert(s->rptr + len <= s->datalen);
                add     eax, 44
                mov     ecx, [eax]
                mov     eax, [ebp+len]
                add     ecx, eax
                mov     eax, [ebp+s]
                add     eax, 20
                mov     edx, [eax]
                cmp     ecx, edx
                jbe     srnb_1
                mov     eax, offset L_206 ; "s->rptr + len <= s->datalen"
                push    eax
                mov     eax, 226        ; (saa.c line 226)
                push    eax
                mov     eax, offset L_205 ; "saa.c"
                push    eax
                call    nasm_assert_failed
                add     esp, 12

srnb_1:                                 ; ...
                mov     eax, [ebp+len]  ; while (len) {
                cmp     eax, 0
                jz      srnb_2
                mov     eax, [ebp+len]  ; size_t l;
                mov     [ebp+l], eax    ; l = len;
                lea     eax, [ebp+l]
                push    eax
                mov     eax, [ebp+s]
                push    eax
                call    saa_rbytes
                add     esp, 8          ; const void *p;
                mov     [ebp+p], eax    ; p = saa_rbytes(s, &l);
                mov     eax, [ebp+l]
                push    eax
                mov     eax, [ebp+p]
                push    eax
                mov     eax, [ebp+d]
                push    eax
                call    memcpy          ; memcpy(d, p, l);
                add     esp, 12
                mov     eax, [ebp+l]
                mov     ecx, [ebp+d]
                add     ecx, eax
                mov     [ebp+d], ecx    ; d += l;
                mov     eax, [ebp+len]
                mov     ecx, [ebp+l]
                sub     eax, ecx
                mov     [ebp+len], eax  ; len -= l;
                jmp     short srnb_1
; ---------------------------------------------------------------------------

srnb_2:                                 ; ...
                leave
                retn
saa_rnbytes     endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

                public saa_fread
saa_fread       proc near

tmp4            = dword ptr -14h
tmp3            = dword ptr -10h
tmp2            = dword ptr -0Ch
tmp1            = dword ptr -8
ix              = dword ptr -4
s               = dword ptr  8
posn            = dword ptr  0Ch
data            = dword ptr  10h
len             = dword ptr  14h

                push    ebp             ; /* Same as saa_rnbytes, except position the counter first */
                                        ; void saa_fread(struct SAA *s, size_t posn, void *data, size_t len)
                mov     ebp, esp
                sub     esp, 20
                nop                     ; size_t ix;
                mov     eax, [ebp+posn] ; nasm_assert(posn + len <= s->datalen);
                mov     ecx, [ebp+len]
                add     eax, ecx
                mov     ecx, [ebp+s]
                add     ecx, 20
                mov     edx, [ecx]      ; s->datalen
                cmp     eax, edx
                jbe     sfr_1
                mov     eax, offset L_208 ; "posn + len <= s->datalen"
                push    eax
                mov     eax, 246        ; (saa.c line 246)
                push    eax
                mov     eax, offset L_207 ; "saa.c"
                push    eax
                call    nasm_assert_failed
                add     esp, 12

sfr_1:                                  ; ...
                mov     eax, [ebp+s]    ; if (likely(s->blk_len == SAA_BLKLEN)) {
                add     eax, 4
                mov     ecx, [eax]
                cmp     ecx, 10000h     ; SAA_BLKLEN = 65536
                jnz     sfr_2
                mov     eax, [ebp+posn]
                shr     eax, 16         ; SAA_BLKSHIFT
                mov     [ebp+ix], eax   ; ix = posn >> SAA_BLKSHIFT;
                mov     eax, [ebp+s]
                add     eax, 40         ; s->rpos
                mov     ecx, [ebp+posn]
                and     ecx, 0FFFFh     ; 65535
                mov     [eax], ecx      ; s->rpos = posn & (SAA_BLKLEN - 1);
                jmp     sfr_3
; ---------------------------------------------------------------------------

sfr_2:                                  ; ...
                mov     eax, [ebp+s]    ; } else {
                add     eax, 4
                mov     [ebp+tmp1], eax
                mov     eax, [ebp+posn]
                mov     ecx, [ebp+tmp1]
                mov     ecx, [ecx]
                xor     edx, edx
                div     ecx
                mov     [ebp+ix], eax   ; ix = posn / s->blk_len;
                mov     eax, [ebp+s]
                add     eax, 40
                mov     ecx, [ebp+s]
                add     ecx, 4
                mov     [ebp+tmp2], eax ; s->rpos address
                mov     eax, [ebp+posn]
                mov     [ebp+tmp3], ecx ; s->blk_len address
                mov     ecx, [ebp+tmp3]
                mov     ecx, [ecx]      ; s->blk_len
                xor     edx, edx
                div     ecx
                mov     eax, [ebp+tmp2]
                mov     [eax], edx      ; s->rpos = posn % s->blk_len;

sfr_3:                                  ; ...
                mov     eax, [ebp+s]
                add     eax, 44
                mov     ecx, [ebp+posn]
                mov     [eax], ecx      ; s->rptr = posn;
                mov     eax, [ebp+s]
                add     eax, 36
                mov     ecx, [ebp+s]
                add     ecx, 48
                mov     edx, [ebp+ix]
                shl     edx, 2
                mov     [ebp+tmp4], eax ; s->rblk
                mov     eax, [ecx]
                add     eax, edx        ; s->blk_ptrs[ix] address
                mov     ecx, [ebp+tmp4]
                mov     [ecx], eax      ; s->rblk = &s->blk_ptrs[ix];
                mov     eax, [ebp+len]
                push    eax
                mov     eax, [ebp+data]
                push    eax
                mov     eax, [ebp+s]
                push    eax
                call    saa_rnbytes
                add     esp, 12
                leave
                retn
saa_fread       endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

                public saa_fwrite
saa_fwrite      proc near

tmp4            = dword ptr -14h
tmp3            = dword ptr -10h
tmp2            = dword ptr -0Ch
tmp1            = dword ptr -8
ix              = dword ptr -4
s               = dword ptr  8
posn            = dword ptr  0Ch
data            = dword ptr  10h
len             = dword ptr  14h

                push    ebp             ; /* Same as saa_wbytes, except position the counter first */
                                        ; void saa_fwrite(struct SAA *s, size_t posn, const void *data, size_t len)
                mov     ebp, esp
                sub     esp, 20         ; size_t ix;
                nop
                mov     eax, [ebp+s]    ; /* Seek beyond the end of the existing array not supported */
                                        ; nasm_assert(posn <= s->datalen);
                add     eax, 20
                mov     ecx, [ebp+posn]
                mov     edx, [eax]
                cmp     ecx, edx
                jbe     sfw_1
                mov     eax, offset L_210 ; "posn <= s->datalen"
                push    eax
                mov     eax, 267        ; (saa.c line 267)
                push    eax
                mov     eax, offset L_209 ; "saa.c"
                push    eax
                call    nasm_assert_failed
                add     esp, 12

sfw_1:                                  ; ...
                mov     eax, [ebp+s]    ; if (likely(s->blk_len == SAA_BLKLEN)) {
                add     eax, 4
                mov     ecx, [eax]
                cmp     ecx, 10000h     ; SAA_BLKLEN = 65536
                jnz     sfw_2
                mov     eax, [ebp+posn]
                shr     eax, 16         ; SAA_BLKSHIFT
                mov     [ebp+ix], eax   ; ix = posn >> SAA_BLKSHIFT;
                mov     eax, [ebp+s]
                add     eax, 28
                mov     ecx, [ebp+posn]
                and     ecx, 0FFFFh     ; 65535
                mov     [eax], ecx      ; s->wpos = posn & (SAA_BLKLEN - 1);
                jmp     sfw_3
; ---------------------------------------------------------------------------

sfw_2:                                  ; ...
                mov     eax, [ebp+s]    ; } else {
                add     eax, 4
                mov     [ebp+tmp1], eax
                mov     eax, [ebp+posn]
                mov     ecx, [ebp+tmp1]
                mov     ecx, [ecx]      ; s->blk_len
                xor     edx, edx
                div     ecx
                mov     [ebp+ix], eax   ; ix = posn / s->blk_len;
                mov     eax, [ebp+s]
                add     eax, 28
                mov     ecx, [ebp+s]
                add     ecx, 4
                mov     [ebp+tmp2], eax
                mov     eax, [ebp+posn]
                mov     [ebp+tmp3], ecx
                mov     ecx, [ebp+tmp3]
                mov     ecx, [ecx]      ; s->blk_len
                xor     edx, edx
                div     ecx
                mov     eax, [ebp+tmp2]
                mov     [eax], edx      ; s->wpos = posn % s->blk_len;

sfw_3:                                  ; ...
                mov     eax, [ebp+s]
                add     eax, 32
                mov     ecx, [ebp+posn]
                mov     [eax], ecx      ; s->wptr = posn;
                mov     eax, [ebp+s]
                add     eax, 24
                mov     ecx, [ebp+s]
                add     ecx, 48
                mov     edx, [ebp+ix]
                shl     edx, 2
                mov     [ebp+tmp4], eax ; s->wblk address
                mov     eax, [ecx]
                add     eax, edx        ; s->blk_ptrs[ix] address
                mov     ecx, [ebp+tmp4]
                mov     [ecx], eax      ; s->wblk = &s->blk_ptrs[ix];
                mov     eax, [ebp+s]
                add     eax, 28
                mov     ecx, [eax]
                cmp     ecx, 0
                jz      sfw_4
                jmp     sfw_5
; ---------------------------------------------------------------------------

sfw_4:                                  ; ...
                mov     eax, [ebp+s]    ; if (!s->wpos) {
                add     eax, 28
                mov     ecx, [ebp+s]
                add     ecx, 4
                mov     edx, [ecx]
                mov     [eax], edx      ; s->wpos = s->blk_len;
                mov     eax, [ebp+s]
                add     eax, 24
                mov     ecx, [eax]
                mov     edx, ecx
                add     ecx, -4
                mov     [eax], ecx      ; s->wblk--;

sfw_5:                                  ; ...
                mov     eax, [ebp+len]
                push    eax
                mov     eax, [ebp+data]
                push    eax
                mov     eax, [ebp+s]
                push    eax
                call    saa_wbytes      ; saa_wbytes(s, data, len);
                add     esp, 12
                leave
                retn
saa_fwrite      endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

                public saa_fpwrite
saa_fpwrite     proc near

len             = dword ptr -8
data            = dword ptr -4
s               = dword ptr  8
fp              = dword ptr  0Ch

                push    ebp             ; void saa_fpwrite(struct SAA *s, FILE * fp)
                mov     ebp, esp
                sub     esp, 8          ; const char *data;
                nop                     ; size_t len;
                mov     eax, [ebp+s]
                push    eax
                call    saa_rewind      ; saa_rewind(s);
                add     esp, 4

sfpw_1:                                 ; ...
                mov     eax, [ebp+s]    ; while (len = s->datalen, (data = saa_rbytes(s, &len)) != NULL)
                add     eax, 20
                mov     ecx, [eax]
                mov     [ebp+len], ecx
                lea     eax, [ebp+len]
                push    eax
                mov     eax, [ebp+s]
                push    eax
                call    saa_rbytes      ; saa_rbytes(s, &len)
                add     esp, 8
                mov     [ebp+data], eax
                cmp     eax, 0
                jz      sfpw_2
                mov     eax, [ebp+fp]
                push    eax
                mov     eax, [ebp+len]
                push    eax
                mov     eax, [ebp+data]
                push    eax
                call    nasm_write      ; nasm_write(data, len, fp);
                add     esp, 12
                jmp     short sfpw_1
; ---------------------------------------------------------------------------

sfpw_2:                                 ; ...
                leave
                retn
saa_fpwrite     endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

                public saa_write8
saa_write8      proc near

s               = dword ptr  8
v               = byte ptr  0Ch

                push    ebp             ; void saa_write8(struct SAA *s, uint8_t v)
                mov     ebp, esp
                sub     esp, 0
                nop
                mov     eax, 1
                push    eax
                lea     eax, [ebp+v]
                push    eax
                mov     eax, [ebp+s]
                push    eax
                call    saa_wbytes      ; saa_wbytes(s, &v, 1);
                add     esp, 12
                leave
                retn
saa_write8      endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

                public saa_write16
saa_write16     proc near

s               = dword ptr  8
v               = word ptr  0Ch

                push    ebp             ; void saa_write16(struct SAA *s, uint16_t v)
                mov     ebp, esp
                sub     esp, 0
                nop
                movzx   eax, [ebp+v]
                mov     [ebp+v], ax     ; v = cpu_to_le16(v);
                mov     eax, 2
                push    eax
                lea     eax, [ebp+v]
                push    eax
                mov     eax, [ebp+s]
                push    eax
                call    saa_wbytes      ; saa_wbytes(s, &v, 2);
                add     esp, 12
                leave
                retn
saa_write16     endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

                public saa_write32
saa_write32     proc near

s               = dword ptr  8
v               = dword ptr  0Ch

                push    ebp             ; void saa_write32(struct SAA *s, uint32_t v)
                mov     ebp, esp
                sub     esp, 0
                nop
                mov     eax, [ebp+v]
                mov     [ebp+v], eax    ; v = cpu_to_le32(v);
                mov     eax, 4
                push    eax
                lea     eax, [ebp+v]
                push    eax
                mov     eax, [ebp+s]
                push    eax
                call    saa_wbytes      ; saa_wbytes(s, &v, 4);
                add     esp, 12
                leave
                retn
saa_write32     endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

                public saa_write64
saa_write64     proc near

s               = dword ptr  8
v               = dword ptr  0Ch
v_h             = dword ptr  10h

                push    ebp             ; void saa_write64(struct SAA *s, uint64_t v)
                mov     ebp, esp
                sub     esp, 0
                nop
                mov     eax, [ebp+v]
                mov     ecx, [ebp+v_h]
                mov     [ebp+v], eax    ; v = cpu_to_le64(v);
                mov     [ebp+v_h], ecx
                mov     eax, 8
                push    eax
                lea     eax, [ebp+v]
                push    eax
                mov     eax, [ebp+s]
                push    eax
                call    saa_wbytes      ; saa_wbytes(s, &v, 8);
                add     esp, 12
                leave
                retn
saa_write64     endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

                public saa_writeaddr
saa_writeaddr   proc near

s               = dword ptr  8
v               = dword ptr  0Ch
v_h             = dword ptr  10h
len             = dword ptr  14h

                push    ebp             ; void saa_writeaddr(struct SAA *s, uint64_t v, size_t len)
                mov     ebp, esp
                sub     esp, 0
                nop
                mov     eax, [ebp+v]
                mov     ecx, [ebp+v_h]
                mov     [ebp+v], eax    ; v = cpu_to_le64(v);
                mov     [ebp+v_h], ecx
                mov     eax, [ebp+len]
                push    eax
                lea     eax, [ebp+v]
                push    eax
                mov     eax, [ebp+s]
                push    eax
                call    saa_wbytes      ; saa_wbytes(s, &v, len);
                add     esp, 12
                leave
                retn
saa_writeaddr   endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

                public saa_wleb128u
saa_wleb128u    proc near

len             = dword ptr -4Ch
byte            = byte ptr -45h
ptemp           = dword ptr -44h
temp            = byte ptr -40h
psaa            = dword ptr  8
value           = dword ptr  0Ch

                push    ebp             ; /* write unsigned LEB128 value to SAA */
                                        ; void saa_wleb128u(struct SAA *psaa, int value)
                mov     ebp, esp
                sub     esp, 76
                nop                     ; char temp[64], *ptemp;
                lea     eax, [ebp+temp] ; uint8_t byte;
                mov     [ebp+ptemp], eax ; ptemp = temp;
                mov     eax, 0          ; int len;
                mov     [ebp+len], eax  ; len = 0;

swlu_1:                                 ; ...
                mov     eax, [ebp+value] ; do {
                and     eax, 7Fh
                mov     [ebp+byte], al  ; byte = value & 127;
                mov     eax, [ebp+value]
                sar     eax, 7
                mov     [ebp+value], eax ; value >>= 7;
                mov     eax, [ebp+value]
                cmp     eax, 0          ; if (value != 0) /* more bytes to come */
                jz      swlu_2
                movzx   eax, [ebp+byte]
                or      eax, 80h        ; byte |= 0x80;
                mov     [ebp+byte], al

swlu_2:                                 ; ...
                mov     eax, [ebp+ptemp]
                movzx   ecx, [ebp+byte]
                shl     ecx, 24
                sar     ecx, 24
                mov     [eax], cl       ; *ptemp = byte;
                mov     eax, [ebp+ptemp]
                mov     ecx, eax
                inc     eax
                mov     [ebp+ptemp], eax ; ptemp++;
                mov     eax, [ebp+len]
                mov     ecx, eax
                inc     eax
                mov     [ebp+len], eax  ; len++;
                mov     eax, [ebp+value]
                cmp     eax, 0
                jnz     swlu_1          ; } while (value != 0);
                mov     eax, [ebp+len]
                push    eax
                lea     eax, [ebp+temp]
                push    eax
                mov     eax, [ebp+psaa]
                push    eax
                call    saa_wbytes      ; saa_wbytes(psaa, temp, len);
                add     esp, 12
                leave
                retn
saa_wleb128u    endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

                public saa_wleb128s
saa_wleb128s    proc near

tmp             = dword ptr -5Ch
len             = dword ptr -58h
size            = dword ptr -54h
negative        = dword ptr -50h
more            = dword ptr -4Ch
byte            = byte ptr -45h
ptemp           = dword ptr -44h
temp            = byte ptr -40h
psaa            = dword ptr  8
value           = dword ptr  0Ch

                push    ebp             ; /* write signed LEB128 value to SAA */
                                        ; void saa_wleb128s(struct SAA *psaa, int value)
                mov     ebp, esp
                sub     esp, 92         ; char temp[64], *ptemp;
                nop                     ; uint8_t byte;
                lea     eax, [ebp+temp]
                mov     [ebp+ptemp], eax ; ptemp = temp;
                mov     eax, 1          ; bool more, negative;
                mov     [ebp+more], eax ; more = 1;
                mov     eax, [ebp+value] ; int size, len;
                cmp     eax, 0
                mov     eax, 0
                setl    al
                mov     [ebp+negative], eax ; negative = (value < 0);
                mov     eax, 32         ; sizeof(int) * 8 = 32
                mov     [ebp+size], eax ; size = sizeof(int) * 8;
                mov     eax, 0
                mov     [ebp+len], eax  ; len = 0;

swls_1:                                 ; ...
                mov     eax, [ebp+more] ; while (more) {
                cmp     eax, 0
                jz      swls_9
                mov     eax, [ebp+value]
                and     eax, 7Fh        ; byte = value & 0x7f;
                mov     [ebp+byte], al
                mov     eax, [ebp+value]
                sar     eax, 7
                mov     [ebp+value], eax ; value >>= 7;
                mov     eax, [ebp+negative]
                cmp     eax, 0          ; if (negative)
                jz      swls_2
                mov     eax, [ebp+size] ; /* sign extend */
                sub     eax, 7          ; (size - 7)
                mov     ecx, 1
                mov     [ebp+tmp], ecx
                mov     ecx, eax
                mov     eax, [ebp+tmp]
                shl     eax, cl
                mov     ecx, 0
                sub     ecx, eax        ; neg
                mov     eax, [ebp+value]
                or      eax, ecx
                mov     [ebp+value], eax ; value |= -(1 << (size - 7));

swls_2:                                 ; ...
                mov     eax, [ebp+value] ; /* sign bit of byte is second high order bit (0x40) */
                cmp     eax, 0          ; if ((value == 0 && !(byte & 0x40)) ||
                                        ;             ((value == -1) && (byte & 0x40)))
                jnz     swls_4
                movzx   eax, [ebp+byte]
                and     eax, 40h
                cmp     eax, 0
                jz      swls_3
                jmp     swls_4
; ---------------------------------------------------------------------------

swls_3:                                 ; ...
                jmp     swls_6
; ---------------------------------------------------------------------------

swls_4:                                 ; ...
                mov     eax, [ebp+value]
                cmp     eax, -1
                jnz     swls_5
                movzx   eax, [ebp+byte]
                and     eax, 40h
                cmp     eax, 0
                jz      swls_5
                jmp     swls_6
; ---------------------------------------------------------------------------

swls_5:                                 ; ...
                jmp     swls_7
; ---------------------------------------------------------------------------

swls_6:                                 ; ...
                mov     eax, 0
                mov     [ebp+more], eax ; more = 0;
                jmp     swls_8
; ---------------------------------------------------------------------------

swls_7:                                 ; ...
                movzx   eax, [ebp+byte] ; else
                or      eax, 80h
                mov     [ebp+byte], al  ; byte |= 0x80;

swls_8:                                 ; ...
                mov     eax, [ebp+ptemp]
                movzx   ecx, [ebp+byte]
                shl     ecx, 24
                sar     ecx, 24
                mov     [eax], cl       ; *ptemp = byte;
                mov     eax, [ebp+ptemp]
                mov     ecx, eax
                inc     eax
                mov     [ebp+ptemp], eax ; ptemp++;
                mov     eax, [ebp+len]
                mov     ecx, eax
                inc     eax
                mov     [ebp+len], eax  ; len++;
                jmp     swls_1
; ---------------------------------------------------------------------------

swls_9:                                 ; ...
                mov     eax, [ebp+len]
                push    eax
                lea     eax, [ebp+temp]
                push    eax
                mov     eax, [ebp+psaa]
                push    eax
                call    saa_wbytes      ; saa_wbytes(psaa, temp, len);
                add     esp, 12
                leave
                retn
saa_wleb128s    endp

_text           ends

; ===========================================================================

; Segment type: Pure data
; Segment permissions: Read/Write
_data           segment dword public 'DATA' use32
                assume cs:_data
                ;org 8001018h
L_199           db 'saa.c',0            ; ...
L_200           db '(s->wpos % s->elem_len) == 0',0 ; ...
L_201           db 'saa.c',0            ; ...
L_202           db 's->wpos == s->blk_len',0 ; ...
L_203           db 'saa.c',0            ; ...
L_204           db '(s->rpos % s->elem_len) == 0',0 ; ...
L_205           db 'saa.c',0            ; ...
L_206           db 's->rptr + len <= s->datalen',0 ; ...
L_207           db 'saa.c',0            ; ...
L_208           db 'posn + len <= s->datalen',0 ; ...
L_209           db 'saa.c',0            ; ...
L_210           db 'posn <= s->datalen',0 ; ...
_data           ends

; ===========================================================================

; Segment type: Zero-length
; Segment permissions: Read/Write
_bss            segment dword public 'BSS' use32
_bss            ends

; ===========================================================================

; Segment type: Externs
; extern
                extrn __ashldi3:near    ; ...
                extrn nasm_zalloc:near  ; ...
                extrn nasm_malloc:near  ; ...
                extrn nasm_free:near    ; ...
                extrn nasm_realloc:near ; ...
                extrn nasm_assert_failed:near ; ...
                extrn memcpy:near       ; ...
                extrn memset:near       ; ...
                extrn strlen:near       ; ...
                extrn nasm_write:near   ; ...


                end
